;****************************************************************************
; *                                                                        *
; * The Mortal Kombat II                                                   *
; * (c) 1993 Williams Electronics Games, Inc.                              *
; *                                                                        *
;****************************************************************************

; **************************************************************************
; *                                                                        *
; * The sound call table maps sound calls from the host to playlists.      *
; * It must be started with the keyword SOUNDCALLS.                        *
; *                                                                        *
; **************************************************************************

SOUNDCALLS				

	0	immed		0

	1	immed		1	; Tune 1
	2	immed		2
	3	immed		3
	4	immed		4
	5	immed		5	; Tune 2
	6	immed		6
	7	immed		7
	8	immed		8
	9	immed		9	; Tune 3

	10	immed		10
	11	immed		11
	12	immed		12
	13	immed		13	; Tune 4
	14	immed		14
	15	immed		15
	16	immed		16
	17	immed		17	; Tune 5
	18	immed		18
	19	immed		19

	20	immed		20
	21	immed		21	; Tune 6
	22	immed		22
	23	immed		23
	24	immed		24
	25	immed		25	; Tune 7
	26	immed		26
	27	immed		27
	28	immed		28

	50	immed		50	; Intro
	51	immed		51
	52	immed		52
	53	immed		53
	54	immed		54
	55	immed		55
	56	immed		56
	57	immed		57
	58	immed		58
	59	immed		59

	60	immed		60
	61	immed		61
	62	immed		62
	63	immed		63
	64	immed		64
	65	immed		65
	66	immed		66

	70	immed		70
	71	immed		71
	72	immed		72
	
	80	marked		1, 51
	81	marked		2, 55

	90	immed		90
	91	immed		91

	99	immed		99

	100	immed		100	; Hits, etc.
	101	immed		101
	102	immed		102
	103	immed		103
	104	immed		104
	105	immed		105
	106	immed		106
	107	immed		107
	108	immed		108
	109	immed		109

	110	immed		110
	111	immed		111
	112	immed		112
	113	immed		113
	114	immed		114
	115	immed		115
	116	immed		116
	117	immed		117
	118	immed		118
	119	immed		119

	120	immed		120
	121	immed		121
	122	immed		122
	123	immed		123
	124	immed		124
	125	immed		125
	126	immed		126
	127	immed		127
	128	immed		128
	129	immed		129

	130	immed		130
	131	immed		131
	132	immed		132
	133	immed		133
	134	immed		134
	135	immed		135
	136	immed		136
	137	immed		137
	138	immed		138
	139	immed		139

	140	immed		140
	141	immed		141
	142	immed		142
	143	immed		143
	144	immed		144
	145	immed		145
	146	immed		146
	147	immed		147
	148	immed		148
	149	immed		149

	150	immed		150
	151	immed		151
	152	immed		152
	153	immed		153
	154	immed		154
	155	immed		155
	156	immed		156
	157	immed		157
	158	immed		158
	159	immed		159

	160	immed		160
	161	immed		161
	162	immed		162
	163	immed		163
	164	immed		164
	165	immed		165
	166	immed		166
	167	immed		167
	168	immed		168
	169	immed		169

	170	immed		170
	171	immed		171
	172	immed		172
	173	immed		173
	174	immed		174
	175	immed		175
	176	immed		176
	177	immed		177
	178	immed		178
	179	immed		179

	180	immed		180
	181	immed		181
	182	immed		182
	183	immed		183
	184	immed		184
	185	immed		185
	186	immed		186
	187	immed		187
	188	immed		188
	189	immed		189

	190	immed		190
	191	immed		191
	192	immed		192
	193	immed		193
	194	immed		194
	195	immed		195
	196	immed		196
	197	immed		197
	198	immed		198
	199	immed		199

	200	immed		200
	201	immed		201
	202	immed		202
	203	immed		203
	204	immed		204
	205	immed		205
	206	immed		206
	207	immed		207
	208	immed		208
	209	immed		209

	210	immed		210
	211	immed		211
	212	immed		212
	213	immed		213
	214	immed		214
	215	immed		215
	216	immed		216
	217	immed		217
	218	immed		218
	219	immed		219

	220	immed		220
	221	immed		221
	222	immed		222
	223	immed		223
	224	immed		224
	225	immed		225
	226	immed		226
	227	immed		227
	228	immed		228
	229	immed		229

	230	immed		230
	231	immed		231
	232	immed		232
	233	immed		233
	234	immed		234
	235	immed		235
	236	immed		236
	237	immed		237
	238	immed		238
	239	immed		239

	240	immed		240
	241	immed		241
	242	immed		242
	243	immed		243
	244	immed		244
	245	immed		245
	246	immed		246
	247	immed		247
	248	immed		248
	249	immed		249

	250	immed		250
	251	immed		251
	252	immed		252
	253	immed		253
	254	immed		254
	255	immed		255
	256	immed		256
	257	immed		257
	258	immed		258
	259	immed		259

	260	immed		260
	261	immed		261
	262	immed		262
	263	immed		263
	264	immed		264
	265	immed		265
	266	immed		266
	267	immed		267
	268	immed		268
	269	immed		269

	270	immed		270
	271	immed		271
	272	immed		272
	273	immed		273
	274	immed		274
	275	immed		275
	276	immed		276
	277	immed		277
	278	immed		278
	279	immed		279

	280	immed		280
	281	immed		281
	282	immed		282
	283	immed		283
	284	immed		284
	285	immed		285
	286	immed		286
	287	immed		287
	288	immed		288
	289	immed		289

	290	immed		290
	291	immed		291
	292	immed		292
	293	immed		293
	294	immed		294
	295	immed		295
	296	immed		296
	297	immed		297

	300	immed		300	; Weapon FX
	301	immed		301
	302	immed		302
	303	immed		303
	304	immed		304
	305	immed		305
	306	immed		306
	307	immed		307
	308	immed		308
	309	immed		309

	310	immed		310
	311	immed		311
	312	immed		312
	313	immed		313
	314	immed		314
	315	immed		315
	316	immed		316
	317	immed		317
	318	immed		318
	319	immed		319

	320	immed		320
	321	immed		321
	322	immed		322
	323	immed		323
	324	immed		324
	325	immed		325
	326	immed		326
	327	immed		327
	328	immed		328
	329	immed		329

	330	immed		330
	331	immed		331
	332	immed		332
	333	immed		333
	334	immed		334
	335	immed		335
	336	immed		336
	337	immed		337
	338	immed		338
	339	immed		339

	340	immed		340
	341	immed		341
	342	immed		342
	343	immed		343
	344	immed		344
	345	immed		345
	346	immed		346
	347	immed		347
	348	immed		348
	349	immed		349

	350	immed		350
	351	immed		351
	352	immed		352
	353	immed		353
	354	immed		354
	355	immed		355
	356	immed		356
	357	immed		357
	358	immed		358
	359	immed		359

	360	immed		360
	361	immed		361
	362	immed		362
	366	immed		366
	367	immed		367
	368	immed		368
	369	immed		369

	370	immed		370
	371	immed		371
	372	immed		372
	373	immed		373
	374	immed		374
	375	immed		375
	376	immed		376
	377	immed		377
	378	immed		378
	379	immed		379

	380	immed		380
	381	immed		381
	382	immed		382
	383	immed		383
	384	immed		384
	385	immed		385
	386	immed		386
	387	immed		387
	388	immed		388
	389	immed		389

	390	immed		390
	391	immed		391
	392	immed		392
	393	immed		393
	394	immed		394
	395	immed		395
	396	immed		396
	397	immed		397
	398	immed		398
	399	immed		399

	400	immed		400
	401	immed		401
	402	immed		402
	403	immed		403
	404	immed		404
	405	immed		405
	406	immed		406
	407	immed		407
	408	immed		408
	409	immed		409

	410	immed		410
	411	immed		411
	412	immed		412
	413	immed		413
	414	immed		414
	415	immed		415
	416	immed		416
	417	immed		417
	418	immed		418
	419	immed		419

	420	immed		420
	421	immed		421
	422	immed		422
	423	immed		423
	424	immed		424
	425	immed		425
	426	immed		426
	427	immed		427
	428	immed		428
	429	immed		429

	430	immed		430
	431	immed		431
	432	immed		432
	433	immed		433
	434	immed		434
	435	immed		435
	436	immed		436
	437	immed		437
	438	immed		438
	439	immed		439

	440	immed		440
	441	immed		441
	442	immed		442
	443	immed		443
	444	immed		444
	445	immed		445
	446	immed		446
	447	immed		447
	448	immed		448
	449	immed		449

	450	immed		450
	451	immed		451
	452	immed		452
	453	immed		453
	454	immed		454
	455	immed		455
	456	immed		456
	457	immed		457
	458	immed		458
	459	immed		459

	460	immed		460
	461	immed		461
	462	immed		462
	463	immed		463
	464	immed		464
	465	immed		465
	466	immed		466
	467	immed		467
	468	immed		468
	469	immed		469

	470	immed		470
	471	immed		471
	472	immed		472
	473	immed		473
	474	immed		474
	475	immed		475
	476	immed		476
	477	immed		477
	478	immed		478
	479	immed		479

	480	immed		480
	481	immed		481
	482	immed		482
	483	immed		483
	484	immed		484
	485	immed		485
	486	immed		486
	487	immed		487
	488	immed		488
	489	immed		489

	490	immed		490
	491	immed		491
	492	immed		492
	493	immed		493
	494	immed		494
	495	immed		495
	496	immed		496
	497	immed		497

	500	immed		500	; General FX
	501	immed		501
	502	immed		502
	503	immed		503
	504	immed		504
	505	immed		505
	506	immed		506
	507	immed		507
	508	immed		508
	509	immed		509

	510	immed		510
	511	immed		511
	512	immed		512
	513	immed		513
	514	immed		514
	515	immed		515
	516	immed		516
	517	immed		517
	518	immed		518
	519	immed		519

	520	immed		520
	521	immed		521
	522	immed		522
	523	immed		523
	524	immed		524
	525	immed		525
	526	immed		526
	527	immed		527
	528	immed		528
	529	immed		529

	530	immed		530
	531	immed		531
	532	immed		532
	533	immed		533
	534	immed		534
	535	immed		535
	536	immed		536
	537	immed		537
	538	immed		538
	539	immed		539

	540	immed		540
	541	immed		541
	542	immed		542
	543	immed		543
	544	immed		544
	545	immed		545
	546	immed		546
	547	immed		547
	548	immed		548
	549	immed		549

	550	immed		550
	551	immed		551
	552	immed		552
	553	immed		553
	554	immed		554
	555	immed		555
	556	immed		556
	557	immed		557
	558	immed		558
	559	immed		559

	560	immed		560
	561	immed		561
	562	immed		562
	563	immed		563
	564	immed		564
	565	immed		565
	566	immed		566
	567	immed		567
	568	immed		568
	569	immed		569

	570	immed		570
	571	immed		571
	572	immed		572
	573	immed		573
	574	immed		574
	575	immed		575
	576	immed		576
	577	immed		577
	578	immed		578
	579	immed		579

	580	immed		580
	581	immed		581
	582	immed		582
	583	immed		583
	584	immed		584
	585	immed		585
	586	immed		586
	587	immed		587
	588	immed		588
	589	immed		589

	590	immed		590
	591	immed		591
	592	immed		592
	593	immed		593
	594	immed		594
	595	immed		595
	596	immed		596
	597	immed		597
	598	immed		598

	600	immed		600	; Player Speech
	601	immed		601
	602	immed		602
	603	immed		603
	604	immed		604
	605	immed		605
	606	immed		606
	607	immed		607
	608	immed		608
	609	immed		609

	610	immed		610
	611	immed		611
	612	immed		612
	613	immed		613
	614	immed		614
	615	immed		615
	616	immed		616
	617	immed		617
	618	immed		618
	619	immed		619

	620	immed		620
	621	immed		621
	622	immed		622
	623	immed		623
	624	immed		624
	625	immed		625
	626	immed		626
	627	immed		627
	628	immed		628
	629	immed		629

	630	immed		630
	631	immed		631
	632	immed		632
	633	immed		633
	634	immed		634
	635	immed		635
	636	immed		636
	637	immed		637
	638	immed		638

	642	immed		642
	643	immed		643
	644	immed		644
	645	immed		645
	646	immed		646
	647	immed		647

	650	immed		650
	651	immed		651
	652	immed		652
	653	immed		653
	654	immed		654
	655	immed		655
	656	immed		656
	657	immed		657
	658	immed		658
	659	immed		659

	660	immed		660
	661	immed		661
	662	immed		662
	663	immed		663
	664	immed		664
	665	immed		665
	666	immed		666
	667	immed		667
	668	immed		668
	669	immed		669

	670	immed		670
	671	immed		671
	672	immed		672
	673	immed		673
	674	immed		674
	675	immed		675
	676	immed		676
	677	immed		677
	678	immed		678
	679	immed		679

	680	immed		680
	681	immed		681
	682	immed		682
	683	immed		683
	684	immed		684
	685	immed		685
	686	immed		686
	687	immed		687
	688	immed		688
	689	immed		689

	690	immed		690
	691	immed		691
	692	immed		692
	693	immed		693
	694	immed		694
	695	immed		695
	696	immed		696
	697	immed		697

	700	immed		700	; More Player Speech
	701	immed		701
	702	immed		702
	703	immed		703
	704	immed		704
	705	immed		705
	706	immed		706
	707	immed		707
	708	immed		708
	709	immed		709

	710	immed		710
	711	immed		711
	712	immed		712
	713	immed		713
	714	immed		714
	715	immed		715
	716	immed		716
	717	immed		717
	718	immed		718
	719	immed		719

	720	immed		720
	721	immed		721
	722	immed		722
	723	immed		723
	724	immed		724
	725	immed		725
	726	immed		726
	727	immed		727
	728	immed		728
	729	immed		729

	730	immed		730
	731	immed		731
	732	immed		732
	733	immed		733
	734	immed		734
	735	immed		735
	736	immed		736
	737	immed		737
	738	immed		738
	739	immed		739

	740	immed		740
	741	immed		741
	742	immed		742
	743	immed		743
	744	immed		744
	745	immed		745
	746	immed		746
	747	immed		747

	750	immed		750
	751	immed		751
	752	immed		752
	753	immed		753
	754	immed		754
	755	immed		755
	756	immed		756
	757	immed		757
	758	immed		758
	759	immed		759

	760	immed		760
	761	immed		761
	762	immed		762
	763	immed		763
	764	immed		764
	765	immed		765
	766	immed		766
	767	immed		767
	768	immed		768
	769	immed		769

	770	immed		770
	771	immed		771
	772	immed		772
	773	immed		773
	774	immed		774
	775	immed		775
	776	immed		776
	777	immed		777
	778	immed		778
	779	immed		779

	780	immed		780
	781	immed		781
	782	immed		782
	783	immed		783
	784	immed		784
	785	immed		785
	786	immed		786
	787	immed		787
	788	immed		788
	789	immed		789

	790	immed		790
	791	immed		791

	800	immed		800
	801	immed		801
	802	immed		802
	803	immed		803
	804	immed		804
	805	immed		805
	806	immed		806
	807	immed		807
	808	immed		808
	809	immed		809

	810	immed		810
	811	immed		811
	812	immed		812
	813	immed		813
	814	immed		814
	815	immed		815
	816	immed		816
	817	immed		817
	818	immed		818
	819	immed		819

	820	immed		820
	821	immed		821
	822	immed		822
	823	immed		823
	824	immed		824
	825	immed		825
	826	immed		826
	827	immed		827
	828	immed		828
	829	immed		829

	830	immed		830
	831	immed		831
	832	immed		832
	836	immed		836
	837	immed		837
	838	immed		838
	839	immed		839
	840	immed		840
	841	immed		841
	842	immed		842
	843	immed		843
	844	immed		844

	850	immed		850
	851	immed		851
	852	immed		852
	853	immed		853
	854	immed		854
	855	immed		855
	856	immed		856
	857	immed		857
	858	immed		858
	859	immed		859

	860	immed		860
	861	immed		861
	862	immed		862
	863	immed		863
	864	immed		864
	865	immed		865
	866	immed		866
	867	immed		867
	868	immed		868
	869	immed		869

	870	immed		870
	871	immed		871
	872	immed		872
	873	immed		873
	874	immed		874
	875	immed		875
	876	immed		876
	877	immed		877
	878	immed		878
	879	immed		879

	880	immed		880
	881	immed		881
	882	immed		882
	883	immed		883
	884	immed		884
	885	immed		885
	886	immed		886
	887	immed		887
	888	immed		888
	889	immed		889

	890	immed		890
	891	immed		891
	892	immed		892
	893	immed		893
	894	immed		894

	995	immed		995	; Kill track 0
	996	immed		996	; Kill track 1
	997	immed		997	; Kill track 2
	998	immed		998	; Kill track 3
	999	immed		999	; version ack

	900	immed		900
	901	immed		901
	902	immed		902
	903	immed		903
	904	immed		904
	905	immed		905
	906	immed		906
	907	immed		907
	908	immed		908
	909	immed		909

	910	immed		910
	911	immed		911
	912	immed		912
	913	immed		913
	914	immed		914
	915	immed		915
	916	immed		916
	917	immed		917
	918	immed		918
	919	immed		919

	920	immed		920
	921	immed		921
	922	immed		922
	923	immed		923
	924	immed		924
	925	immed		925
	926	immed		926
	927	immed		927
	928	immed		928
	929	immed		929

	930	immed		930
	931	immed		931
	932	immed		932
	933	immed		933
	934	immed		934
	935	immed		935
	936	immed		936
	937	immed		937
	938	immed		938
	939	immed		939

	940	immed		940
	941	immed		941
	942	immed		942
	943	immed		943
	944	immed		944
	945	immed		945
	946	immed		946
	947	immed		947
	948	immed		948
	949	immed		949

	950	immed		950
	951	immed		951
	952	immed		952
	953	immed		953
	954	immed		954
	955	immed		955
	956	immed		956
	957	immed		957
	958	immed		958
	959	immed		959

	960	immed		960
	961	immed		961
	962	immed		962
	963	immed		963
	964	immed		964
	965	immed		965
	966	immed		966
	967	immed		967
	968	immed		968
	969	immed		969

	970	immed		970
	971	immed		971
	972	immed		972
	973	immed		973
	974	immed		974
	975	immed		975
	976	immed		976
	977	immed		977

	980	immed		980
	981	immed		981
	982	immed		982
	983	immed		983
	984	immed		984
	985	immed		985
	986	immed		986
	987	immed		987
	988	immed		988

	1000	immed		1000
	1001	immed		1001

	1020	immed		1020
	1021	immed		1021
	1022	immed		1022
	1023	immed		1023
	1024	immed		1024
	1025	immed		1025
	1026	immed		1026
	1027	immed		1027
	1028	immed		1028
	1029	immed		1029

	1030	immed		1030
	1031	immed		1031
	1032	immed		1032
	1033	immed		1033
	1034	immed		1034
	1035	immed		1035
	1036	immed		1036
	1037	immed		1037
	1038	immed		1038
	1039	immed		1039

	1040	immed		1040
	1041	immed		1041
	1042	immed		1042
	1043	immed		1043
	1044	immed		1044
	1045	immed		1045
	1046	immed		1046
	1047	immed		1047
	1048	immed		1048
	1049	immed		1049

	1050	immed		1050
	1051	immed		1051
	1052	immed		1052
	1053	immed		1053
	1054	immed		1054
	1055	immed		1055
	1056	immed		1056
	1057	immed		1057
	1058	immed		1058
	1059	immed		1059

	1060	immed		1060
	1061	immed		1061
	1062	immed		1062
	1063	immed		1063
	1064	immed		1064
	1065	immed		1065
	1066	immed		1066
	1067	immed		1067
	1068	immed		1068
	1069	immed		1069

	1070	immed		1070

	1100	immed		1100
	1101	immed		1101
	1102	immed		1102
	1103	immed		1103
	1104	immed		1104
	1105	immed		1105
	1106	immed		1106
	1107	immed		1107
	1108	immed		1108
	1109	immed		1109

	1110	immed		1110
	1111	immed		1111
	1112	immed		1112
	1113	immed		1113
	1114	immed		1114
	1115	immed		1115
	1116	immed		1116
	1117	immed		1117
	1118	immed		1118
	1119	immed		1119

	1120	immed		1120
	1121	immed		1121
	1122	immed		1122
	1123	immed		1123
	1124	immed		1124
	1125	immed		1125
	1126	immed		1126
	1127	immed		1127
	1128	immed		1128
	1129	immed		1129

	1130	immed		1130
	1131	immed		1131
	1132	immed		1132
	1133	immed		1133
	1134	immed		1134
	1135	immed		1135
	1136	immed		1136
	1137	immed		1137
	1138	immed		1138
	1139	immed		1139

	1140	immed		1140
	1141	immed		1141
	1142	immed		1142
	1143	immed		1143
	1144	immed		1144
	1145	immed		1145
	1146	immed		1146
	1147	immed		1147
	1148	immed		1148
	1149	immed		1149

	1150	immed		1150
	1151	immed		1151
	1152	immed		1152
	1153	immed		1153
	1154	immed		1154
	1155	immed		1155
	1156	immed		1156
	1157	immed		1157
	1158	immed		1158
	1159	immed		1159

	1160	immed		1160
	1161	immed		1161
	1162	immed		1162
	1166	immed		1166
	1167	immed		1167
	1168	immed		1168

	1172	immed		1172
	1173	immed		1173
	1174	immed		1174
	1175	immed		1175
	1176	immed		1176
	1177	immed		1177
	1178	immed		1178
	1179	immed		1179

	1180	immed		1180
	1181	immed		1181
	1182	immed		1182
	1183	immed		1183
	1184	immed		1184
	1185	immed		1185
	1186	immed		1186
	1187	immed		1187
	1188	immed		1188
	1189	immed		1189

	1190	immed		1190
	1191	immed		1191
	1192	immed		1192
	1193	immed		1193
	1194	immed		1194
	1195	immed		1195
	1196	immed		1196
	1197	immed		1197
	1198	immed		1198

	1200	immed		1200
	1201	immed		1201
	1202	immed		1202
	1203	immed		1203
	1204	immed		1204
	1205	immed		1205
	1206	immed		1206
	1207	immed		1207
	1208	immed		1208
	1209	immed		1209

	1210	immed		1210
	1211	immed		1211
	1212	immed		1212
	1213	immed		1213
	1214	immed		1214
	1215	immed		1215
	1216	immed		1216
	1217	immed		1217
	1218	immed		1218
	1219	immed		1219

	1220	immed		1220

	1250	immed		1250
	1251	immed		1251
	1252	immed		1252
	1253	immed		1253
	1254	immed		1254
	1255	immed		1255
	1256	immed		1256
	1257	immed		1257
	1258	immed		1258
	1259	immed		1259

	1260	immed		1260
	1261	immed		1261
	1262	immed		1262
	1263	immed		1263
	1264	immed		1264
	1265	immed		1265
	1266	immed		1266
	1267	immed		1267
	1268	immed		1268
	1269	immed		1269

	1270	immed		1270
	1271	immed		1271
	1272	immed		1272
	1273	immed		1273

	1288	immed		1288
	1289	immed		1289

	1290	immed		1290
	1291	immed		1291
	1292	immed		1292
	1293	immed		1293
	1294	immed		1294
	1295	immed		1295
	1296	immed		1296
	1297	immed		1297
	1298	immed		1298
	1299	immed		1299

	1300	immed		1300
	1301	immed		1301
	1302	immed		1302
	1303	immed		1303
	1304	immed		1304
	1305	immed		1305
	1306	immed		1306
	1307	immed		1307
	1308	immed		1308
	1309	immed		1309

	1310	immed		1310
	1311	immed		1311
	1312	immed		1312
	1313	immed		1313
	1314	immed		1314
	1315	immed		1315
	1316	immed		1316
	1317	immed		1317
	1318	immed		1318
	1319	immed		1319

	1320	immed		1320
	1321	immed		1321
	1322	immed		1322
	1323	immed		1323
	1324	immed		1324
	1325	immed		1325
	1326	immed		1326
	1327	immed		1327
	1328	immed		1328
	1329	immed		1329

	1330	immed		1330
	1331	immed		1331
	1332	immed		1332
	1333	immed		1333
	1334	immed		1334
	1335	immed		1335
	1336	immed		1336
	1337	immed		1337
	1338	immed		1338

	1350	immed		1350
	1351	immed		1351
	1352	immed		1352
	1353	immed		1353
	1354	immed		1354
	1355	immed		1355
	1356	immed		1356
	1357	immed		1357
	1358	immed		1358
	1359	immed		1359

	1360	immed		1360
	1361	immed		1361
	1362	immed		1362
	1363	immed		1363
	1364	immed		1364
	1365	immed		1365
	1366	immed		1366
	1367	immed		1367

	1377	immed		1377
	1378	immed		1378
	1379	immed		1379

	1380	immed		1380
	1381	immed		1381
	1382	immed		1382
	1383	immed		1383
	1384	immed		1384
	1385	immed		1385
	1386	immed		1386
	1387	immed		1387
	1388	immed		1388
	1389	immed		1389

	1390	immed		1390
	1391	immed		1391
	1392	immed		1392
	1393	immed		1393
	1394	immed		1394
	1395	immed		1395

	1400	immed		1400
	1401	immed		1401
	1402	immed		1402
END					

; **************************************************************************

; **************************************************************************
; *                                                                        *
; * The transition table must be started with the keyword TRANSITION.      *
; *                                                                        *
; **************************************************************************

TRANSITION		
END

; **************************************************************************
; *                                                                        *
; * The following are the actual playlists...                              *
; *                                                                        *
; **************************************************************************

; **************************************************************************
; *                                                                        *
; *                         Tunes and grooves                              *
; *                                                                        *
; **************************************************************************

	playlist	0, 0, 'kill sound on all tracks'
	0	stop	1
	0	stop	2
	0	stop	3
	1	end
	end

      	playlist	1, 0, 'music: Main #1 (1st fight)'
	0	setvol	0, 95
	0	play	0, 'main1a', 1
	445	play	0, 'main1b', 1
	892	play	0, 'main1b', 1
	892	loopstart	0
	0	play	0, 'main1c', 1
	890	play	0, 'main1d', 1
	890	loopend
	65535	end
	end

      	playlist	2, 0, 'music: Main #1 (2nd and 3rd fight)'
	0	setvol	0, 95
	0	play	0, 'main1b', 1
	892	play	0, 'main1d', 1
	890	play	0, 'main1c', 1
	223	loopstart	0
	0	play	0, 'main1e', 1
	222	play	0, 'main1f', 4
	1780	play	0, 'main1c', 1
	223	loopend
	65535	end
	end

      	playlist	3, 0, 'music: Finish it #1'
	0	setvol	0, 100
	0	play	0, 'finish1a', 1
	222	play	0, 'finish1b', 0
	65535	end
	end

      	playlist	4, 0, 'music: End it #1'
	0	setvol	0, 105
	0	play	0, 'end1a', 1
	415	rampdownvol	0, 30, 170
	73	play	0, 'end1bl', 0
	65535	end
	end

      	playlist	5, 0, 'music: Main #2 (1st fight)'
	0	setvol	0, 100
	0	play	0, 'main2a', 1
	430	play	0, 'main2a', 1
	363	play	0, 'main2b', 1
	67	loopstart	0
	0	play	0, 'main2c1', 1
	159	play	0, 'main2c2', 1
	269	play	0, 'main2d1', 1
	159	play	0, 'main2c2', 1
	269	play	0, 'main2e', 1
	430	play	0, 'main2f', 1
	430	loopend
	65535	end
	end

      	playlist	6, 0, 'music: Main #2 (2nd and 3rd fight)'
	0	setvol	0, 100
	0	play	0, 'main2c1', 1
	159	play	0, 'main2c2', 1
	269	play	0, 'main2d1', 1
	159	play	0, 'main2c2', 1
	269	play	0, 'main2e', 1
	430	play	0, 'main2f', 1
	430	play	0, 'main2c1', 1
	159	play	0, 'main2c2', 1
	269	loopstart	0
	0	play	0, 'main2e', 1
	430	play	0, 'main2g', 1
	430	play	0, 'main2g', 1
	396	play	0, 'main2g1', 1
	34	play	0, 'main2c1', 1
	159	play	0, 'main2c2', 1
	269	play	0, 'main2b', 1
	0	loopend
	65535	end
	end

      	playlist	7, 0, 'music: Finish it #2'
	0	setvol	0, 105
	0	play	0, 'finish2', 0
	65535	end
	end

      	playlist	8, 0, 'music: End it #2'
	0	setvol	0, 110
	0	play	0, 'end2a', 1
	4	play	0, 'end2b', 1
	200	rampdownvol	0, 30, 120
	138	downvol	0, 20
	0	rampupvol	0, 20, 30
	0	loopstart	0
	0	play	0, 'end2cl', 1
	158	loopend
	65535	end
	end

      	playlist	9, 0, 'music: Main #3 (1st fight)'
	0	setvol	0, 100
	0	play	0, 'main3a', 1
	496	play	0, 'main3b', 1
	495	play	0, 'main3a', 1
	496	loopstart	0
	0	play	0, 'main3b', 1
	495	play	0, 'main3c', 1
	495	play	0, 'main3c', 1
	495	loopend
	65535	end
	end

      	playlist	10, 0, 'music: Main #3 (2nd and 3rd fight)'
	0	setvol	0, 100
	0	play	0, 'main3a', 1
	496	play	0, 'main3b', 1
	495	play	0, 'main3c', 1
	495	play	0, 'main3c', 1
	495	loopstart	0
	0	loopstart	4
	0	play	0, 'main3c', 1
	247	play	0, 'main3d', 1
	248	loopend
	0	play	0, 'main3a', 1
	496	play	0, 'main3b', 1
	495	loopend
	65535	end
	end

      	playlist	11, 0, 'music: Finish it #3'
	0	setvol	0, 105
	0	play	0, 'finish3', 0
	65535	end
	end

      	playlist	12, 0, 'music: End it #3'
	0	setvol	0, 110
	0	play	0, 'end3a', 1
	200	rampdownvol	0, 30, 300
	308	downvol	0, 50
	0	play	0, 'end3bl', 1
	0	rampupvol	0, 50, 4
	120	play	0, 'end3bl', 0
	65535	end
	end

      	playlist	13, 0, 'music: Main #4 (1st fight)'
	0	setvol	0, 100
	0	loopstart	0
	0	play	0, 'main4a', 1
	261	play	0, 'main4a', 1
	261	play	0, 'main4b', 1
	259	play	0, 'main4a', 1
	261	play	0, 'main4c', 1
	521	play	0, 'main4d', 1
	260	loopend
	65535	end
	end

      	playlist	14, 0, 'music: Main #4 (2nd and 3rd fight)'
	0	setvol	0, 100
	0	loopstart	0
	0	play	0, 'main4a', 1
	261	play	0, 'main4a', 1
	261	play	0, 'main4c', 1
	521	play	0, 'main4d', 1
	260	play	0, 'main4e', 1
	258	play	0, 'main4d', 1
	260	play	0, 'main4e', 1
	258	play	0, 'main4d', 1
	260	loopend
	65535	end
	end

      	playlist	15, 0, 'music: Finish it #4'
	0	setvol	0, 105
	0	play	0, 'finish4', 0
	65535	end
	end

      	playlist	16, 0, 'music: End it #4'
	0	setvol	0, 105
	0	play	0, 'end4a', 1
	0	rampdownvol	0, 30, 250
	277	loopstart	0
	0	play	0, 'end4bl', 1
	0	rampupvol	0, 5, 130
	133	downvol	0, 5
	0	loopend
	65535	end
	end

      	playlist	17, 0, 'music: Main #5 (1st fight)'
	0	setvol	0, 100
	0	play	0, 'main5a', 1
	505	loopstart	0
	0	play	0, 'main5b', 1
	504	play	0, 'main5c', 1
	250	play	0, 'main5d', 1
	252	play	0, 'main5c', 1
	250	play	0, 'main5e', 1
	250	loopend
	65535	end
	end

      	playlist	18, 0, 'music: Main #5 (2nd and 3rd fight)'
	0	setvol	0, 100
	0	play	0, 'main5a', 1
	505	loopstart	0
	0	play	0, 'main5c', 1
	250	play	0, 'main5d', 1
	252	play	0, 'main5c', 1
	250	play	0, 'main5e', 1
	250	play	0, 'main5f', 1
	504	play	0, 'main5f', 1
	504	play	0, 'main5b', 1
	504	loopend
	65535	end
	end

      	playlist	19, 0, 'music: Finish it #5'
	0	setvol	0, 105
	0	play	0, 'finish5', 0
	65535	end
	end

      	playlist	20, 0, 'music: End it #5'
	0	setvol	0, 105
	0	play	0, 'end5a', 1
	40	rampdownvol	0, 20, 300
	329	play	0, 'end5b', 1
	183	loopstart	0
	0	downvol	0, 15
	0	rampupvol	0, 15, 20
	0	play	0, 'end5b', 1
	183	loopend
	65535	end
	end

      	playlist	21, 0, 'music: Main #6 (1st fight)'
	0	setvol	0, 100
	0	loopstart	0
	0	play	0, 'main6a', 1
	261	play	0, 'main6a', 1
	261	play	0, 'main6b', 1
	258	play	0, 'main6c', 1
	261	play	0, 'main6d', 1
	259	play	0, 'main6e', 1
	260	play	0, 'main6f', 1
	261	loopend
	65535	end
	end

      	playlist	22, 0, 'music: Main #6 (2nd and 3rd fight)'
	0	setvol	0, 100
	0	play	0, 'main6a', 1
	261	play	0, 'main6a', 1
	261	loopstart	0
	0	play	0, 'main6b', 1
	258	play	0, 'main6c', 1
	261	play	0, 'main6d', 1
	259	play	0, 'main6e', 1
	260	play	0, 'main6f', 1
	261	play	0, 'main6g', 1
	259	play	0, 'main6g', 1
	259	loopend
	65535	end
	end

      	playlist	23, 0, 'music: Finish it #6'
	0	setvol	0, 105
	0	play	0, 'finish6', 0
	65535	end
	end

      	playlist	24, 0, 'music: End it #6'
	0	setvol	0, 110
	0	play	0, 'end6a', 1
	40	rampdownvol	0, 30, 300
	376	downvol	0, 50
	0	play	0, 'end6bl', 1
	0	rampupvol	0, 50, 4
	232	play	0, 'end6bl', 0
	65535	end
	end

	playlist	25, 0, 'music: Main #7 (1st fight)'
	0	setvol	0, 105
	0	loopstart	0
	0	play	0, 'main7a', 1
	384	play	0, 'main7b', 1
	355	play	0, 'main7b', 1
	118	play	0, 'main7c', 1
	355	play	0, 'main7b', 1
	355	play	0, 'main7b', 1
	118	play	0, 'main7c', 1
	88	play	0, 'main7d', 1
	267	play	0, 'main7e', 1
	236	play	0, 'main7g', 1
	237	loopend
	65535	end
	end

	playlist	26, 0, 'music: Main #7 (2nd and 3rd fight)'
	0	setvol	0, 105
	0	loopstart	0
	0	play	0, 'main7a', 1
	384	play	0, 'main7b', 1
	355	play	0, 'main7b', 1
	118	play	0, 'main7c', 1
	355	play	0, 'main7b', 1
	355	play	0, 'main7b', 1
	118	play	0, 'main7c', 1
	88	play	0, 'main7d', 1
	267	play	0, 'main7e', 1
	236	play	0, 'main7f', 1
	237	play	0, 'main7e', 1
	236	play	0, 'main7f', 1
	237	play	0, 'main7e', 1
	236	play	0, 'main7g', 1
	237	loopend
	65535	end
	end

      	playlist	27, 0, 'music: Finish it #7'
	0	setvol	0, 110
	0	play	0, 'finish7', 0
	65535	end
	end

      	playlist	28, 0, 'music: End it #7'
	0	setvol	0, 110
	0	play	0, 'end7a', 1
	40	rampdownvol	0, 20, 300
	258	loopstart	0
	0	play	0, 'end7b', 1
	58	loopend
	65535	end
	end

      	playlist	50, 0, 'music: MK II select screen'
	0	setvol	0, 105
	0	loopstart	0
	0	play	0, 'introa', 1
	0	marker	1
	65	marker	1
	65	marker	1
	65	marker	1
	66	play	0, 'introb', 1
	0	marker	1
	65	marker	1
	65	marker	1
	65	marker	1
	66	loopend
	65535	end
	end

      	playlist	51, 0, 'music: Mortal Sans'
	0	setvol	0, 110
	0	play	0, 'mrtlsans', 1
	327	end
	end

      	playlist	52, 0, 'music: Begin Fatality'
	0	setvol	0, 115
	0	play	0, 'fatal1', 1
	490	rampdownvol	0, 90, 8
	8	end
	end

      	playlist	53, 0, 'music: End Fatality'
	0	setvol	0, 115
	0	play	0, 'fatal2', 1
	452	rampdownvol	0, 90, 10
	10	end
	end

      	playlist	54, 0, 'music: One Player Map'
	0	setvol	0, 110
	0	loopstart	0
	0	play	0, 'oneguy', 1
	0	marker	2
	65	marker	2
	66	marker	2
	65	marker	2
	66	marker	2
	65	marker	2
	65	marker	2
	65	marker	2
	65	loopend
	65535	end
	end

      	playlist	55, 0, 'music: End One player map'
	0	setvol	0, 110
	0	play	0, 'endguy', 1
	250	rampdownvol	0, 120, 8
	8	end
	end

      	playlist	56, 0, 'music: Buy-in tune'
	0	setvol	0, 110
	0	play	0, 'buyin', 0
	65535	end
	end

      	playlist	57, 0, 'music: MTV attract mode tune'
	0	setvol	0, 115
	0	loopstart	0
	0	play	0, 'attrct1a', 1
	97	play	0, 'attrct1b', 1
	98	play	0, 'attrct1c', 1
	34	play	0, 'attrct1d', 1
	96	play	0, 'attrct1e', 1
	129	play	0, 'attrct1f', 1
	196	play	0, 'attrct1a', 1
	97	play	0, 'attrct1b', 1
	98	downvol	0, 10
	0	play	0, 'attrct1d', 1
	34	upvol	0, 10
	0	play	0, 'attrct1e', 1
	129	play	0, 'attrct1f', 1
	196	loopend
	65535	end
	end

      	playlist	58, 0, 'music: Shang-Tsung friendship'
	0	setvol	0, 110
	0	play	0, 'fbone1', 1
	441	end
	end

      	playlist	59, 0, 'music: Liu Kang''s disco fever'
	0	setvol	0, 110
	0	play	0, 'disco', 1
	260	play	0, 'disco', 1
	281	end
	end

      	playlist	60, 0, 'music: End Show'
	0	setvol	0, 120
	0	play	0, 'endsho1', 1
	56	play	0, 'endsho2', 1
	432	setvol	0, 115
	0	play	0, 'endsho3', 1
	869	play	0, 'endsho2', 1
	432	end
	end

      	playlist	61, 0, 'music: end credits'
	0	setvol	0, 115
	0	loopstart	0
	0	play	0, 'theend1', 1
	521	play	0, 'theend1', 1
	521	play	0, 'theend2', 1
	456	play	0, 'theend2', 1
	456	play	0, 'theend3', 1
	521	loopstart	2
	0	play	0, 'attrct1a', 1
	97	play	0, 'attrct1b', 1
	98	play	0, 'attrct1c', 1
	34	play	0, 'attrct1d', 1
	96	play	0, 'attrct1e', 1
	129	play	0, 'attrct1f', 1
	196	play	0, 'attrct1a', 1
	97	play	0, 'attrct1b', 1
	98	downvol	0, 10
	0	play	0, 'attrct1d', 1
	34	upvol	0, 10
	0	play	0, 'attrct1e', 1
	129	play	0, 'attrct1f', 1
	196	loopend
	0	loopend
	65535	end
	end
  
      	playlist	62, 0, 'music: Really dumb friendship'
	0	setvol	0, 110
	0	play	0, 'dumbfrnd', 1
	433	end
	end

      	playlist	63, 0, 'music: Babality tune'
	0	setvol	0, 110
	0	play	0, 'babytune', 1
	400	end
	end

      	playlist	64, 0, 'music: End Show with gong & credits'
	0	setvol	0, 120
	0	play	0, 'endsho1', 1
	56	play	0, 'endsho2', 1
	432	setvol	0, 115
	0	play	0, 'endsho3', 1
	869	play	0, 'endsho2', 1
	330	setvol	1, 90
	0	play	1, 'gong1', 1
	132	setvol	0, 100
	0	rampupvol	0, 15, 400
	0	loopstart	0
	0	play	0, 'theend1', 1
	521	play	0, 'theend1', 1
	521	play	0, 'theend2', 1
	456	play	0, 'theend2', 1
	456	play	0, 'theend3', 1
	521	loopstart	2
	0	play	0, 'attrct1a', 1
	97	play	0, 'attrct1b', 1
	98	play	0, 'attrct1c', 1
	34	play	0, 'attrct1d', 1
	96	play	0, 'attrct1e', 1
	129	play	0, 'attrct1f', 1
	196	play	0, 'attrct1a', 1
	97	play	0, 'attrct1b', 1
	98	downvol	0, 10
	0	play	0, 'attrct1d', 1
	34	upvol	0, 10
	0	play	0, 'attrct1e', 1
	129	play	0, 'attrct1f', 1
	196	loopend
	0	loopend
	65535	end
	end

      	playlist	65, 0, 'Music: Story Attract Mode'
	0	setvol	0, 110
	0	loopstart	0
	0	play	0, 'theend1', 1
	521	play	0, 'theend1', 1
	521	play	0, 'theend2', 1
	456	play	0, 'theend2', 1
	456	play	0, 'theend3', 1
	521	loopend
	65535	end
	end

      	playlist	66, 0, 'Music: Smelly Attract Mode'
	0	setvol	0, 120
	0	loopstart	0
	0	play	0, 'attrct2a', 1
	522	play	0, 'attrct2a', 1
	522	play	0, 'attrct2b', 1
	521	loopend
	65535	end
	end

      	playlist	70, 1, 'FX: DCS logo jet flyby'
	0	setvol	1, 110
	0	play	1, 'jetfx', 1
	90	end
	end

      	playlist	71, 2, 'FX: DCS logo jet flyby'
	0	setvol	2, 110
	0	play	2, 'jetfx', 1
	90	end
	end

      	playlist	72, 3, 'FX: DCS logo jet flyby'
	0	setvol	3, 110
	0	play	3, 'jetfx', 1
	90	end
	end

      	playlist	90, 0, 'FX: Quick low drone'
	0	setvol	0, 110
	0	play	0, 'qdrone', 1
	572	end
	end

      	playlist	91, 0, 'FX: Reverse cymbal'
	0	setvol	0, 90
	0	play	0, 'revcym', 1
	321	end
	end

      	playlist	99, 0, 'music: Disco lives forever'
	0	setvol	0, 110
	0	loopstart	0
	0	play	0, 'disco', 1
	260	loopend
	65535	end
	end

; **************************************************************************
; *                                                                        *
; *                         Hits etc.                                      *
; *                                                                        *
; **************************************************************************

      	playlist	100, 1, 'big hit #1'
	0	setvol	1, 95
	0	play	1, 'bighit1', 1
	93	end
	end

      	playlist	101, 2, 'big hit #1'
	0	setvol	2, 95
	0	play	2, 'bighit1', 1
	93	end
	end

      	playlist	102, 3, 'big hit #1'
	0	setvol	3, 95
	0	play	3, 'bighit1', 1
	93	end
	end

      	playlist	103, 1, 'big hit #2'
	0	setvol	1, 95
	0	play	1, 'bighit2', 1
	91	end
	end

      	playlist	104, 2, 'big hit #2'
	0	setvol	2, 95
	0	play	2, 'bighit2', 1
	91	end
	end

      	playlist	105, 3, 'big hit #2'
	0	setvol	3, 95
	0	play	3, 'bighit2', 1
	91	end
	end

      	playlist	106, 1, 'Block a Major hit'
	0	setvol	1, 100
	0	play	1, 'gudblock', 1
	59	end
	end

      	playlist	107, 2, 'Block a Major hit'
	0	setvol	2, 100
	0	play	2, 'gudblock', 1
	59	end
	end

      	playlist	108, 3, 'Block a Major hit'
	0	setvol	3, 100
	0	play	3, 'gudblock', 1
	59	end
	end

      	playlist	109, 1, 'block #1'
	0	setvol	1, 105
	0	play	1, 'block1', 1
	38	end
	end

      	playlist	110, 2, 'block #1'
	0	setvol	2, 105
	0	play	2, 'block1', 1
	38	end
	end

      	playlist	111, 3, 'block #1'
	0	setvol	3, 105
	0	play	3, 'block1', 1
	38	end
	end

      	playlist	112, 1, 'block #2'
	0	setvol	1, 80
	0	play	1, 'gudblock', 1
	35	end
	end

      	playlist	113, 2, 'block #2'
	0	setvol	2, 80
	0	play	2, 'gudblock', 1
	35	end
	end

      	playlist	114, 3, 'block #2'
	0	setvol	3, 80
	0	play	3, 'gudblock', 1
	35	end
	end

      	playlist	115, 1, 'body hit #1'
	0	setvol	1, 80
	0	play	1, 'body1', 1
	39	end
	end

      	playlist	116, 2, 'body hit #1'
	0	setvol	2, 80
	0	play	2, 'body1', 1
	39	end
	end

      	playlist	117, 3, 'body hit #1'
	0	setvol	3, 80
	0	play	3, 'body1', 1
	39	end
	end

      	playlist	118, 1, 'body hit #2'
	0	setvol	1, 90
	0	play	1, 'body2', 1
	43	end
	end

      	playlist	119, 2, 'body hit #2'
	0	setvol	2, 90
	0	play	2, 'body2', 1
	43	end
	end

      	playlist	120, 3, 'body hit #2'
	0	setvol	3, 90
	0	play	3, 'body2', 1
	43	end
	end

      	playlist	121, 1, 'face hit #1'
	0	setvol	1, 95
	0	play	1, 'gudhit1', 1
	61	end
	end

      	playlist	122, 2, 'face hit #1'
	0	setvol	2, 95
	0	play	2, 'gudhit1', 1
	61	end
	end

      	playlist	123, 3, 'face hit #1'
	0	setvol	3, 95
	0	play	3, 'gudhit1', 1
	61	end
	end

      	playlist	124, 1, 'face hit #2'
	0	setvol	1, 95
	0	play	1, 'face2', 1
	45	end
	end

      	playlist	125, 2, 'face hit #2'
	0	setvol	2, 95
	0	play	2, 'face2', 1
	45	end
	end

      	playlist	126, 3, 'face hit #2'
	0	setvol	3, 95
	0	play	3, 'face2', 1
	45	end
	end

      	playlist	127, 1, 'Biggie Hit #3'
	0	setvol	1, 100
	0	play	1, 'bighit3', 1
	145	end
	end

      	playlist	128, 2, 'Biggie Hit #3'
	0	setvol	2, 100
	0	play	2, 'bighit3', 1
	145	end
	end

      	playlist	129, 3, 'Biggie Hit #3'
	0	setvol	3, 100
	0	play	3, 'bighit3', 1
	145	end
	end

      	playlist	130, 1, 'big whoosh #1'
	0	setvol	1, 100
	0	play	1, 'bwhoosh1', 1
	61	end
	end

      	playlist	131, 2, 'big whoosh #1'
	0	setvol	2, 100
	0	play	2, 'bwhoosh1', 1
	61	end
	end

      	playlist	132, 3, 'big whoosh #1'
	0	setvol	3, 100
	0	play	3, 'bwhoosh1', 1
	61	end
	end

      	playlist	133, 1, 'big whoosh #2'
	0	setvol	1, 95
	0	play	1, 'bwhoosh2', 1
	44	end
	end

      	playlist	134, 2, 'big whoosh #2'
	0	setvol	2, 95
	0	play	2, 'bwhoosh2', 1
	44	end
	end

      	playlist	135, 3, 'big whoosh #2'
	0	setvol	3, 95
	0	play	3, 'bwhoosh2', 1
	44	end
	end

      	playlist	136, 1, 'whoosh #1'
	0	setvol	1, 90
	0	play	1, 'whoosh1', 1
	39	end
	end

      	playlist	137, 2, 'whoosh #1'
	0	setvol	2, 90
	0	play	2, 'whoosh1', 1
	39	end
	end

      	playlist	138, 3, 'whoosh #1'
	0	setvol	3, 90
	0	play	3, 'whoosh1', 1
	39	end
	end

      	playlist	139, 1, 'whoosh #2'
	0	setvol	1, 95
	0	play	1, 'whoosh2', 1
	55	end
	end

      	playlist	140, 2, 'whoosh #2'
	0	setvol	2, 95
	0	play	2, 'whoosh2', 1
	55	end
	end

      	playlist	141, 3, 'whoosh #2'
	0	setvol	3, 95
	0	play	3, 'whoosh2', 1
	55	end
	end

      	playlist	142, 1, 'whoosh #3'
	0	setvol	1, 95
	0	play	1, 'whoosh3', 1
	48	end
	end

      	playlist	143, 2, 'whoosh #3'
	0	setvol	2, 95
	0	play	2, 'whoosh3', 1
	48	end
	end

      	playlist	144, 3, 'whoosh #3'
	0	setvol	3, 95
	0	play	3, 'whoosh3', 1
	48	end
	end

      	playlist	145, 1, 'Body hit #3'
	0	setvol	1, 100
	0	play	1, 'goodbod1', 1
	50	end
	end

      	playlist	146, 2, 'Body hit #3'
	0	setvol	2, 100
	0	play	2, 'goodbod1', 1
	50	end
	end

      	playlist	147, 3, 'Body hit #3'
	0	setvol	3, 100
	0	play	3, 'goodbod1', 1
	50	end
	end

      	playlist	148, 1, 'fall #1'
	0	setvol	1, 105
	0	play	1, 'gudfall1', 1
	51	end
	end

      	playlist	149, 2, 'fall #1'
	0	setvol	2, 105
	0	play	2, 'gudfall1', 1
	51	end
	end

      	playlist	150, 3, 'fall #1'
	0	setvol	3, 105
	0	play	3, 'gudfall1', 1
	51	end
	end

      	playlist	151, 1, 'fall #2'
	0	setvol	1, 105
	0	play	1, 'gudfall2', 1
	69	end
	end

      	playlist	152, 2, 'fall #2'
	0	setvol	2, 105
	0	play	2, 'gudfall2', 1
	69	end
	end

      	playlist	153, 3, 'fall #2'
	0	setvol	3, 105
	0	play	3, 'gudfall2', 1
	69	end
	end

      	playlist	154, 1, 'Crunch #1'
	0	setvol	1, 95
	0	play	1, 'crunch1', 1
	76	end
	end

      	playlist	155, 2, 'Crunch #1'
	0	setvol	2, 95
	0	play	2, 'crunch1', 1
	76	end
	end

      	playlist	156, 3, 'Crunch #1'
	0	setvol	3, 95
	0	play	3, 'crunch1', 1
	76	end
	end

      	playlist	157, 1, 'Crunch #2'
	0	setvol	1, 95
	0	play	1, 'crunch2', 1
	84	end
	end

      	playlist	158, 2, 'Crunch #2'
	0	setvol	2, 95
	0	play	2, 'crunch2', 1
	84	end
	end

      	playlist	159, 3, 'Crunch #2'
	0	setvol	3, 95
	0	play	3, 'crunch2', 1
	84	end
	end

      	playlist	160, 1, 'Stab #1'
	0	setvol	1, 95
	0	play	1, 'stab1', 1
	59	end
	end

      	playlist	161, 2, 'Stab #1'
	0	setvol	2, 95
	0	play	2, 'stab1', 1
	59	end
	end

      	playlist	162, 3, 'Stab #1'
	0	setvol	3, 95
	0	play	3, 'stab1', 1
	59	end
	end

      	playlist	163, 1, 'Biggie Stab #1'
	0	setvol	1, 100
	0	play	1, 'bigstab1', 1
	159	end
	end

      	playlist	164, 2, 'Biggie Stab #1'
	0	setvol	2, 100
	0	play	2, 'bigstab1', 1
	159	end
	end

      	playlist	165, 3, 'Biggie Stab #1'
	0	setvol	3, 100
	0	play	3, 'bigstab1', 1
	159	end
	end

      	playlist	166, 1, 'Biggie Stab #2'
	0	setvol	1, 100
	0	play	1, 'bigstab2', 1
	159	end
	end

      	playlist	167, 2, 'Biggie Stab #2'
	0	setvol	2, 100
	0	play	2, 'bigstab2', 1
	159	end
	end

      	playlist	168, 3, 'Biggie Stab #2'
	0	setvol	3, 100
	0	play	3, 'bigstab2', 1
	159	end
	end

      	playlist	169, 1, 'Biggie Stab #3'
	0	setvol	1, 110
	0	play	1, 'bigstab3', 1
	159	end
	end

      	playlist	170, 2, 'Biggie Stab #3'
	0	setvol	2, 110
	0	play	2, 'bigstab3', 1
	159	end
	end

      	playlist	171, 3, 'Biggie Stab #3'
	0	setvol	3, 110
	0	play	3, 'bigstab3', 1
	159	end
	end

      	playlist	172, 1, 'fall #3'
	0	setvol	1, 100
	0	play	1, 'gudfall3', 1
	159	end
	end

      	playlist	173, 2, 'fall #3'
	0	setvol	2, 100
	0	play	2, 'gudfall3', 1
	159	end
	end

      	playlist	174, 3, 'fall #3'
	0	setvol	3, 100
	0	play	3, 'gudfall3', 1
	159	end
	end

      	playlist	175, 1, 'fall #4'
	0	setvol	1, 100
	0	play	1, 'gudfall4', 1
	159	end
	end

      	playlist	176, 2, 'fall #4'
	0	setvol	2, 100
	0	play	2, 'gudfall4', 1
	159	end
	end

      	playlist	177, 3, 'fall #4'
	0	setvol	3, 100
	0	play	3, 'gudfall4', 1
	159	end
	end

      	playlist	178, 1, 'Big Fall #1'
	0	setvol	1, 100
	0	play	1, 'bigfall1', 1
	159	end
	end

      	playlist	179, 2, 'Big Fall #1'
	0	setvol	2, 100
	0	play	2, 'bigfall1', 1
	159	end
	end

      	playlist	180, 3, 'Big Fall #1'
	0	setvol	3, 100
	0	play	3, 'bigfall1', 1
	159	end
	end

      	playlist	181, 1, 'Mileena spits bones'
	0	setvol	1, 105
	0	play	1, 'milespit', 1
	77	end
	end

      	playlist	182, 2, 'Mileena spits bones'
	0	setvol	2, 105
	0	play	2, 'milespit', 1
	77	end
	end

      	playlist	183, 3, 'Mileena spits bones'
	0	setvol	3, 105
	0	play	3, 'milespit', 1
	77	end
	end

      	playlist	184, 1, 'Sub-Zero: freeze his own self'
	0	setvol	1, 110
	0	play	1, 'szautofz', 1
	202	end
	end

      	playlist	185, 2, 'Sub-Zero: freeze his own self'
	0	setvol	2, 110
	0	play	2, 'szautofz', 1
	202	end
	end

      	playlist	186, 3, 'Sub-Zero: freeze his own self'
	0	setvol	3, 110
	0	play	3, 'szautofz', 1
	202	end
	end

      	playlist	187, 1, 'coin drop'
	0	setvol	1, 100
	0	play	1, 'coindrop', 1
	101	end
	end

      	playlist	188, 2, 'coin drop'
	0	setvol	2, 100
	0	play	2, 'coindrop', 1
	101	end
	end

      	playlist	189, 3, 'coin drop'
	0	setvol	3, 100
	0	play	3, 'coindrop', 1
	101	end
	end

      	playlist	190, 1, 'Big Whoosh #3'
	0	setvol	1, 95
	0	play	1, 'bwhoosh4', 1
	48	end
	end

      	playlist	191, 2, 'Big Whoosh #3'
	0	setvol	2, 95
	0	play	2, 'bwhoosh4', 1
	48	end
	end

      	playlist	192, 3, 'Big Whoosh #3'
	0	setvol	3, 95
	0	play	3, 'bwhoosh4', 1
	48	end
	end

      	playlist	193, 1, 'Old big hit #1'
	0	setvol	1, 115
	0	downvol	0, 55
	0	play	1, 'roldbig1', 1
	30	rampupvol	0, 55, 20
	70	rampdownvol	1, 100, 8
	8	end
	end

      	playlist	194, 2, 'Old big hit #1'
	0	setvol	2, 115
	0	downvol	0, 55
	0	play	2, 'roldbig1', 1
	30	rampupvol	0, 55, 20
	70	rampdownvol	2, 100, 8
	8	end
	end

      	playlist	195, 3, 'Old big hit #1'
	0	setvol	3, 115
	0	downvol	0, 55
	0	play	3, 'roldbig1', 1
	30	rampupvol	0, 55, 20
	70	rampdownvol	3, 100, 8
	8	end
	end

      	playlist	196, 1, 'Old big hit #2'
	0	setvol	1, 115
	0	downvol	0, 55
	0	play	1, 'roldbig2', 1
	20	rampupvol	0, 55, 10
	80	rampdownvol	1, 100, 8
	8	end
	end

      	playlist	197, 2, 'Old big hit #2'
	0	setvol	2, 115
	0	downvol	0, 55
	0	play	2, 'roldbig2', 1
	20	rampupvol	0, 55, 10
	80	rampdownvol	2, 100, 8
	8	end
	end

      	playlist	198, 3, 'Old big hit #2'
	0	setvol	3, 115
	0	downvol	0, 55
	0	play	3, 'roldbig2', 1
	20	rampupvol	0, 55, 10
	80	rampdownvol	3, 100, 8
	8	end
	end

      	playlist	199, 1, 'Player''s feet landing'
	0	setvol	1, 80
	0	play 	1, 'gudfall3', 1
	5	setvol	1, 0
	5	setvol	1, 60
	0	play 	1, 'gudblock', 1
	0	rampdownvol	1, 60, 15
	15 	end
	end
	
      	playlist	200, 2, 'Player''s feet landing'
	0	setvol	2, 80
	0	play 	2, 'gudfall3', 1
	5	setvol	2, 0
	5	setvol	2, 60
	0	play 	2, 'gudblock', 1
	0	rampdownvol	2, 60, 15
	15 	end
	end
	
      	playlist	201, 3, 'Player''s feet landing'
	0	setvol	3, 80
	0	play 	3, 'gudfall3', 1
	5	setvol	3, 0
	5	setvol	3, 60
	0	play 	3, 'gudblock', 1
	0	rampdownvol	3, 60, 15
	15 	end
	end
	
      	playlist	202, 1, 'long rip'
	0	setvol	1, 110
	0	play	1, 'rip1a', 1
	21	play	1, 'rip1b', 1
	63	end
	end

      	playlist	203, 2, 'long rip'
	0	setvol	2, 110
	0	play	2, 'rip1a', 1
	21	play	2, 'rip1b', 1
	63	end
	end

      	playlist	204, 3, 'long rip'
	0	setvol	3, 110
	0	play	3, 'rip1a', 1
	21	play	3, 'rip1b', 1
	63	end
	end

      	playlist	205, 1, 'short rip'
	0	setvol	1, 110
	0	play	1, 'rip1b', 1
	63	end
	end

      	playlist	206, 2, 'short rip'
	0	setvol	2, 110
	0	play	2, 'rip1b', 1
	63	end
	end

      	playlist	207, 3, 'short rip'
	0	setvol	3, 110
	0	play	3, 'rip1b', 1
	63	end
	end

      	playlist	208, 1, 'old rip'
	0	setvol	1, 105
	0	play	1, 'oldrip', 1
	64	end
	end

      	playlist	209, 2, 'old rip'
	0	setvol	2, 105
	0	play	2, 'oldrip', 1
	64	end
	end

      	playlist	210, 3, 'old rip'
	0	setvol	3, 105
	0	play	3, 'oldrip', 1
	64	end
	end

      	playlist	211, 1, 'bite head off'
	0	setvol	1, 105
	0	play	1, 'bitehead', 1
	69	end
	end

      	playlist	212, 2, 'bite head off'
	0	setvol	2, 105
	0	play	2, 'bitehead', 1
	69	end
	end

      	playlist	213, 3, 'bite head off'
	0	setvol	3, 105
	0	play	3, 'bitehead', 1
	69	end
	end

      	playlist	214, 1, 'Blood spooge'
	0	setvol	1, 105
	0	play	1, 'spooge', 1
	123	end
	end

      	playlist	215, 2, 'Blood spooge'
	0	setvol	2, 105
	0	play	2, 'spooge', 1
	123	end
	end

      	playlist	216, 3, 'Blood spooge'
	0	setvol	3, 105
	0	play	3, 'spooge', 1
	123	end
	end

      	playlist	217, 1, 'Big whoosh #4'
	0	setvol	1, 105
	0	play	1, 'bwhoosh3', 1
	49	end
	end

      	playlist	218, 2, 'Big whoosh #4'
	0	setvol	2, 105
	0	play	2, 'bwhoosh3', 1
	49	end
	end

      	playlist	219, 3, 'Big whoosh #4'
	0	setvol	3, 105
	0	play	3, 'bwhoosh3', 1
	49	end
	end

      	playlist	220, 1, 'Raiden: Smack you against wall'
	0 	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'rsmak', 1
	20 	upvol	0, 10
	57	end
	end

      	playlist	221, 2, 'Raiden: Smack you against wall'
	0 	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'rsmak', 1
	20 	upvol	0, 10
	57	end
	end

      	playlist	222, 3, 'Raiden: Smack you against wall'
	0 	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'rsmak', 1
	20 	upvol	0, 10
	57	end
	end

      	playlist	223, 1, 'Danger sound - about to get it'
	0	setvol	1, 80
	0	play	1, 'danger', 1
	100	rampdownvol	1, 80, 20
	20	end
	end

      	playlist	224, 2, 'Danger sound - about to get it'
	0	setvol	2, 80
	0	play	2, 'danger', 1
	100	rampdownvol	2, 80, 20
	20	end
	end

      	playlist	225, 3, 'Danger sound - about to get it'
	0	setvol	3, 80
	0	play	3, 'danger', 1
	100	rampdownvol	3, 80, 20
	20	end
	end

      	playlist	226, 1, 'Vortex spark #1'
	0	setvol	1, 90
	0	play	1, 'vsprk1', 1
	73	end
	end

      	playlist	227, 2, 'Vortex spark #1'
	0	setvol	2, 90
	0	play	2, 'vsprk1', 1
	73	end
	end

      	playlist	228, 3, 'Vortex spark #1'
	0	setvol	3, 90
	0	play	3, 'vsprk1', 1
	73	end
	end

      	playlist	229, 1, 'Vortex spark #2'
	0	setvol	1, 90
	0	play	1, 'vsprk2', 1
	58	end
	end

      	playlist	230, 2, 'Vortex spark #2'
	0	setvol	2, 90
	0	play	2, 'vsprk2', 1
	58	end
	end

      	playlist	231, 3, 'Vortex spark #2'
	0	setvol	3, 90
	0	play	3, 'vsprk2', 1
	58	end
	end

      	playlist	232, 1, 'Liu Kang: end of fight warble'
	0	setvol	1, 110
	0	play	1, 'lkendf', 1
	182	end
	end

      	playlist	233, 2, 'Liu Kang: end of fight warble'
	0	setvol	2, 110
	0	play	2, 'lkendf', 1
	182	end
	end

      	playlist	234, 3, 'Liu Kang: end of fight warble'
	0	setvol	3, 110
	0	play	3, 'lkendf', 1
	182	end
	end

      	playlist	235, 1, 'Liu Kang: spinning kick'
	0	setvol	1, 103
	0	play	1, 'lkspink', 1
	240	end
	end

      	playlist	236, 2, 'Liu Kang: spinning kick'
	0	setvol	2, 103
	0	play	2, 'lkspink', 1
	240	end
	end

      	playlist	237, 3, 'Liu Kang: spinning kick'
	0	setvol	3, 103
	0	play	3, 'lkspink', 1
	240	end
	end

      	playlist	238, 1, 'Liu Kang: kick #1'
	0	setvol	1, 103
	0	play	1, 'lkspkck1', 1
	74	end
	end

      	playlist	239, 2, 'Liu Kang: kick #1'
	0	setvol	2, 103
	0	play	2, 'lkspkck1', 1
	74	end
	end

      	playlist	240, 3, 'Liu Kang: kick #1'
	0	setvol	3, 103
	0	play	3, 'lkspkck1', 1
	74	end
	end

      	playlist	241, 1, 'Liu Kang: kick #2'
	0	setvol	1, 103
	0	play	1, 'lkspkck2', 1
	133	end
	end

      	playlist	242, 2, 'Liu Kang: kick #2'
	0	setvol	2, 103
	0	play	2, 'lkspkck2', 1
	133	end
	end

      	playlist	243, 3, 'Liu Kang: kick #2'
	0	setvol	3, 103
	0	play	3, 'lkspkck2', 1
	133	end
	end

      	playlist	244, 1, 'Liu Kang: uppercut'
	0	setvol	1, 103
	0	play	1, 'lkupper', 1
	114	end
	end

      	playlist	245, 2, 'Liu Kang: uppercut'
	0	setvol	2, 103
	0	play	2, 'lkupper', 1
	114	end
	end

      	playlist	246, 3, 'Liu Kang: uppercut'
	0	setvol	3, 103
	0	play	3, 'lkupper', 1
	114	end
	end

      	playlist	247, 1, 'Liu Kang: morph into dragon'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'lkmorph', 1
	300	upvol	0, 10
	46	end
	end

      	playlist	248, 2, 'Liu Kang: morph into dragon'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'lkmorph', 1
	300	upvol	0, 10
	46	end
	end

      	playlist	249, 3, 'Liu Kang: morph into dragon'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'lkmorph', 1
	300	upvol	0, 10
	46	end
	end

      	playlist	250, 1, 'Liu Kang: dragon bites in half'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'munch', 1
	60	upvol	0, 10
	10	end
	end

      	playlist	251, 2, 'Liu Kang: dragon bites in half'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'munch', 1
	60	upvol	0, 10
	10	end
	end

      	playlist	252, 3, 'Liu Kang: dragon bites in half'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'munch', 1
	60	upvol	0, 10
	10	end
	end

      	playlist	253, 1, 'Liu Kang: unmorph from dragon'
	0	setvol	1, 0
	0	rampupvol	1, 100, 3
	0	play	1, 'lkunmrph', 1
	138	end
	end

      	playlist	254, 2, 'Liu Kang: unmorph from dragon'
	0	setvol	2, 0
	0	rampupvol	2, 100, 3
	0	play	2, 'lkunmrph', 1
	138	end
	end

      	playlist	255, 3, 'Liu Kang: unmorph from dragon'
	0	setvol	3, 0
	0	rampupvol	3, 100, 3
	0	play	3, 'lkunmrph', 1
	138	end
	end

      	playlist	256, 1, 'Jax: rip arms off'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'riparms', 1
	50	upvol	0, 10
	21	end
	end

      	playlist	257, 2, 'Jax: rip arms off'
	0	downvol	0, 10
	0	setvol	2, 105
	0	play	2, 'riparms', 1
	50	upvol	0, 10
	21	end
	end

      	playlist	258, 3, 'Jax: rip arms off'
	0	downvol	0, 10
	0	setvol	3, 105
	0	play	3, 'riparms', 1
	50	upvol	0, 10
	21	end
	end

      	playlist	259, 1, 'Sub-Z: frozen explosion'
	0	downvol	0, 30
	0	setvol	1, 115
	0	play	1, 'szshattr', 1
	100	rampupvol	0, 30, 135
	135	end
	end

      	playlist	260, 2, 'Sub-Z: frozen explosion'
	0	downvol	0, 30
	0	setvol	2, 115
	0	play	2, 'szshattr', 1
	100	rampupvol	0, 30, 135
	135	end
	end

      	playlist	261, 3, 'Sub-Z: frozen explosion'
	0	downvol	0, 30
	0	setvol	3, 115
	0	play	3, 'szshattr', 1
	100	rampupvol	0, 30, 135
	135	end
	end

      	playlist	262, 1, 'bubbles'
	0	setvol	1, 105
	0	play	1, 'bubble', 1
	102	end
	end

      	playlist	263, 2, 'bubbles'
	0	setvol	2, 105
	0	play	2, 'bubble', 1
	102	end
	end

      	playlist	264, 3, 'bubbles'
	0	setvol	3, 105
	0	play	3, 'bubble', 1
	102	end
	end

      	playlist	265, 1, 'splash'
	0	setvol	1, 105
	0	play	1, 'splash', 1
	286	end
	end

      	playlist	266, 2, 'splash'
	0	setvol	2, 105
	0	play	2, 'splash', 1
	286	end
	end

      	playlist	267, 3, 'splash'
	0	setvol	3, 105
	0	play	3, 'splash', 1
	286	end
	end

      	playlist	268, 1, 'acid sizzle'
	0	setvol	1, 105
	0	play	1, 'acid', 1
	365	end
	end

      	playlist	269, 2, 'acid sizzle'
	0	setvol	2, 105
	0	play	2, 'acid', 1
	365	end
	end

      	playlist	270, 3, 'acid sizzle'
	0	setvol	3, 105
	0	play	3, 'acid', 1
	365	end
	end

      	playlist	271, 1, 'Scorpion: take off mask'
	0	setvol	1, 103
	0	play	1, 'mask', 1
	334	end
	end

      	playlist	272, 2, 'Scorpion: take off mask'
	0	setvol	2, 103
	0	play	2, 'mask', 1
	334	end
	end

      	playlist	273, 3, 'Scorpion: take off mask'
	0	setvol	3, 103
	0	play	3, 'mask', 1
	334	end
	end

      	playlist	274, 1, 'Scorpion: throw flame'
	0	downvol	0, 10
	0	setvol	1, 105
	0	play	1, 'flamthro', 1
	80	upvol	0, 10
	28	end
	end

      	playlist	275, 2, 'Scorpion: throw flame'
	0	downvol	0, 10
	0	setvol	2, 105
	0	play	2, 'flamthro', 1
	80	upvol	0, 10
	28	end
	end

      	playlist	276, 3, 'Scorpion: throw flame'
	0	downvol	0, 10
	0	setvol	3, 105
	0	play	3, 'flamthro', 1
	80	upvol	0, 10
	28	end
	end

      	playlist	277, 1, 'Scorpion: ignite and burn'
	0	downvol	0, 20
	0	setvol	1, 100
	0	play	1, 'ignite', 1
	387	upvol	0, 20
	0	end
	end

      	playlist	278, 2, 'Scorpion: ignite and burn'
	0	downvol	0, 20
	0	setvol	2, 100
	0	play	2, 'ignite', 1
	387	upvol	0, 20
	0	end
	end

      	playlist	279, 3, 'Scorpion: ignite and burn'
	0	downvol	0, 20
	0	setvol	3, 100
	0	play	3, 'ignite', 1
	387	upvol	0, 20
	0	end
	end

      	playlist	280, 1, 'Reptile and other''s magical poof'
	0	setvol	1, 115
	0	downvol	0, 20
	0	play	1, 'reptpoof', 1
	20	upvol	0, 20
	130	end
	end

      	playlist	281, 2, 'Reptile and other''s magical poof'
	0	setvol	2, 115
	0	downvol	0, 20
	0	play	2, 'reptpoof', 1
	20	upvol	0, 20
	130	end
	end

      	playlist	282, 3, 'Reptile and other''s magical poof'
	0	setvol	3, 115
	0	downvol	0, 20
	0	play	3, 'reptpoof', 1
	20	upvol	0, 20
	130	end
	end

      	playlist	283, 1, 'Kung Lao: victim peels apart'
	0	setvol	1, 115
	0	play	1, 'peel1', 1
	155	end
	end

      	playlist	284, 2, 'Kung Lao: victim peels apart'
	0	setvol	2, 115
	0	play	2, 'peel1', 1
	155	end
	end

      	playlist	285, 3, 'Kung Lao: victim peels apart'
	0	setvol	3, 115
	0	play	3, 'peel1', 1
	155	end
	end

      	playlist	286, 1, 'Raiden: electrocute big time'
	0	downvol	0, 15
	0	setvol	1, 110
	0	play	1, 'raidkill', 1
	142	upvol	0, 15
	0	end
	end

      	playlist	287, 2, 'Raiden: electrocute big time'
	0	downvol	0, 15
	0	setvol	2, 110
	0	play	2, 'raidkill', 1
	142	upvol	0, 15
	0	end
	end

      	playlist	288, 3, 'Raiden: electrocute big time'
	0	downvol	0, 15
	0	setvol	3, 110
	0	play	3, 'raidkill', 1
	142	upvol	0, 15
	0	end
	end

      	playlist	289, 1, 'Major crowd cheer'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'crowd1', 1
	250	rampdownvol	1, 105, 147
	47	rampupvol	0, 10, 100
	100	end
	end

      	playlist	290, 2, 'Major crowd cheer'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'crowd1', 1
	250	rampdownvol	2, 105, 147
	47	rampupvol	0, 10, 100
	100	end
	end

      	playlist	291, 3, 'Major crowd cheer'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'crowd1', 1
	250	rampdownvol	3, 105, 147
	47	rampupvol	0, 10, 100
	100	end
	end

      	playlist	292, 1, 'Mileena sucks'
	0	setvol	1, 105
	0	play	1, 'milesuck', 1
	204	end
	end

      	playlist	293, 2, 'Mileena sucks'
	0	setvol	2, 105
	0	play	2, 'milesuck', 1
	204	end
	end

      	playlist	294, 3, 'Mileena sucks'
	0	setvol	3, 105
	0	play	3, 'milesuck', 1
	204	end
	end

      	playlist	295, 1, 'Raiden wins effect'
	0	downvol	0, 30
	0	setvol	1, 110
	0	play	1, 'raidwin1', 1
	196	play	1, 'raidwin2', 1
	0	rampupvol	0, 30, 53
	53	end
	end

      	playlist	296, 2, 'Raiden wins effect'
	0	downvol	0, 30
	0	setvol	2, 110
	0	play	2, 'raidwin1', 1
	196	play	2, 'raidwin2', 1
	0	rampupvol	0, 30, 53
	53	end
	end

      	playlist	297, 3, 'Raiden wins effect'
	0	downvol	0, 30
	0	setvol	3, 110
	0	play	3, 'raidwin1', 1
	196	play	3, 'raidwin2', 1
	0	rampupvol	0, 30, 53
	53	end
	end

; **************************************************************************
; *                                                                        *
; *                         Player Effects                                 *
; *                                                                        *
; **************************************************************************

      	playlist	300, 1, 'Cage: Shadow kick'
	0	setvol	1, 105
	0	play	1, 'cagekck1', 1
	25	play	1, 'cagekck2', 1
	70	rampdownvol	1, 100, 10
	10	end
	end

      	playlist	301, 2, 'Cage: Shadow kick'
	0	setvol	2, 105
	0	play	2, 'cagekck1', 1
	25	play	2, 'cagekck2', 1
	70	rampdownvol	2, 100, 10
	10	end
	end

      	playlist	302, 3, 'Cage: Shadow kick'
	0	setvol	3, 105
	0	play	3, 'cagekck1', 1
	25	play	3, 'cagekck2', 1
	70	rampdownvol	3, 100, 10
	10	end
	end

      	playlist	303, 1, 'Sword Guy: Swords eject from arms'
	0	setvol	1, 90
	0	play	1, 'knifejec', 1
	95	end
	end

      	playlist	304, 2, 'Sword Guy: Swords eject from arms'
	0	setvol	2, 90
	0	play	2, 'knifejec', 1
	95	end
	end

      	playlist	305, 3, 'Sword Guy: Swords eject from arms'
	0	setvol	3, 90
	0	play	3, 'knifejec', 1
	95	end
	end

      	playlist	306, 1, 'Sword Guy: Plunges the swords in...'
	0	setvol	1, 95
	0	play	1, 'knifplng', 1
	94	end
	end

      	playlist	307, 2, 'Sword Guy: Plunges the swords in...'
	0	setvol	2, 95
	0	play	2, 'knifplng', 1
	94	end
	end

      	playlist	308, 3, 'Sword Guy: Plunges the swords in...'
	0	setvol	3, 95
	0	play	3, 'knifplng', 1
	94	end
	end

      	playlist	309, 1, 'Kitana: throw fan'
	0	setvol	1, 95
	0	loopstart	4
	0	play	1, 'n1thrfan', 1
	22	downvol	1, 4
	0	loopend
	0	loopstart	4
	0	play	1, 'n1thrfan', 1
	20	downvol	1, 10
	0	loopend
	0	end
	end

      	playlist	310, 2, 'Kitana: throw fan'
	0	setvol	2, 95
	0	loopstart	4
	0	play	2, 'n1thrfan', 1
	22	downvol	2, 4
	0	loopend
	0	loopstart	4
	0	play	2, 'n1thrfan', 1
	20	downvol	2, 10
	0	loopend
	0	end
	end

      	playlist	311, 3, 'Kitana: throw fan'
	0	setvol	3, 95
	0	loopstart	4
	0	play	3, 'n1thrfan', 1
	22	downvol	3, 4
	0	loopend
	0	loopstart	4
	0	play	3, 'n1thrfan', 1
	20	downvol	3, 10
	0	loopend
	0	end
	end

      	playlist	312, 1, 'Kitana: fan hits'
	0	setvol	1, 100
	0	play	1, 'nfanhit', 1
	246	end
	end

      	playlist	313, 2, 'Kitana: fan hits'
	0	setvol	2, 100
	0	play	2, 'nfanhit', 1
	246	end
	end

      	playlist	314, 3, 'Kitana: fan hits'
	0	setvol	3, 100
	0	play	3, 'nfanhit', 1
	246	end
	end

      	playlist	315, 1, 'Kitana: fan blocked'
	0	setvol	1, 90
	0	play	1, 'fanhit', 1
	0	rampdownvol	1, 90, 50
	50	end
	end

      	playlist	316, 2, 'Kitana: fan blocked'
	0	setvol	2, 90
	0	play	2, 'fanhit', 1
	0	rampdownvol	2, 90, 50
	50	end
	end

      	playlist	317, 3, 'Kitana: fan blocked'
	0	setvol	3, 90
	0	play	3, 'fanhit', 1
	0	rampdownvol	3, 90, 50
	50	end
	end

      	playlist	318, 1, 'Cage: throw snot up'
	0	setvol	1, 95
	0	play	1, 'snotup', 1
	158	end
	end

      	playlist	319, 2, 'Cage: throw snot up'
	0	setvol	2, 95
	0	play	2, 'snotup', 1
	158	end
	end

      	playlist	320, 3, 'Cage: throw snot up'
	0	setvol	3, 95
	0	play	3, 'snotup', 1
	158	end
	end

      	playlist	321, 1, 'Cage: snot hits'
	0	downvol	0, 20
	0	setvol	1, 95
	0	play	1, 'snothit', 1
	60	rampupvol	0, 20, 21
	21	end
	end

      	playlist	322, 2, 'Cage: snot hits'
	0	downvol	0, 20
	0	setvol	2, 95
	0	play	2, 'snothit', 1
	60	rampupvol	0, 20, 21
	21	end
	end

      	playlist	323, 3, 'Cage: snot hits'
	0	downvol	0, 20
	0	setvol	3, 95
	0	play	3, 'snothit', 1
	60	rampupvol	0, 20, 21
	21	end
	end

      	playlist	324, 1, 'Cage: snot blocked'
	0	setvol	1, 85
	0	play	1, 'snothit', 1
	0	rampdownvol	1, 110, 70
	70	end
	end

      	playlist	325, 2, 'Cage: snot blocked'
	0	setvol	2, 85
	0	play	2, 'snothit', 1
	0	rampdownvol	2, 110, 70
	70	end
	end

      	playlist	326, 3, 'Cage: snot blocked'
	0	setvol	3, 85
	0	play	3, 'snothit', 1
	0	rampdownvol	3, 110, 70
	70	end
	end

      	playlist	327, 1, 'Mileena: tsais throw'
	0	setvol	1, 85
	0	play	1, 'throtsai', 1
	152	end
	end

      	playlist	328, 2, 'Mileena: tsais throw'
	0	setvol	2, 85
	0	play	2, 'throtsai', 1
	152	end
	end

      	playlist	329, 3, 'Mileena: tsais throw'
	0	setvol	3, 85
	0	play	3, 'throtsai', 1
	152	end
	end

      	playlist	330, 1, 'Mileena: tsais hits'
	0	downvol	0, 20
	0	setvol	1, 105
	0	play	1, 'bigstab1', 1
	20	rampupvol	0, 20, 29
	139	end
	end

      	playlist	331, 2, 'Mileena: tsais hits'
	0	downvol	0, 20
	0	setvol	2, 105
	0	play	2, 'bigstab1', 1
	20	rampupvol	0, 20, 29
	139	end
	end

      	playlist	332, 3, 'Mileena: tsais hits'
	0	downvol	0, 20
	0	setvol	3, 105
	0	play	3, 'bigstab1', 1
	20	rampupvol	0, 20, 29
	139	end
	end

      	playlist	333, 1, 'Mileena: tsais blocked'
	0	setvol	1, 80
	0	play	1, 'crunch1', 1
	0	rampdownvol	1, 80, 70
	70	end
	end

      	playlist	334, 2, 'Mileena: tsais blocked'
	0	setvol	2, 80
	0	play	2, 'crunch1', 1
	0	rampdownvol	2, 80, 70
	70	end
	end

      	playlist	335, 3, 'Mileena: tsais blocked'
	0	setvol	3, 80
	0	play	3, 'crunch1', 1
	0	rampdownvol	3, 80, 70
	70	end
	end

      	playlist	336, 1, 'Reptile: spit stuff'
	0	setvol	1, 90
	0	play	1, 'reptspit', 1
	220	end
	end

      	playlist	337, 2, 'Reptile: spit stuff'
	0	setvol	2, 90
	0	play	2, 'reptspit', 1
	220	end
	end

      	playlist	338, 3, 'Reptile: spit stuff'
	0	setvol	3, 90
	0	play	3, 'reptspit', 1
	220	end
	end

      	playlist	339, 1, 'Reptile: spit hits'
	0	downvol	0, 20
	0	setvol	1, 105
	0	play	1, 'bigblock', 1
	10	rampupvol	0, 20, 20
	60	rampdownvol	1, 105, 20
	20	end
	end

      	playlist	340, 2, 'Reptile: spit hits'
	0	downvol	0, 20
	0	setvol	2, 105
	0	play	2, 'bigblock', 1
	10	rampupvol	0, 20, 20
	60	rampdownvol	2, 105, 20
	20	end
	end

      	playlist	341, 3, 'Reptile: spit hits'
	0	downvol	0, 20
	0	setvol	3, 105
	0	play	3, 'bigblock', 1
	10	rampupvol	0, 20, 20
	60	rampdownvol	3, 105, 20
	20	end
	end

      	playlist	342, 1, 'Reptile: spit blocked'
	0	setvol	1, 85
	0	play	1, 'bigblock', 1
	0	rampdownvol	1, 75, 50
	50	end
	end

      	playlist	343, 2, 'Reptile: spit blocked'
	0	setvol	2, 85
	0	play	2, 'bigblock', 1
	0	rampdownvol	2, 75, 50
	50	end
	end

      	playlist	344, 3, 'Reptile: spit blocked'
	0	setvol	3, 85
	0	play	3, 'bigblock', 1
	0	rampdownvol	3, 75, 50
	50	end
	end

      	playlist	345, 1, 'Scorpion: rope throw'
	0	setvol	1, 95
	0	play	1, 'scorthr1', 1
	228	end
	end

      	playlist	346, 2, 'Scorpion: rope throw'
	0	setvol	2, 95
	0	play	2, 'scorthr1', 1
	228	end
	end

      	playlist	347, 3, 'Scorpion: rope throw'
	0	setvol	3, 95
	0	play	3, 'scorthr1', 1
	228	end
	end

      	playlist	348, 1, 'Scorpion: rope hits'
	0	downvol	0, 20
	0	setvol	1, 100
	0	play	1, 'bigstab2', 1
	20	rampupvol	0, 20, 29
	139	end
	end

      	playlist	349, 2, 'Scorpion: rope hits'
	0	downvol	0, 20
	0	setvol	2, 100
	0	play	2, 'bigstab2', 1
	20	rampupvol	0, 20, 29
	139	end
	end

      	playlist	350, 3, 'Scorpion: rope hits'
	0	downvol	0, 20
	0	setvol	3, 100
	0	play	3, 'bigstab2', 1
	20	rampupvol	0, 20, 29
	139	end
	end

      	playlist	351, 1, 'Scorpion: rope blocked'
	0	setvol	1, 85
	0	play	1, 'stab1', 1
	0	rampdownvol	1, 85, 50
	50	end
	end

      	playlist	352, 2, 'Scorpion: rope blocked'
	0	setvol	2, 85
	0	play	2, 'stab1', 1
	0	rampdownvol	2, 85, 50
	50	end
	end

      	playlist	353, 3, 'Scorpion: rope blocked'
	0	setvol	3, 85
	0	play	3, 'stab1', 1
	0	rampdownvol	3, 85, 50
	50	end
	end

      	playlist	354, 1, 'HatHead: throw hat'
	0	setvol	1, 80
	0	play	1, 'hhsaw', 1
	152	end
	end

      	playlist	355, 2, 'HatHead: throw hat'
	0	setvol	2, 80
	0	play	2, 'hhsaw', 1
	152	end
	end

      	playlist	356, 3, 'HatHead: throw hat'
	0	setvol	3, 80
	0	play	3, 'hhsaw', 1
	152	end
	end

      	playlist	357, 1, 'HatHead: hat hits'
	0	setvol	1, 100
	0	play	1, 'hhsawhit', 1
	82	end
	end

      	playlist	358, 2, 'HatHead: hat hits'
	0	setvol	2, 100
	0	play	2, 'hhsawhit', 1
	82	end
	end

      	playlist	359, 3, 'HatHead: hat hits'
	0	setvol	3, 100
	0	play	3, 'hhsawhit', 1
	82	end
	end

      	playlist	360, 1, 'HatHead: hat blocked'
	0	setvol	1, 85
	0	play	1, 'hhsawblk', 1
	30	rampupvol	1, 40, 60
	60	end
	end

      	playlist	361, 2, 'HatHead: hat blocked'
	0	setvol	2, 85
	0	play	2, 'hhsawblk', 1
	30	rampupvol	2, 40, 60
	60	end
	end

      	playlist	362, 3, 'HatHead: hat blocked'
	0	setvol	3, 85
	0	play	3, 'hhsawblk', 1
	30	rampupvol	3, 40, 60
	60	end
	end

      	playlist	366, 1, 'Edward: sword scrape'
	0	setvol	1, 90
	0	play	1, 'swrdscrp', 1
	70	end
	end

      	playlist	367, 2, 'Edward: sword scrape'
	0	setvol	2, 90
	0	play	2, 'swrdscrp', 1
	70	end
	end

      	playlist	368, 3, 'Edward: sword scrape'
	0	setvol	3, 90
	0	play	3, 'swrdscrp', 1
	70	end
	end

      	playlist	369, 1, 'Raiden: Arcing #1'
	0	setvol	1, 90
	0	play	1, 'arc1', 1
	15	play	1, 'arc2', 1
	27	play	1, 'arc3', 1
	66	end
	end

      	playlist	370, 2, 'Raiden: Arcing #1'
	0	setvol	2, 90
	0	play	2, 'arc1', 1
	15	play	2, 'arc2', 1
	27	play	2, 'arc3', 1
	66	end
	end

      	playlist	371, 3, 'Raiden: Arcing #1'
	0	setvol	3, 90
	0	play	3, 'arc1', 1
	15	play	3, 'arc2', 1
	27	play	3, 'arc3', 1
	66	end
	end

      	playlist	372, 1, 'Raiden: Arcing #2'
	0	setvol	1, 90
	0	play	1, 'arc2', 1
	27	play	1, 'arc3', 1
	66	end
	end

      	playlist	373, 2, 'Raiden: Arcing #2'
	0	setvol	2, 90
	0	play	2, 'arc2', 1
	27	play	2, 'arc3', 1
	66	end
	end

      	playlist	374, 3, 'Raiden: Arcing #2'
	0	setvol	3, 90
	0	play	3, 'arc2', 1
	27	play	3, 'arc3', 1
	66	end
	end

      	playlist	375, 1, 'Raiden: Arcing #3'
	0	setvol	1, 85
	0	play	1, 'arc3', 1
	66	end
	end

      	playlist	376, 2, 'Raiden: Arcing #3'
	0	setvol	2, 85
	0	play	2, 'arc3', 1
	66	end
	end

      	playlist	377, 3, 'Raiden: Arcing #3'
	0	setvol	3, 85
	0	play	3, 'arc3', 1
	66	end
	end

      	playlist	378, 1, 'Raiden: Throw Sparks'
	0	setvol	1, 75
	0	play	1, 'sprkthro', 1
	150	rampupvol	1, 10, 100
	100	rampdownvol	1, 80, 3
	3	end
	end

      	playlist	379, 2, 'Raiden: Throw Sparks'
	0	setvol	2, 75
	0	play	2, 'sprkthro', 1
	150	rampupvol	2, 10, 100
	100	rampdownvol	2, 80, 3
	3	end
	end

      	playlist	380, 3, 'Raiden: Throw Sparks'
	0	setvol	3, 75
	0	play	3, 'sprkthro', 1
	150	rampupvol	3, 10, 100
	100	rampdownvol	3, 80, 3
	3	end
	end

      	playlist	381, 1, 'Raiden: Spark hits'
	0	downvol	0, 20
	0	setvol	1, 95
	0	play	1, 'rsprkstr', 1
	30	play	1, 'rspark1', 1
	60	play	1, 'rsprkend', 1
	0	rampupvol	0, 20, 20
	40	end
	end

      	playlist	382, 2, 'Raiden: Spark hits'
	0	downvol	0, 20
	0	setvol	2, 95
	0	play	2, 'rsprkstr', 1
	30	play	2, 'rspark1', 1
	60	play	2, 'rsprkend', 1
	0	rampupvol	0, 20, 20
	40	end
	end

      	playlist	383, 3, 'Raiden: Spark hits'
	0	downvol	0, 20
	0	setvol	3, 95
	0	play	3, 'rsprkstr', 1
	30	play	3, 'rspark1', 1
	60	play	3, 'rsprkend', 1
	0	rampupvol	0, 20, 20
	40	end
	end

      	playlist	384, 1, 'Raiden: Spark blocked'
	0	setvol	1, 80
	0	play	1, 'rsprkstr', 1
	30	play	1, 'rsprkend', 1
	40	end
	end

      	playlist	385, 2, 'Raiden: Spark blocked'
	0	setvol	2, 80
	0	play	2, 'rsprkstr', 1
	30	play	2, 'rsprkend', 1
	40	end
	end

      	playlist	386, 3, 'Raiden: Spark blocked'
	0	setvol	3, 80
	0	play	3, 'rsprkstr', 1
	30	play	3, 'rsprkend', 1
	40	end
	end

      	playlist	387, 1, 'Raiden: Hold and Fry'
	0	downvol	0, 20
	0	setvol	1, 95
	0	play	1, 'rspark1', 1
	65	play	1, 'rspark1', 1
	55	play	1, 'rspark1', 1
	50	play	1, 'rsprkend', 1
	0	rampupvol	0, 20, 20
	40	end
	end

      	playlist	388, 2, 'Raiden: Hold and Fry'
	0	downvol	0, 20
	0	setvol	2, 95
	0	play	2, 'rspark1', 1
	65	play	2, 'rspark1', 1
	55	play	2, 'rspark1', 1
	50	play	2, 'rsprkend', 1
	0	rampupvol	0, 20, 20
	40	end
	end

      	playlist	389, 3, 'Raiden: Hold and Fry'
	0	downvol	0, 20
	0	setvol	3, 95
	0	play	3, 'rspark1', 1
	65	play	3, 'rspark1', 1
	55	play	3, 'rspark1', 1
	50	play	3, 'rsprkend', 1
	0	rampupvol	0, 20, 20
	40	end
	end

      	playlist	390, 1, 'Kitana: Sonic Girl Trap'
	0	downvol	0, 15
	0	setvol	1, 100
	0	loopstart	2
	0	play	1, 'girltrap', 1
	170	loopend
	0	upvol	0, 15
	0	end
	end

      	playlist	391, 2, 'Kitana: Sonic Girl Trap'
	0	downvol	0, 15
	0	setvol	2, 100
	0	loopstart	2
	0	play	2, 'girltrap', 1
	170	loopend
	0	upvol	0, 15
	0	end
	end

      	playlist	392, 3, 'Kitana: Sonic Girl Trap'
	0	downvol	0, 15
	0	setvol	3, 100
	0	loopstart	2
	0	play	3, 'girltrap', 1
	170	loopend
	0	upvol	0, 15
	0	end
	end

      	playlist	393, 1, 'Reptile: hocking a loogie'
	0	setvol	1, 90
	0	play	1, 'repthock', 1
	48	end
	end

      	playlist	394, 2, 'Reptile: hocking a loogie'
	0	setvol	2, 90
	0	play	2, 'repthock', 1
	48	end
	end

      	playlist	395, 3, 'Reptile: hocking a loogie'
	0	setvol	3, 90
	0	play	3, 'repthock', 1
	48	end
	end

      	playlist	396, 1, 'Reptile: hocking and spitting'
	0	setvol	1, 90
	0	play	1, 'repthock', 1
	40	play	1, 'reptspit', 1
	220	end
	end

      	playlist	397, 2, 'Reptile: hocking and spitting'
	0	setvol	2, 90
	0	play	2, 'repthock', 1
	40	play	2, 'reptspit', 1
	220	end
	end

      	playlist	398, 3, 'Reptile: hocking and spitting'
	0	setvol	3, 90
	0	play	3, 'repthock', 1
	40	play	3, 'reptspit', 1
	220	end
	end

      	playlist	399, 1, 'Kitana: Kissy sound'
	0	setvol	1, 100
	0	play	1, 'kiss', 1
	57	end
	end

      	playlist	400, 2, 'Kitana: Kissy sound'
	0	setvol	2, 100
	0	play	2, 'kiss', 1
	57	end
	end

      	playlist	401, 3, 'Kitana: Kissy sound'
	0	setvol	3, 100
	0	play	3, 'kiss', 1
	57	end
	end

      	playlist	402, 1, 'Liu Kang: Throw Fireball'
	0	setvol	1, 100
	0	play	1, 'lkfball', 1
	152	end
	end

      	playlist	403, 2, 'Liu Kang: Throw Fireball'
	0	setvol	2, 100
	0	play	2, 'lkfball', 1
	152	end
	end

      	playlist	404, 3, 'Liu Kang: Throw Fireball'
	0	setvol	3, 100
	0	play	3, 'lkfball', 1
	152	end
	end

      	playlist	405, 1, 'Liu Kang: Fireball hits'
	0	downvol	0, 20
	0	setvol	1, 100
	0	play	1, 'fballhit', 1	
	60	rampupvol	1, 15, 60
	15	rampupvol	0, 20, 15
	65	end
	end

      	playlist	406, 2, 'Liu Kang: Fireball hits'
	0	downvol	0, 20
	0	setvol	2, 100
	0	play	2, 'fballhit', 1	
	60	rampupvol	2, 15, 60
	15	rampupvol	0, 20, 15
	65	end
	end

      	playlist	407, 3, 'Liu Kang: Fireball hits'
	0	downvol	0, 20
	0	setvol	3, 100
	0	play	3, 'fballhit', 1	
	60	rampupvol	3, 15, 60
	15	rampupvol	0, 20, 15
	65	end
	end

      	playlist	408, 1, 'Liu Kang: Fireball blocked'
	0	setvol	1, 90
	0	play	1, 'fballhit', 1
	0	rampdownvol	1, 70, 60
	60	end
	end

      	playlist	409, 2, 'Liu Kang: Fireball blocked'
	0	setvol	2, 90
	0	play	2, 'fballhit', 1
	0	rampdownvol	2, 70, 60
	60	end
	end

      	playlist	410, 3, 'Liu Kang: Fireball blocked'
	0	setvol	3, 90
	0	play	3, 'fballhit', 1
	0	rampdownvol	3, 70, 60
	60	end
	end

      	playlist	411, 1, 'Liu Kang: Flying Kick'
	0	setvol	1, 0
	0	rampupvol	1, 70, 5
	0	play	1, 'lkflykck', 1
	158	end
	end

      	playlist	412, 2, 'Liu Kang: Flying Kick'
	0	setvol	2, 0
	0	rampupvol	2, 70, 5
	0	play	2, 'lkflykck', 1
	158	end
	end

      	playlist	413, 3, 'Liu Kang: Flying Kick'
	0	setvol	3, 0
	0	rampupvol	3, 70, 5
	0	play	3, 'lkflykck', 1
	158	end
	end

      	playlist	414, 1, 'Raiden: Teleport'
	0	setvol	1, 90
	0	play	1, 'rtele', 1
	97	end
	end

      	playlist	415, 2, 'Raiden: Teleport'
	0	setvol	2, 90
	0	play	2, 'rtele', 1
	97	end
	end

      	playlist	416, 3, 'Raiden: Teleport'
	0	setvol	3, 90
	0	play	3, 'rtele', 1
	97	end
	end

      	playlist	417, 1, 'Raiden: Get Up'
	0	setvol	1, 90
	0	play	1, 'rgetup', 1
	132	end
	end

      	playlist	418, 2, 'Raiden: Get Up'
	0	setvol	2, 90
	0	play	2, 'rgetup', 1
	132	end
	end

      	playlist	419, 3, 'Raiden: Get Up'
	0	setvol	3, 90
	0	play	3, 'rgetup', 1
	132	end
	end

      	playlist	420, 1, 'Shang Tsung: Throw Skulls'
	0	setvol	1, 90
	0	play	1, 'stskulls', 1
	195	end
	end

      	playlist	421, 2, 'Shang Tsung: Throw Skulls'
	0	setvol	2, 90
	0	play	2, 'stskulls', 1
	195	end
	end

      	playlist	422, 3, 'Shang Tsung: Throw Skulls'
	0	setvol	3, 90
	0	play	3, 'stskulls', 1
	195	end
	end

      	playlist	423, 1, 'Shang Tsung: Skulls hit'
	0	downvol	0, 20
	0	setvol	1, 100
	0	play	1, 'fballhit', 1	
	60	rampupvol	1, 15, 60
	15	rampupvol	0, 20, 15
	65	end
	end

      	playlist	424, 2, 'Shang Tsung: Skulls hit'
	0	downvol	0, 20
	0	setvol	2, 100
	0	play	2, 'fballhit', 1	
	60	rampupvol	2, 15, 60
	15	rampupvol	0, 20, 15
	65	end
	end

      	playlist	425, 3, 'Shang Tsung: Skulls hit'
	0	downvol	0, 20
	0	setvol	3, 100
	0	play	3, 'fballhit', 1	
	60	rampupvol	3, 15, 60
	15	rampupvol	0, 20, 15
	65	end
	end

      	playlist	426, 1, 'Shang Tsung: Skulls blocked'
	0	setvol	1, 90
	0	play	1, 'fballhit', 1
	0	rampdownvol	1, 70, 60
	60	end
	end

      	playlist	427, 2, 'Shang Tsung: Skulls blocked'
	0	setvol	2, 90
	0	play	2, 'fballhit', 1
	0	rampdownvol	2, 70, 60
	60	end
	end

      	playlist	428, 3, 'Shang Tsung: Skulls blocked'
	0	setvol	3, 90
	0	play	3, 'fballhit', 1
	0	rampdownvol	3, 70, 60
	60	end
	end

      	playlist	429, 1, 'Sub-Zero: Slide Trip'
	0	setvol	1, 0
	0	rampupvol	1, 90, 10
	0	play	1, 'szslide', 1
	30	rampdownvol	1, 90, 80
	80	end
	end

      	playlist	430, 2, 'Sub-Zero: Slide Trip'
	0	setvol	2, 0
	0	rampupvol	2, 90, 10
	0	play	2, 'szslide', 1
	30	rampdownvol	2, 90, 80
	80	end
	end

      	playlist	431, 3, 'Sub-Zero: Slide Trip'
	0	setvol	3, 0
	0	rampupvol	3, 90, 10
	0	play	3, 'szslide', 1
	30	rampdownvol	3, 90, 80
	80	end
	end

      	playlist	432, 1, 'Cage: Shadow Elbow'
	0	setvol	1, 10
	0	play	1, 'cagekck2', 1
	0	rampupvol	1, 90, 5
	60	rampdownvol	1, 90, 10
	10	end
	end

      	playlist	433, 2, 'Cage: Shadow Elbow'
	0	setvol	2, 10
	0	play	2, 'cagekck2', 1
	0	rampupvol	2, 90, 5
	60	rampdownvol	2, 90, 10
	10	end
	end

      	playlist	434, 3, 'Cage: Shadow Elbow'
	0	setvol	3, 10
	0	play	3, 'cagekck2', 1
	0	rampupvol	3, 90, 5
	60	rampdownvol	3, 90, 10
	10	end
	end

      	playlist	435, 1, 'Reptile: slow moving orb #1 - 4 times'
	0	setvol	1, 80
	0	loopstart	4
	0	play	1, 'reporb4l', 1
	15	loopend
	0	end
	end

      	playlist	436, 2, 'Reptile: slow moving orb #1 - 4 times'
	0	setvol	2, 80
	0	loopstart	4
	0	play	2, 'reporb4l', 1
	15	loopend
	0	end
	end

      	playlist	437, 3, 'Reptile: slow moving orb #1 - 4 times'
	0	setvol	3, 80
	0	loopstart	4
	0	play	3, 'reporb4l', 1
	15	loopend
	0	end
	end

      	playlist	438, 1, 'Baraka: little stab #1'
	0	setvol	1, 95
	0	play	1, 'lilstab1', 1
	64	end
	end

      	playlist	439, 2, 'Baraka: little stab #1'
	0	setvol	2, 95
	0	play	2, 'lilstab1', 1
	64	end
	end

      	playlist	440, 3, 'Baraka: little stab #1'
	0	setvol	3, 95
	0	play	3, 'lilstab1', 1
	64	end
	end

      	playlist	441, 1, 'Baraka: little stab #2'
	0	setvol	1, 95
	0	play	1, 'lilstab2', 1
	54	end
	end

      	playlist	442, 2, 'Baraka: little stab #2'
	0	setvol	2, 95
	0	play	2, 'lilstab2', 1
	54	end
	end

      	playlist	443, 3, 'Baraka: little stab #2'
	0	setvol	3, 95
	0	play	3, 'lilstab2', 1
	54	end
	end

      	playlist	444, 1, 'Baraka: little stab #3'
	0	setvol	1, 95
	0	play	1, 'lilstab3', 1
	60	end
	end

      	playlist	445, 2, 'Baraka: little stab #3'
	0	setvol	2, 95
	0	play	2, 'lilstab3', 1
	60	end
	end

      	playlist	446, 3, 'Baraka: little stab #3'
	0	setvol	3, 95
	0	play	3, 'lilstab3', 1
	60	end
	end

      	playlist	447, 1, 'Baraka: many stabs'
	0	setvol	1, 95
	0	play	1, 'lilstab1', 1
	14	play	1, 'lilstab2', 1
	14	play	1, 'lilstab3', 1
	14	play	1, 'lilstab1', 1
	14	play	1, 'lilstab2', 1
	14	play	1, 'lilstab1', 1
	14	play	1, 'lilstab3', 1
	14	play	1, 'lilstab1', 1
	14	play	1, 'lilstab3', 1
	14	play	1, 'lilstab2', 1
	14	play	1, 'lilstab3', 1
	14	play	1, 'lilstab1', 1
	14	play	1, 'lilstab2', 1
	14	play	1, 'lilstab3', 1
	60	end
	end

      	playlist	448, 1, 'Baraka: many whooshes'
	0	setvol	1, 95
	0	play	1, 'whoosh2', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh2', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh2', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh2', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh2', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh2', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh2', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh2', 1
	12	play	1, 'bwhoosh2', 1
	61	end
	end

      	playlist	449, 1, 'Baraka: many whooshes'
	0	setvol	1, 95
	0	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh1', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh1', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh1', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh1', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh1', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh1', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh1', 1
	12	play	1, 'bwhoosh2', 1
	12	play	1, 'whoosh1', 1
	61	end
	end

      	playlist	450, 1, 'Sub-Zero: freeze pee puddle'
	0	setvol	1, 0
	0	rampupvol	1, 80, 3
	0	play	1, 'szice2', 1
	40	rampdownvol	1, 80, 20
	20	end
	end

      	playlist	451, 2, 'Sub-Zero: freeze pee puddle'
	0	setvol	2, 0
	0	rampupvol	2, 80, 3
	0	play	2, 'szice2', 1
	40	rampdownvol	2, 80, 20
	20	end
	end

      	playlist	452, 3, 'Sub-Zero: freeze pee puddle'
	0	setvol	3, 0
	0	rampupvol	3, 80, 3
	0	play	3, 'szice2', 1
	40	rampdownvol	3, 80, 20
	20	end
	end

      	playlist	453, 1, 'Sub-Zero: throw ice'
	0	setvol	1, 85
	0	play	1, 'szice1', 1
	11	play	1, 'szice2', 1
	60	play	1, 'szice3', 1
	111	end
	end

      	playlist	454, 2, 'Sub-Zero: throw ice'
	0	setvol	2, 85
	0	play	2, 'szice1', 1
	11	play	2, 'szice2', 1
	60	play	2, 'szice3', 1
	111	end
	end

      	playlist	455, 3, 'Sub-Zero: throw ice'
	0	setvol	3, 85
	0	play	3, 'szice1', 1
	11	play	3, 'szice2', 1
	60	play	3, 'szice3', 1
	111	end
	end

      	playlist	456, 1, 'Reptile: slow moving orb #1 - infinite'
	0	loopstart	0
	0	setvol	1, 0
	0	rampupvol	1, 80, 5
	0	play	1, 'reporb4l', 1
	15	loopend
	65535	end
	end

      	playlist	457, 2, 'Reptile: slow moving orb #1 - infinite'
	0	loopstart	0
	0	setvol	2, 0
	0	rampupvol	2, 80, 5
	0	play	2, 'reporb4l', 1
	15	loopend
	65535	end
	end

      	playlist	458, 3, 'Reptile: slow moving orb #1 - infinite'
	0	loopstart	0
	0	setvol	3, 0
	0	rampupvol	3, 80, 5
	0	play	3, 'reporb4l', 1
	15	loopend
	65535	end
	end

      	playlist	459, 1, 'Reptile: orb explodes'
	0	downvol	0, 35
	0	setvol	1, 115
	0	play	1, 'repblow', 1
	20	rampupvol	0, 35, 49
	129	end
	end

      	playlist	460, 2, 'Reptile: orb explodes'
	0	downvol	0, 35
	0	setvol	2, 115
	0	play	2, 'repblow', 1
	20	rampupvol	0, 35, 49
	129	end
	end

      	playlist	461, 3, 'Reptile: orb explodes'
	0	downvol	0, 35
	0	setvol	3, 115
	0	play	3, 'repblow', 1
	20	rampupvol	0, 35, 49
	129	end
	end

      	playlist	462, 1, 'Johnny Cage: nut crunch'
	0	downvol	0, 20
	0	setvol	1, 100
	0	play	1, 'crunch1', 1
	20	rampupvol	0, 20, 26
	56	end
	end

      	playlist	463, 2, 'Johnny Cage: nut crunch'
	0	downvol	0, 20
	0	setvol	2, 100
	0	play	2, 'crunch1', 1
	20	rampupvol	0, 20, 26
	56	end
	end

      	playlist	464, 3, 'Johnny Cage: nut crunch'
	0	downvol	0, 20
	0	setvol	3, 100
	0	play	3, 'crunch1', 1
	20	rampupvol	0, 20, 26
	56	end
	end

      	playlist	465, 1, 'Raiden: Dive and carry'
	0	setvol	1, 105
	0	play	1, 'rdive', 1
	147	end
	end

      	playlist	466, 2, 'Raiden: Dive and carry'
	0	setvol	2, 105
	0	play	2, 'rdive', 1
	147	end
	end

      	playlist	467, 3, 'Raiden: Dive and carry'
	0	setvol	3, 105
	0	play	3, 'rdive', 1
	147	end
	end

      	playlist	468, 1, 'Scorpion: teleport'
	0	setvol	1, 115
	0	play	1, 'scortele', 1
	83	end
	end

      	playlist	469, 2, 'Scorpion: teleport'
	0	setvol	2, 115
	0	play	2, 'scortele', 1
	83	end
	end

      	playlist	470, 3, 'Scorpion: teleport'
	0	setvol	3, 115
	0	play	3, 'scortele', 1
	83	end
	end

      	playlist	471, 1, 'Kung Lao: teleport'
	0	setvol	1, 100
	0	play	1, 'kungtele', 1
	119	end
	end

      	playlist	472, 2, 'Kung Lao: teleport'
	0	setvol	2, 100
	0	play	2, 'kungtele', 1
	119	end
	end

      	playlist	473, 3, 'Kung Lao: teleport'
	0	setvol	3, 100
	0	play	3, 'kungtele', 1
	119	end
	end

      	playlist	474, 1, 'Malena: teleport'
	0	setvol	1, 100
	0	play	1, 'mlenatel', 1
	128	end
	end

      	playlist	475, 2, 'Malena: teleport'
	0	setvol	2, 100
	0	play	2, 'mlenatel', 1
	128	end
	end

      	playlist	476, 3, 'Malena: teleport'
	0	setvol	3, 100
	0	play	3, 'mlenatel', 1
	128	end
	end

      	playlist	477, 1, 'Shang Tsung: morph'
	0	setvol	1, 100
	0	play	1, 'shngmrph', 1
	103	end
	end

      	playlist	478, 2, 'Shang Tsung: morph'
	0	setvol	2, 100
	0	play	2, 'shngmrph', 1
	103	end
	end

      	playlist	479, 3, 'Shang Tsung: morph'
	0	setvol	3, 100
	0	play	3, 'shngmrph', 1
	103	end
	end

      	playlist	480, 1, 'Baraka: sword snot'
	0	setvol	1, 90
	0	play	1, 'barthrow', 1
	127	end
	end

      	playlist	481, 2, 'Baraka: sword snot'
	0	setvol	2, 90
	0	play	2, 'barthrow', 1
	127	end
	end

      	playlist	482, 3, 'Baraka: sword snot'
	0	setvol	3, 90
	0	play	3, 'barthrow', 1
	127	end
	end

      	playlist	483, 1, 'Baraka: sword snot hits'
	0	setvol	1, 105
	0	play	1, 'bigstab3', 1
	159	end
	end

      	playlist	484, 2, 'Baraka: sword snot hits'
	0	setvol	2, 105
	0	play	2, 'bigstab3', 1
	159	end
	end

      	playlist	485, 3, 'Baraka: sword snot hits'
	0	setvol	3, 105
	0	play	3, 'bigstab3', 1
	159	end
	end

      	playlist	486, 1, 'Baraka: sword snot blocked'
	0	setvol	1, 90
	0	play	1, 'bigstab3', 1
	0	rampdownvol	1, 90, 30
	30	end
	end

      	playlist	487, 2, 'Baraka: sword snot blocked'
	0	setvol	2, 90
	0	play	2, 'bigstab3', 1
	0	rampdownvol	2, 90, 30
	30	end
	end

      	playlist	488, 3, 'Baraka: sword snot blocked'
	0	setvol	3, 90
	0	play	3, 'bigstab3', 1
	0	rampdownvol	3, 90, 30
	30	end
	end

      	playlist	489, 1, 'Sub-Zero: ice hits'
	0	setvol	1, 105
	0	play	1, 'szfreeze', 1
	83	end
	end

      	playlist	490, 2, 'Sub-Zero: ice hits'
	0	setvol	2, 105
	0	play	2, 'szfreeze', 1
	83	end
	end

      	playlist	491, 3, 'Sub-Zero: ice hits'
	0	setvol	3, 105
	0	play	3, 'szfreeze', 1
	83	end
	end

      	playlist	492, 1, 'Sub-Zero: ice blocked'
	0	setvol	1, 90
	0	play	1, 'szfreeze', 1
	0	rampdownvol	1, 90, 30
	30	end
	end

      	playlist	493, 2, 'Sub-Zero: ice blocked'
	0	setvol	2, 90
	0	play	2, 'szfreeze', 1
	0	rampdownvol	2, 90, 30
	30	end
	end

      	playlist	494, 3, 'Sub-Zero: ice blocked'
	0	setvol	3, 90
	0	play	3, 'szfreeze', 1
	0	rampdownvol	3, 90, 30
	30	end
	end

      	playlist	495, 1, 'Kung Lao: spin sound (4 times)'
	0	setvol	1, 105
	0	play	1, 'kungspin', 1
	131	end
	end

      	playlist	496, 2, 'Kung Lao: spin sound'
	0	setvol	2, 105
	0	play	2, 'kungspin', 1
	131	end
	end

      	playlist	497, 3, 'Kung Lao: spin sound'
	0	setvol	3, 105
	0	play	3, 'kungspin', 1
	131	end
	end

; **************************************************************************
; *                                                                        *
; *                         General Effects                                *
; *                                                                        *
; **************************************************************************

      	playlist	500, 1, 'Big door slides shut'
	0	setvol	1, 105
	0	play	1, 'doorslid', 1
	231	end
	end

      	playlist	501, 2, 'Big door slides shut'
	0	setvol	2, 105
	0	play	2, 'doorslid', 1
	231	end
	end

      	playlist	502, 3, 'Big door slides shut'
	0	setvol	3, 105
	0	play	3, 'doorslid', 1
	231	end
	end

      	playlist	503, 1, 'Big door closes'
	0	downvol	0, 20
	0	setvol	1, 110
	0	play	1, 'doorclos', 1
	30	upvol	0, 20
	190	rampdownvol	1, 90, 15
	15	end
	end

      	playlist	504, 2, 'Big door closes'
	0	downvol	0, 20
	0	setvol	2, 110
	0	play	2, 'doorclos', 1
	30	upvol	0, 20
	190	rampdownvol	2, 90, 15
	15	end
	end

      	playlist	505, 3, 'Big door closes'
	0	downvol	0, 20
	0	setvol	3, 110
	0	play	3, 'doorclos', 1
	30	upvol	0, 20
	190	rampdownvol	3, 90, 15
	15	end
	end

      	playlist	506, 1, 'screen message hits'
	0	downvol	0, 60
	0	setvol	1, 100
	0	play	1, 'message', 1
	90	rampupvol	0, 60, 58
	58	end
	end

      	playlist	507, 2, 'screen message hits'
	0	downvol	0, 60
	0	setvol	2, 100
	0	play	2, 'message', 1
	90	rampupvol	0, 60, 58
	58	end
	end

      	playlist	508, 3, 'screen message hits'
	0	downvol	0, 60
	0	setvol	3, 100
	0	play	3, 'message', 1
	90	rampupvol	0, 60, 58
	58	end
	end

      	playlist	509, 1, 'baby #1'
	0	setvol	1, 105
	0	play	1, 'baby1', 1
	142	end
	end

      	playlist	510, 2, 'baby #1'
	0	setvol	2, 105
	0	play	2, 'baby1', 1
	142	end
	end

      	playlist	511, 3, 'baby #1'
	0	setvol	3, 105
	0	play	3, 'baby1', 1
	142	end
	end

      	playlist	512, 1, 'baby #2'
	0	setvol	1, 105
	0	play	1, 'baby2', 1
	282	end
	end

      	playlist	513, 2, 'baby #2'
	0	setvol	2, 105
	0	play	2, 'baby2', 1
	282	end
	end

      	playlist	514, 3, 'baby #2'
	0	setvol	3, 105
	0	play	3, 'baby2', 1
	282	end
	end

      	playlist	515, 1, 'Splish #1'
	0	setvol	1, 85
	0	play	1, 'splish1', 1
	42	end
	end

      	playlist	516, 2, 'Splish #1'
	0	setvol	2, 85
	0	play	2, 'splish1', 1
	42	end
	end

      	playlist	517, 3, 'Splish #1'
	0	setvol	3, 85
	0	play	3, 'splish1', 1
	42	end
	end

      	playlist	518, 1, 'Splish #2'
	0	setvol	1, 85
	0	play	1, 'splish2', 1
	34	end
	end

      	playlist	519, 2, 'Splish #2'
	0	setvol	2, 85
	0	play	2, 'splish2', 1
	34	end
	end

      	playlist	520, 3, 'Splish #2'
	0	setvol	3, 85
	0	play	3, 'splish2', 1
	34	end
	end

      	playlist	521, 1, 'Splish #3'
	0	setvol	1, 85
	0	play	1, 'splish3', 1
	93	end
	end

      	playlist	522, 2, 'Splish #3'
	0	setvol	2, 85
	0	play	2, 'splish3', 1
	93	end
	end

      	playlist	523, 3, 'Splish #3'
	0	setvol	3, 85
	0	play	3, 'splish3', 1
	93	end
	end

      	playlist	524, 1, 'Cursor: low D'
	0	setvol	1, 55
	0	play	1, 'kotod1', 1
	48	end
	end

      	playlist	525, 2, 'Cursor: low D'
	0	setvol	2, 55
	0	play	2, 'kotod1', 1
	48	end
	end

      	playlist	526, 3, 'Cursor: low D'
	0	setvol	3, 55
	0	play	3, 'kotod1', 1
	48	end
	end

      	playlist	527, 1, 'Cursor: G'
	0	setvol	1, 55
	0	play	1, 'kotog', 1
	43	end
	end

      	playlist	528, 2, 'Cursor: G'
	0	setvol	2, 55
	0	play	2, 'kotog', 1
	43	end
	end

      	playlist	529, 3, 'Cursor: G'
	0	setvol	3, 55
	0	play	3, 'kotog', 1
	43	end
	end

      	playlist	530, 1, 'Pick Player #1'
	0	setvol	1, 90
	0	play	1, 'picked1', 1
	80	rampdownvol	1, 90, 15
	15	end
	end

      	playlist	531, 2, 'Pick Player #1'
	0	setvol	2, 90
	0	play	2, 'picked1', 1
	80	rampdownvol	2, 90, 15
	15	end
	end

      	playlist	532, 3, 'Pick Player #1'
	0	setvol	3, 90
	0	play	3, 'picked1', 1
	80	rampdownvol	3, 90, 15
	15	end
	end

      	playlist	533, 1, 'Pick Player #2'
	0	setvol	1, 90
	0	play	1, 'picked2', 1
	110	rampdownvol	1, 90, 15
	15	end
	end

      	playlist	534, 2, 'Pick Player #2'
	0	setvol	2, 90
	0	play	2, 'picked2', 1
	110	rampdownvol	2, 90, 15
	15	end
	end

      	playlist	535, 3, 'Pick Player #2'
	0	setvol	3, 90
	0	play	3, 'picked2', 1
	110	rampdownvol	3, 90, 15
	15	end
	end

      	playlist	536, 1, 'Time-Down Tick'
	0	setvol	1, 90
	0	play	1, 'timeout1', 1
	27	end
	end

      	playlist	537, 2, 'Time-Down Tick'
	0	setvol	2, 90	 
	0	play	2, 'timeout1', 1
	27	end
	end

      	playlist	538, 3, 'Time-Down Tick'
	0	setvol	3, 90
	0	play	3, 'timeout1', 1
	27	end
	end

      	playlist	539, 1, 'Gong #1'
	0	setvol	1, 105
	0	play	1, 'gong1', 1
	300	rampdownvol	1, 100, 33
	33	end
	end

      	playlist	540, 2, 'Gong #1'
	0	setvol	2, 105
	0	play	2, 'gong1', 1
	300	rampdownvol	2, 100, 33
	33	end
	end

      	playlist	541, 3, 'Gong #1'
	0	setvol	3, 105
	0	play	3, 'gong1', 1
	300	rampdownvol	3, 100, 33
	33	end
	end

      	playlist	542, 1, 'Cursor: low E'
	0	setvol	1, 55
	0	play	1, 'kotoe1', 1
	45	end
	end

      	playlist	543, 2, 'Cursor: low E'
	0	setvol	2, 55
	0	play	2, 'kotoe1', 1
	45	end
	end

      	playlist	544, 3, 'Cursor: low E'
	0	setvol	3, 55
	0	play	3, 'kotoe1', 1
	45	end
	end

      	playlist	545, 1, 'Cursor: A'
	0	setvol	1, 55
	0	play	1, 'kotoa', 1
	37	end
	end

      	playlist	546, 2, 'Cursor: A'
	0	setvol	2, 55
	0	play	2, 'kotoa', 1
	37	end
	end

      	playlist	547, 3, 'Cursor: A'
	0	setvol	3, 55
	0	play	3, 'kotoa', 1
	37	end
	end

      	playlist	548, 1, 'Cursor: B'
	0	setvol	1, 55
	0	play	1, 'kotob', 1
	34	end
	end

      	playlist	549, 2, 'Cursor: B'
	0	setvol	2, 55
	0	play	2, 'kotob', 1
	34	end
	end

      	playlist	550, 3, 'Cursor: B'
	0	setvol	3, 55
	0	play	3, 'kotob', 1
	34	end
	end

      	playlist	551, 1, 'Cursor: high D'
	0	setvol	1, 55
	0	play	1, 'kotod2', 1
	40	end
	end

      	playlist	552, 2, 'Cursor: high D'
	0	setvol	2, 55
	0	play	2, 'kotod2', 1
	40	end
	end

      	playlist	553, 3, 'Cursor: high D'
	0	setvol	3, 55
	0	play	3, 'kotod2', 1
	40	end
	end

      	playlist	554, 1, 'Cursor: high E'
	0	setvol	1, 55
	0	play	1, 'kotoe2', 1
	40	end
	end

      	playlist	555, 2, 'Cursor: high E'
	0	setvol	2, 55
	0	play	2, 'kotoe2', 1
	40	end
	end

      	playlist	556, 3, 'Cursor: high E'
	0	setvol	3, 55
	0	play	3, 'kotoe2', 1
	40	end
	end

      	playlist	557, 1, 'Cursor: F#'
	0	setvol	1, 55
	0	play	1, 'kotofs', 1
	42	end
	end

      	playlist	558, 2, 'Cursor: F#'
	0	setvol	2, 55
	0	play	2, 'kotofs', 1
	42	end
	end

      	playlist	559, 3, 'Cursor: F#'
	0	setvol	3, 55
	0	play	3, 'kotofs', 1
	42	end
	end

      	playlist	560, 1, 'Cursor: C#'
	0	setvol	1, 55
	0	play	1, 'kotocs', 1
	42	end
	end

      	playlist	561, 2, 'Cursor: C#'
	0	setvol	2, 55
	0	play	2, 'kotocs', 1
	42	end
	end

      	playlist	562, 3, 'Cursor: C#'
	0	setvol	3, 55
	0	play	3, 'kotocs', 1
	42	end
	end

      	playlist	563, 1, 'Distant Thunder #1'
	0	setvol	1, 105
	0	downvol	0, 20
	0	play	1, 'dthun1', 1
	80	rampupvol	0, 20, 44
	48	end
	end

      	playlist	564, 2, 'Distant Thunder #1'
	0	setvol	2, 105
	0	downvol	0, 20
	0	play	2, 'dthun1', 1
	80	rampupvol	0, 20, 44
	48	end
	end

      	playlist	565, 3, 'Distant Thunder #1'
	0	setvol	3, 105
	0	downvol	0, 20
	0	play	3, 'dthun1', 1
	80	rampupvol	0, 20, 44
	48	end
	end

      	playlist	566, 1, 'Distant Thunder #2'
	0	setvol	1, 105
	0	downvol	0, 20
	0	play	1, 'dthun2', 1
	80	rampupvol	0, 20, 38
	36	end
	end

      	playlist	567, 2, 'Distant Thunder #2'
	0	setvol	2, 105
	0	downvol	0, 20
	0	play	2, 'dthun2', 1
	80	rampupvol	0, 20, 38
	36	end
	end

      	playlist	568, 3, 'Distant Thunder #2'
	0	setvol	3, 105
	0	downvol	0, 20
	0	play	3, 'dthun2', 1
	80	rampupvol	0, 20, 38
	36	end
	end

      	playlist	569, 1, 'Big Lightning bolt'
	0	downvol	0, 15
	0	setvol	1, 115
	0	play	1, 'lightng', 1
	215	rampdownvol	1, 115, 60
	0	rampupvol	0, 15, 20
	60	end
	end

      	playlist	570, 2, 'Big Lightning bolt'
	0	downvol	0, 15
	0	setvol	2, 115
	0	play	2, 'lightng', 1
	215	rampdownvol	2, 115, 60
	0	rampupvol	0, 15, 20
	60	end
	end

      	playlist	571, 3, 'Big Lightning bolt'
	0	downvol	0, 15
	0	setvol	3, 115
	0	play	3, 'lightng', 1
	215	rampdownvol	3, 115, 60
	0	rampupvol	0, 15, 20
	60	end
	end

      	playlist	572, 1, 'FX: Quick low drone'
	0	setvol	1, 105
	0	play	1, 'qdrone', 1
	572	end
	end

      	playlist	573, 2, 'FX: Quick low drone'
	0	setvol	2, 105
	0	play	2, 'qdrone', 1
	572	end
	end

      	playlist	574, 3, 'FX: Quick low drone'
	0	setvol	3, 105
	0	play	3, 'qdrone', 1
	572	end
	end

      	playlist	575, 1, 'FX: Reverse cymbal'
	0	setvol	1, 95
	0	play	1, 'revcym', 1
	321	end
	end

      	playlist	576, 2, 'FX: Reverse cymbal'
	0	setvol	2, 95
	0	play	2, 'revcym', 1
	321	end
	end

      	playlist	577, 2, 'FX: Reverse cymbal'
	0	setvol	3, 95
	0	play	3, 'revcym', 1
	321	end
	end

      	playlist	578, 1, 'FX: Flawless Victory tone'
	0	setvol	1, 100
	0	rampdownvol	0, 50, 100
	0	play	1, 'flawtone', 1
	350	rampupvol	0, 50, 100
	139	end
	end

      	playlist	579, 2, 'FX: Flawless Victory tone'
	0	setvol	2, 100
	0	rampdownvol	0, 50, 100
	0	play	2, 'flawtone', 1
	350	rampupvol	0, 50, 100
	139	end
	end

      	playlist	580, 3, 'FX: Flawless Victory tone'
	0	setvol	3, 100
	0	rampdownvol	0, 50, 100
	0	play	3, 'flawtone', 1
	350	rampupvol	0, 50, 100
	139	end
	end

      	playlist	581, 1, 'FX: Fatality Blood Drips'
	0	setvol	1, 103
	0	play	1, 'fataldrp', 1
	380	rampdownvol	1, 105, 26
	26	end
	end

      	playlist	582, 2, 'FX: Fatality Blood Drips'
	0	setvol	2, 103
	0	play	2, 'fataldrp', 1
	380	rampdownvol	2, 105, 26
	26	end
	end

      	playlist	583, 3, 'FX: Fatality Blood Drips'
	0	setvol	3, 103
	0	play	3, 'fataldrp', 1
	380	rampdownvol	3, 105, 26
	26	end
	end

      	playlist	584, 1, 'FX: Player 2 Start'
	0	setvol	1, 95
	0	play	1, 'player2', 1
	110	end
	end

      	playlist	585, 2, 'FX: Player 2 Start'
	0	setvol	2, 95
	0	play	2, 'player2', 1
	110	end
	end

      	playlist	586, 3, 'FX: Player 2 Start'
	0	setvol	3, 95
	0	play	3, 'player2', 1
	110	end
	end

      	playlist	587, 1, 'Crowd "oooh"'
	0	setvol	1, 105
	0	play	1, 'oooh', 1
	237	end
	end

      	playlist	588, 2, 'Crowd "oooh"'
	0	setvol	2, 105
	0	play	2, 'oooh', 1
	237	end
	end

      	playlist	589, 3, 'Crowd "oooh"'
	0	setvol	3, 105
	0	play	3, 'oooh', 1
	237	end
	end

      	playlist	590, 1, 'Big crunch/step/bang'
	0	downvol	0, 20
	0	setvol	1, 105
	0	play	1, 'bigcrnch', 1
	20	upvol	0, 20
	175	end
	end

      	playlist	591, 2, 'Big crunch/step/bang'
	0	downvol	0, 20
	0	setvol	2, 105
	0	play	2, 'bigcrnch', 1
	20	upvol	0, 20
	175	end
	end

      	playlist	592, 3, 'Big crunch/step/bang'
	0	downvol	0, 20
	0	setvol	3, 105
	0	play	3, 'bigcrnch', 1
	20	upvol	0, 20
	175	end
	end

      	playlist	593, 1, 'Goro foot step'
	0	downvol	0, 30
	0	setvol	1, 105
	0	play	1, 'gorofoot', 1
	20	upvol	0, 30
	130	rampdownvol	1, 100, 8
	8	end
	end

      	playlist	594, 2, 'Goro foot step'
	0	downvol	0, 30
	0	setvol	2, 105
	0	play	2, 'gorofoot', 1
	20	upvol	0, 30
	130	rampdownvol	2, 100, 8
	8	end
	end

      	playlist	595, 3, 'Goro foot step'
	0	downvol	0, 30
	0	setvol	3, 105
	0	play	3, 'gorofoot', 1
	20	upvol	0, 30
	130	rampdownvol	3, 100, 8
	8	end
	end

      	playlist	596, 1, 'Fall into pit'
	0	setvol	1, 105
	0	play	1, 'pitfall', 1
	137	end
	end

      	playlist	597, 2, 'Fall into pit'
	0	setvol	2, 105
	0	play	2, 'pitfall', 1
	137	end
	end

      	playlist	598, 3, 'Fall into pit'
	0	setvol	3, 105
	0	play	3, 'pitfall', 1
	137	end
	end

; **************************************************************************
; *                                                                        *
; *                         Speech                                         *
; *                                                                        *
; **************************************************************************

      	playlist	600, 1, 'DF: attack 1'
	0	setvol	1, 105
	0	play	1, 'dfatak1', 1
	57	end
	end

      	playlist	601, 2, 'DF: attack 1'
	0	setvol	2, 105
	0	play	2, 'dfatak1', 1
	57	end
	end

      	playlist	602, 3, 'DF: attack 1'
	0	setvol	3, 105
	0	play	3, 'dfatak1', 1
	57	end
	end

      	playlist	603, 1, 'DF: attack 2'
	0	setvol	1, 105
	0	play	1, 'dfatak2', 1
	44	end
	end

      	playlist	604, 2, 'DF: attack 2'
	0	setvol	2, 105
	0	play	2, 'dfatak2', 1
	44	end
	end

      	playlist	605, 3, 'DF: attack 2'
	0	setvol	3, 105
	0	play	3, 'dfatak2', 1
	44	end
	end

      	playlist	606, 1, 'DF: jump'
	0	setvol	1, 100
	0	play	1, 'dfjump', 1
	47	end
	end

      	playlist	607, 2, 'DF: jump'
	0	setvol	2, 100
	0	play	2, 'dfjump', 1
	47	end
	end

      	playlist	608, 3, 'DF: jump'
	0	setvol	3, 100
	0	play	3, 'dfjump', 1
	47	end
	end

      	playlist	609, 1, 'DF: trip'
	0	setvol	1, 100
	0	play	1, 'dftrip', 1
	69	end
	end

      	playlist	610, 2, 'DF: trip'
	0	setvol	2, 100
	0	play	2, 'dftrip', 1
	69	end
	end

      	playlist	611, 3, 'DF: trip'
	0	setvol	3, 100
	0	play	3, 'dftrip', 1
	69	end
	end

      	playlist	612, 1, 'DF: grab'
	0	setvol	1, 100
	0	play	1, 'dfgrab', 1
	39	end
	end

      	playlist	613, 2, 'DF: grab'
	0	setvol	2, 100
	0	play	2, 'dfgrab', 1
	39	end
	end

      	playlist	614, 3, 'DF: grab'
	0	setvol	3, 100
	0	play	3, 'dfgrab', 1
	39	end
	end

      	playlist	615, 1, 'DF: throw'
	0	setvol	1, 100
	0	play	1, 'dfthrow', 1
	101	end
	end

      	playlist	616, 2, 'DF: throw'
	0	setvol	2, 100
	0	play	2, 'dfthrow', 1
	101	end
	end

      	playlist	617, 3, 'DF: throw'
	0	setvol	3, 100
	0	play	3, 'dfthrow', 1
	101	end
	end

      	playlist	618, 1, 'DF: react 1'
	0	setvol	1, 100
	0	play	1, 'dfreact1', 1
	73	end
	end

      	playlist	619, 2, 'DF: react 1'
	0	setvol	2, 100
	0	play	2, 'dfreact1', 1
	73	end
	end

      	playlist	620, 3, 'DF: react 1'
	0	setvol	3, 100
	0	play	3, 'dfreact1', 1
	73	end
	end

      	playlist	621, 1, 'DF: react 2'
	0	setvol	1, 100
	0	play	1, 'dfreact2', 1
	91	end
	end

      	playlist	622, 2, 'DF: react 2'
	0	setvol	2, 100
	0	play	2, 'dfreact2', 1
	91	end
	end

      	playlist	623, 3, 'DF: react 2'
	0	setvol	3, 100
	0	play	3, 'dfreact2', 1
	91	end
	end

      	playlist	624, 1, 'DF: react 3'
	0	setvol	1, 100
	0	play	1, 'dfreact3', 1
	87	end
	end

      	playlist	625, 2, 'DF: react 3'
	0	setvol	2, 100
	0	play	2, 'dfreact3', 1
	87	end
	end

      	playlist	626, 3, 'DF: react 3'
	0	setvol	3, 100
	0	play	3, 'dfreact3', 1
	87	end
	end

      	playlist	627, 1, 'DF: wast 1'
	0	setvol	1, 100
	0	play	1, 'dfwast1', 1
	213	end
	end

      	playlist	628, 2, 'DF: wast 1'
	0	setvol	2, 100
	0	play	2, 'dfwast1', 1
	213	end
	end

      	playlist	629, 3, 'DF: wast 1'
	0	setvol	3, 100
	0	play	3, 'dfwast1', 1
	213	end
	end

      	playlist	630, 1, 'DF: wast 2'
	0	setvol	1, 100
	0	play	1, 'dfwast2', 1
	113	end
	end

      	playlist	631, 2, 'DF: wast 2'
	0	setvol	2, 100
	0	play	2, 'dfwast2', 1
	113	end
	end

      	playlist	632, 3, 'DF: wast 2'
	0	setvol	3, 100
	0	play	3, 'dfwast2', 1
	113	end
	end

      	playlist	633, 1, 'DF: death 1'
	0	setvol	1, 100
	0	play	1, 'dfdeath1', 1
	159	end
	end

      	playlist	634, 2, 'DF: death 1'
	0	setvol	2, 100
	0	play	2, 'dfdeath1', 1
	159	end
	end

      	playlist	635, 3, 'DF: death 1'
	0	setvol	3, 100
	0	play	3, 'dfdeath1', 1
	159	end
	end

      	playlist	636, 1, 'DF: fall/death scream'
	0	setvol	1, 100
	0	play	1, 'dfskream', 1
	307	end
	end

      	playlist	637, 2, 'DF: fall/death scream'
	0	setvol	2, 100
	0	play	2, 'dfskream', 1
	307	end
	end

      	playlist	638, 3, 'DF: fall/death scream'
	0	setvol	3, 100
	0	play	3, 'dfskream', 1
	307	end
	end

      	playlist	642, 1, 'DF: Yeah!'
	0	setvol	1, 104
	0	play	1, 'dfyea', 1
	93	end
	end

      	playlist	643, 2, 'DF: Yeah!'
	0	setvol	2, 104
	0	play	2, 'dfyea', 1
	93	end
	end

      	playlist	644, 3, 'DF: Yeah!'
	0	setvol	3, 104
	0	play	3, 'dfyea', 1
	93	end
	end

      	playlist	645, 1, 'DF: Tosty!'
	0	setvol	1, 104
	0	play	1, 'tosty', 1
	90	end
	end

      	playlist	646, 2, 'DF: Tosty!'
	0	setvol	2, 104
	0	play	2, 'tosty', 1
	90	end
	end

      	playlist	647, 3, 'DF: Tosty!'
	0	setvol	3, 104
	0	play	3, 'tosty', 1
	90	end
	end

      	playlist	650, 1, 'JH: attack 1'
	0	setvol	1, 96
	0	play	1, 'jhattak1', 1
	68	end
	end

      	playlist	651, 2, 'JH: attack 1'
	0	setvol	2, 96
	0	play	2, 'jhattak1', 1
	68	end
	end

      	playlist	652, 3, 'JH: attack 1'
	0	setvol	3, 96
	0	play	3, 'jhattak1', 1
	68	end
	end

      	playlist	653, 1, 'JH: attack 2'
	0	setvol	1, 96
	0	play	1, 'jhattak2', 1
	68	end
	end

      	playlist	654, 2, 'JH: attack 2'
	0	setvol	2, 96
	0	play	2, 'jhattak2', 1
	68	end
	end

      	playlist	655, 3, 'JH: attack 2'
	0	setvol	3, 96
	0	play	3, 'jhattak2', 1
	68	end
	end

      	playlist	656, 1, 'JH: jump'
	0	setvol	1, 96
	0	play	1, 'jhjump', 1
	51	end
	end

      	playlist	657, 2, 'JH: jump'
	0	setvol	2, 96
	0	play	2, 'jhjump', 1
	51	end
	end

      	playlist	658, 3, 'JH: jump'
	0	setvol	3, 96
	0	play	3, 'jhjump', 1
	51	end
	end

      	playlist	659, 1, 'JH: trip'
	0	setvol	1, 96
	0	play	1, 'jhtrip', 1
	75	end
	end

      	playlist	660, 2, 'JH: trip'
	0	setvol	2, 96
	0	play	2, 'jhtrip', 1
	75	end
	end

      	playlist	661, 3, 'JH: trip'
	0	setvol	3, 96
	0	play	3, 'jhtrip', 1
	75	end
	end

      	playlist	662, 1, 'JH: grab'
	0	setvol	1, 96
	0	play	1, 'jhgrab', 1
	55	end
	end

      	playlist	663, 2, 'JH: grab'
	0	setvol	2, 96
	0	play	2, 'jhgrab', 1
	55	end
	end

      	playlist	664, 3, 'JH: grab'
	0	setvol	3, 96
	0	play	3, 'jhgrab', 1
	55	end
	end

      	playlist	665, 1, 'JH: throw'
	0	setvol	1, 96
	0	play	1, 'jhthrow', 1
	126	end
	end

      	playlist	666, 2, 'JH: throw'
	0	setvol	2, 96
	0	play	2, 'jhthrow', 1
	126	end
	end

      	playlist	667, 3, 'JH: throw'
	0	setvol	3, 96
	0	play	3, 'jhthrow', 1
	126	end
	end

      	playlist	668, 1, 'JH: react 1'
	0	setvol	1, 96
	0	play	1, 'jhreact1', 1
	97	end
	end

      	playlist	669, 2, 'JH: react 1'
	0	setvol	2, 96
	0	play	2, 'jhreact1', 1
	97	end
	end

      	playlist	670, 3, 'JH: react 1'
	0	setvol	3, 96
	0	play	3, 'jhreact1', 1
	97	end
	end

      	playlist	671, 1, 'JH: react 2'
	0	setvol	1, 96
	0	play	1, 'jhreact2', 1
	83	end
	end

      	playlist	672, 2, 'JH: react 2'
	0	setvol	2, 96
	0	play	2, 'jhreact2', 1
	83	end
	end

      	playlist	673, 3, 'JH: react 2'
	0	setvol	3, 96
	0	play	3, 'jhreact2', 1
	83	end
	end

      	playlist	674, 1, 'JH: react 3'
	0	setvol	1, 96
	0	play	1, 'jhreact3', 1
	77	end
	end

      	playlist	675, 2, 'JH: react 3'
	0	setvol	2, 96
	0	play	2, 'jhreact3', 1
	77	end
	end

      	playlist	676, 3, 'JH: react 3'
	0	setvol	3, 96
	0	play	3, 'jhreact3', 1
	77	end
	end

      	playlist	677, 1, 'JH: wast 1'
	0	setvol	1, 96
	0	play	1, 'jhwast1', 1
	228	end
	end

      	playlist	678, 2, 'JH: wast 1'
	0	setvol	2, 96
	0	play	2, 'jhwast1', 1
	228	end
	end

      	playlist	679, 3, 'JH: wast 1'
	0	setvol	3, 96
	0	play	3, 'jhwast1', 1
	228	end
	end

      	playlist	680, 1, 'JH: wast 2'
	0	setvol	1, 96
	0	play	1, 'jhwast2', 1
	224	end
	end

      	playlist	681, 2, 'JH: wast 2'
	0	setvol	2, 96
	0	play	2, 'jhwast2', 1
	224	end
	end

      	playlist	682, 3, 'JH: wast 2'
	0	setvol	3, 96
	0	play	3, 'jhwast2', 1
	224	end
	end

      	playlist	683, 1, 'JH: death 1'
	0	setvol	1, 96
	0	play	1, 'jhdeath1', 1
	430	end
	end

      	playlist	684, 2, 'JH: death 1'
	0	setvol	2, 96
	0	play	2, 'jhdeath1', 1
	430	end
	end

      	playlist	685, 3, 'JH: death 1'
	0	setvol	3, 96
	0	play	3, 'jhdeath1', 1
	430	end
	end

      	playlist	686, 1, 'JH: gibberish #1'
	0	setvol	1, 104
	0	play	1, 'gib1', 1
	174	end
	end

      	playlist	687, 2, 'JH: gibberish #1'
	0	setvol	2, 104
	0	play	2, 'gib1', 1
	174	end
	end

      	playlist	688, 3, 'JH: gibberish #1'
	0	setvol	3, 104
	0	play	3, 'gib1', 1
	174	end
	end

      	playlist	689, 1, 'JH: gibberish #2'
	0	setvol	1, 104
	0	play	1, 'gib2', 1
	188	end
	end

      	playlist	690, 2, 'JH: gibberish #2'
	0	setvol	2, 104
	0	play	2, 'gib2', 1
	188	end
	end

      	playlist	691, 3, 'JH: gibberish #2'
	0	setvol	3, 104
	0	play	3, 'gib2', 1
	188	end
	end

      	playlist	692, 1, 'JH: gibberish #3'
	0	setvol	1, 104
	0	play	1, 'gib3', 1
	153	end
	end

      	playlist	693, 2, 'JH: gibberish #3'
	0	setvol	2, 104
	0	play	2, 'gib3', 1
	153	end
	end

      	playlist	694, 3, 'JH: gibberish #3'
	0	setvol	3, 104
	0	play	3, 'gib3', 1
	153	end
	end

      	playlist	695, 1, 'JH: gibberish #4'
	0	setvol	1, 104
	0	play	1, 'gib4', 1
	263	end
	end

      	playlist	696, 2, 'JH: gibberish #4'
	0	setvol	2, 104
	0	play	2, 'gib4', 1
	263	end
	end

      	playlist	697, 3, 'JH: gibberish #4'
	0	setvol	3, 104
	0	play	3, 'gib4', 1
	263	end
	end

      	playlist	700, 1, 'Ninja Girl 1: attack 1'
	0	setvol	1, 96
	0	play	1, 'n1attak1', 1
	70	end
	end

      	playlist	701, 2, 'Ninja Girl 1: attack 1'
	0	setvol	2, 96
	0	play	2, 'n1attak1', 1
	70	end
	end

      	playlist	702, 3, 'Ninja Girl 1: attack 1'
	0	setvol	3, 96
	0	play	3, 'n1attak1', 1
	70	end
	end

      	playlist	703, 1, 'Ninja Girl 1: attack 2'
	0	setvol	1, 96
	0	play	1, 'n1attak2', 1
	56	end
	end

      	playlist	704, 2, 'Ninja Girl 1: attack 2'
	0	setvol	2, 96
	0	play	2, 'n1attak2', 1
	56	end
	end

      	playlist	705, 3, 'Ninja Girl 1: attack 2'
	0	setvol	3, 96
	0	play	3, 'n1attak2', 1
	56	end
	end

      	playlist	706, 1, 'Ninja Girl 1: jump'
	0	setvol	1, 96
	0	play	1, 'n1jump', 1
	36	end
	end

      	playlist	707, 2, 'Ninja Girl 1: jump'
	0	setvol	2, 96
	0	play	2, 'n1jump', 1
	36	end
	end

      	playlist	708, 3, 'Ninja Girl 1: jump'
	0	setvol	3, 96
	0	play	3, 'n1jump', 1
	36	end
	end

      	playlist	709, 1, 'Ninja Girl 1: trip'
	0	setvol	1, 96
	0	play	1, 'n1trip', 1
	48	end
	end

      	playlist	710, 2, 'Ninja Girl 1: trip'
	0	setvol	2, 96
	0	play	2, 'n1trip', 1
	48	end
	end

      	playlist	711, 3, 'Ninja Girl 1: trip'
	0	setvol	3, 96
	0	play	3, 'n1trip', 1
	48	end
	end

      	playlist	712, 1, 'Ninja Girl 1: grab'
	0	setvol	1, 96
	0	play	1, 'n1grab', 1
	45	end
	end

      	playlist	713, 2, 'Ninja Girl 1: grab'
	0	setvol	2, 96
	0	play	2, 'n1grab', 1
	45	end
	end

      	playlist	714, 3, 'Ninja Girl 1: grab'
	0	setvol	3, 96
	0	play	3, 'n1grab', 1
	45	end
	end

      	playlist	715, 1, 'Ninja Girl 1: throw'
	0	setvol	1, 96
	0	play	1, 'n1throw', 1
	81	end
	end

      	playlist	716, 2, 'Ninja Girl 1: throw'
	0	setvol	2, 96
	0	play	2, 'n1throw', 1
	81	end
	end

      	playlist	717, 3, 'Ninja Girl 1: throw'
	0	setvol	3, 96
	0	play	3, 'n1throw', 1
	81	end
	end

      	playlist	718, 1, 'Ninja Girl 1: react 1'
	0	setvol	1, 96
	0	play	1, 'n1react1', 1
	60	end
	end

      	playlist	719, 2, 'Ninja Girl 1: react 1'
	0	setvol	2, 96
	0	play	2, 'n1react1', 1
	60	end
	end

      	playlist	720, 3, 'Ninja Girl 1: react 1'
	0	setvol	3, 96
	0	play	3, 'n1react1', 1
	60	end
	end

      	playlist	721, 1, 'Ninja Girl 1: react 2'
	0	setvol	1, 96
	0	play	1, 'n1react2', 1
	63	end
	end

      	playlist	722, 2, 'Ninja Girl 1: react 2'
	0	setvol	2, 96
	0	play	2, 'n1react2', 1
	63	end
	end

      	playlist	723, 3, 'Ninja Girl 1: react 2'
	0	setvol	3, 96
	0	play	3, 'n1react2', 1
	63	end
	end

      	playlist	724, 1, 'Ninja Girl 1: react 3'
	0	setvol	1, 96
	0	play	1, 'n1react3', 1
	60	end
	end

      	playlist	725, 2, 'Ninja Girl 1: react 3'
	0	setvol	2, 96
	0	play	2, 'n1react3', 1
	60	end
	end

      	playlist	726, 3, 'Ninja Girl 1: react 3'
	0	setvol	3, 96
	0	play	3, 'n1react3', 1
	60	end
	end

      	playlist	727, 1, 'Ninja Girl 1: wast 1'
	0	setvol	1, 96
	0	play	1, 'n1wast1', 1
	89	end
	end

      	playlist	728, 2, 'Ninja Girl 1: wast 1'
	0	setvol	2, 96
	0	play	2, 'n1wast1', 1
	89	end
	end

      	playlist	729, 3, 'Ninja Girl 1: wast 1'
	0	setvol	3, 96
	0	play	3, 'n1wast1', 1
	89	end
	end

      	playlist	730, 1, 'Ninja Girl 1: wast 2'
	0	setvol	1, 96
	0	play	1, 'n1wast2', 1
	221	end
	end

      	playlist	731, 2, 'Ninja Girl 1: wast 2'
	0	setvol	2, 96
	0	play	2, 'n1wast2', 1
	221	end
	end

      	playlist	732, 3, 'Ninja Girl 1: wast 2'
	0	setvol	3, 96
	0	play	3, 'n1wast2', 1
	221	end
	end

      	playlist	733, 1, 'Ninja Girl 1: death 1'
	0	setvol	1, 96
	0	play	1, 'n1death1', 1
	370	end
	end

      	playlist	734, 2, 'Ninja Girl 1: death 1'
	0	setvol	2, 96
	0	play	2, 'n1death1', 1
	370	end
	end

      	playlist	735, 3, 'Ninja Girl 1: death 1'
	0	setvol	3, 96
	0	play	3, 'n1death1', 1
	370	end
	end

      	playlist	736, 1, 'Ninja Girl 1: death 2'
	0	setvol	1, 96
	0	play	1, 'n1death2', 1
	385	end
	end

      	playlist	737, 2, 'Ninja Girl 1: death 2'
	0	setvol	2, 96
	0	play	2, 'n1death2', 1
	385	end
	end

      	playlist	738, 3, 'Ninja Girl 1: death 2'
	0	setvol	3, 96
	0	play	3, 'n1death2', 1
	385	end
	end

      	playlist	739, 1, 'Ninja Girl 1: fall down pit'
	0	setvol	1, 96
	0	play	1, 'gpit', 1
	501	end
	end

      	playlist	740, 2, 'Ninja Girl 1: fall down pit'
	0	setvol	2, 96
	0	play	2, 'gpit', 1
	501	end
	end

      	playlist	741, 3, 'Ninja Girl 1: fall down pit'
	0	setvol	3, 96
	0	play	3, 'gpit', 1
	501	end
	end

      	playlist	742, 1, 'Ninja Girl 1: hit bottom of pit'
	0	setvol	1, 105
	0	play	1, 'gpithit', 1
	100	end
	end

      	playlist	743, 2, 'Ninja Girl 1: hit bottom of pit'
	0	setvol	2, 105
	0	play	2, 'gpithit', 1
	100	end
	end

      	playlist	744, 3, 'Ninja Girl 1: hit bottom of pit'
	0	setvol	3, 105
	0	play	3, 'gpithit', 1
	100	end
	end

      	playlist	745, 1, 'Ninja Girl 1: about to explode'
	0	setvol	1, 96
	0	play	1, 'gexplode', 1
	302	end
	end

      	playlist	746, 2, 'Ninja Girl 1: about to explode'
	0	setvol	2, 96
	0	play	2, 'gexplode', 1
	302	end
	end

      	playlist	747, 3, 'Ninja Girl 1: about to explode'
	0	setvol	3, 96
	0	play	3, 'gexplode', 1
	302	end
	end

      	playlist	750, 1, 'Liu Kang: attack 1'
	0	setvol	1, 98
	0	play	1, 'lkattak1', 1
	65	end
	end

      	playlist	751, 2, 'Liu Kang: attack 1'
	0	setvol	2, 98
	0	play	2, 'lkattak1', 1
	65	end
	end

      	playlist	752, 3, 'Liu Kang: attack 1'
	0	setvol	3, 98
	0	play	3, 'lkattak1', 1
	65	end
	end

      	playlist	753, 1, 'Liu Kang: attack 2'
	0	setvol	1, 98
	0	play	1, 'lkattak2', 1
	59	end
	end

      	playlist	754, 2, 'Liu Kang: attack 2'
	0	setvol	2, 98
	0	play	2, 'lkattak2', 1
	59	end
	end

      	playlist	755, 3, 'Liu Kang: attack 2'
	0	setvol	3, 98
	0	play	3, 'lkattak2', 1
	59	end
	end

      	playlist	756, 1, 'Liu Kang: bicycle kicks'
	0	setvol	1, 98
	0	play	1, 'lkcycle', 1
	165	rampdownvol	1, 100, 10
	10	end
	end

      	playlist	757, 2, 'Liu Kang: bicycle kicks'
	0	setvol	2, 98
	0	play	2, 'lkcycle', 1
	165	rampdownvol	2, 100, 10
	10	end
	end

      	playlist	758, 3, 'Liu Kang: bicycle kicks'
	0	setvol	3, 98
	0	play	3, 'lkcycle', 1
	165	rampdownvol	3, 100, 10
	10	end
	end

      	playlist	759, 1, 'Liu Kang: flying kick #1'
	0	setvol	1, 98
	0	play	1, 'lkflyk1', 1
	180	end
	end

      	playlist	760, 2, 'Liu Kang: flying kick #1'
	0	setvol	2, 98
	0	play	2, 'lkflyk1', 1
	180	end
	end

      	playlist	761, 3, 'Liu Kang: flying kick #1'
	0	setvol	3, 98
	0	play	3, 'lkflyk1', 1
	180	end
	end

      	playlist	762, 1, 'Liu Kang: flying kick #2'
	0	setvol	1, 98
	0	play	1, 'lkflyk2', 1
	209	end
	end

      	playlist	763, 2, 'Liu Kang: flying kick #2'
	0	setvol	2, 98
	0	play	2, 'lkflyk2', 1
	209	end
	end

      	playlist	764, 3, 'Liu Kang: flying kick #2'
	0	setvol	3, 98
	0	play	3, 'lkflyk2', 1
	209	end
	end

      	playlist	765, 1, 'Liu Kang: spiked'
	0	setvol	1, 98
	0	play	1, 'lkspiked', 1
	80	end
	end

      	playlist	766, 2, 'Liu Kang: spiked'
	0	setvol	2, 98
	0	play	2, 'lkspiked', 1
	80	end
	end

      	playlist	767, 3, 'Liu Kang: spiked'
	0	setvol	3, 98
	0	play	3, 'lkspiked', 1
	80	end
	end

      	playlist	768, 1, 'Liu Kang: throw #1'
	0	setvol	1, 98
	0	play	1, 'lkthrow1', 1
	103	end
	end

      	playlist	769, 2, 'Liu Kang: throw #1'
	0	setvol	2, 98
	0	play	2, 'lkthrow1', 1
	103	end
	end

      	playlist	770, 3, 'Liu Kang: throw #1'
	0	setvol	3, 98
	0	play	3, 'lkthrow1', 1
	103	end
	end

      	playlist	771, 1, 'Liu Kang: react 1'
	0	setvol	1, 98
	0	play	1, 'lkreact1', 1
	93	end
	end

      	playlist	772, 2, 'Liu Kang: react 1'
	0	setvol	2, 98
	0	play	2, 'lkreact1', 1
	93	end
	end

      	playlist	773, 3, 'Liu Kang: react 1'
	0	setvol	3, 98
	0	play	3, 'lkreact1', 1
	93	end
	end

      	playlist	774, 1, 'Liu Kang: react 2'
	0	setvol	1, 98
	0	play	1, 'lkreact2', 1
	59	end
	end

      	playlist	775, 2, 'Liu Kang: react 2'
	0	setvol	2, 98
	0	play	2, 'lkreact2', 1
	59	end
	end

      	playlist	776, 3, 'Liu Kang: react 2'
	0	setvol	3, 98
	0	play	3, 'lkreact2', 1
	59	end
	end

      	playlist	777, 1, 'Liu Kang: wast 1'
	0	setvol	1, 98
	0	play	1, 'lkwast1', 1
	201	end
	end

      	playlist	778, 2, 'Liu Kang: wast 1'
	0	setvol	2, 98
	0	play	2, 'lkwast1', 1
	201	end
	end

      	playlist	779, 3, 'Liu Kang: wast 1'
	0	setvol	3, 98
	0	play	3, 'lkwast1', 1
	201	end
	end

      	playlist	780, 1, 'Liu Kang: wast 2'
	0	setvol	1, 98
	0	play	1, 'lkwast2', 1
	218	end
	end

      	playlist	781, 2, 'Liu Kang: wast 2'
	0	setvol	2, 98
	0	play	2, 'lkwast2', 1
	218	end
	end

      	playlist	782, 3, 'Liu Kang: wast 2'
	0	setvol	3, 98
	0	play	3, 'lkwast2', 1
	218	end
	end

      	playlist	783, 1, 'Liu Kang: death'
	0	setvol	1, 98
	0	play	1, 'lkdeath', 1
	293	end
	end

      	playlist	784, 2, 'Liu Kang: death'
	0	setvol	2, 98
	0	play	2, 'lkdeath', 1
	293	end
	end

      	playlist	785, 3, 'Liu Kang: death'
	0	setvol	3, 98
	0	play	3, 'lkdeath', 1
	293	end
	end

      	playlist	786, 1, 'Liu Kang: jump'
	0	setvol	1, 98
	0	play	1, 'lkjump', 1
	47	end
	end

      	playlist	787, 2, 'Liu Kang: jump'
	0	setvol	2, 98
	0	play	2, 'lkjump', 1
	47	end
	end

      	playlist	788, 3, 'Liu Kang: jump'
	0	setvol	3, 98
	0	play	3, 'lkjump', 1
	47	end
	end

      	playlist	789, 1, 'Liu Kang: throw #2'
	0	setvol	1, 98
	0	play	1, 'lkthrow2', 1
	99	end
	end

      	playlist	790, 2, 'Liu Kang: throw #2'
	0	setvol	2, 98
	0	play	2, 'lkthrow2', 1
	99	end
	end

      	playlist	791, 3, 'Liu Kang: throw #2'
	0	setvol	3, 98
	0	play	3, 'lkthrow2', 1
	99	end
	end

      	playlist	800, 1, 'JH: gibberish #5'
	0	setvol	1, 104
	0	play	1, 'gib5', 1
	208	end
	end

      	playlist	801, 2, 'JH: gibberish #5'
	0	setvol	2, 104
	0	play	2, 'gib5', 1
	208	end
	end

      	playlist	802, 3, 'JH: gibberish #5'
	0	setvol	3, 104
	0	play	3, 'gib5', 1
	208	end
	end

      	playlist	803, 1, 'JH: hmmmm'
	0	setvol	1, 100
	0	play	1, 'jhfelch', 1
	388	end
	end

      	playlist	804, 2, 'JH: hmmmm'
	0	setvol	2, 100
	0	play	2, 'jhfelch', 1
	388	end
	end

      	playlist	805, 3, 'JH: hmmmm'
	0	setvol	3, 100
	0	play	3, 'jhfelch', 1
	388	end
	end

      	playlist	806, 1, 'Johnny Cage: victory kiss'
	0	setvol	1, 100
	0	play	1, 'cagekiss', 1
	137	end
	end

      	playlist	807, 2, 'Johnny Cage: victory kiss'
	0	setvol	2, 100
	0	play	2, 'cagekiss', 1
	137	end
	end

      	playlist	808, 3, 'Johnny Cage: victory kiss'
	0	setvol	3, 100
	0	play	3, 'cagekiss', 1
	137	end
	end

      	playlist	809, 1, 'Kid Thunder: Kid Thunder'
	0	setvol	1, 100
	0	play	1, 'kidthund', 1
	224	end
	end

      	playlist	810, 2, 'Kid Thunder: Kid Thunder'
	0	setvol	2, 100
	0	play	2, 'kidthund', 1
	224	end
	end

      	playlist	811, 3, 'Kid Thunder: Kid Thunder'
	0	setvol	3, 100
	0	play	3, 'kidthund', 1
	224	end
	end

      	playlist	812, 1, 'Jax: Aahhhh! (gotcha)'
	0	setvol	1, 105
	0	play	1, 'jaxahh', 1
	73	end
	end

      	playlist	813, 2, 'Jax: Aahhhh! (gotcha)'
	0	setvol	2, 105
	0	play	2, 'jaxahh', 1
	73	end
	end

      	playlist	814, 3, 'Jax: Aahhhh! (gotcha)'
	0	setvol	3, 105
	0	play	3, 'jaxahh', 1
	73	end
	end

      	playlist	815, 1, 'Jax: Gotcha'
	0	setvol	1, 105
	0	play	1, 'jaxgotch', 1
	86	end
	end

      	playlist	816, 2, 'Jax: Gotcha'
	0	setvol	2, 105
	0	play	2, 'jaxgotch', 1
	86	end
	end

      	playlist	817, 3, 'Jax: Gotcha'
	0	setvol	3, 105
	0	play	3, 'jaxgotch', 1
	86	end
	end

      	playlist	818, 1, 'Jax: Victory yeah'
	0	setvol	1, 105
	0	play	1, 'jaxyeah', 1
	280	end
	end

      	playlist	819, 2, 'Jax: Victory yeah'
	0	setvol	2, 105
	0	play	2, 'jaxyeah', 1
	280	end
	end

      	playlist	820, 3, 'Jax: Victory yeah'
	0	setvol	3, 105
	0	play	3, 'jaxyeah', 1
	280	end
	end

      	playlist	821, 1, 'DF: oh maw'
	0	setvol	1, 100
	0	play	1, 'ohmaw', 1
	96	end
	end

      	playlist	822, 2, 'DF: oh maw'
	0	setvol	2, 100
	0	play	2, 'ohmaw', 1
	96	end
	end

      	playlist	823, 3, 'DF: oh maw'
	0	setvol	3, 100
	0	play	3, 'ohmaw', 1
	96	end
	end

      	playlist	824, 1, 'Scorpion: Come Here!'
	0	setvol	1, 100
	0	play	1, 'scorcome', 1
	229	end
	end

      	playlist	825, 2, 'Scorpion: Come Here!'
	0	setvol	2, 100
	0	play	2, 'scorcome', 1
	229	end
	end

      	playlist	826, 3, 'Scorpion: Come Here!'
	0	setvol	3, 100
	0	play	3, 'scorcome', 1
	229	end
	end

      	playlist	827, 1, 'Scorpion: Get over here!'
	0	setvol	1, 100
	0	play	1, 'scorget', 1
	266	end
	end

      	playlist	828, 2, 'Scorpion: Get over here!'
	0	setvol	2, 100
	0	play	2, 'scorget', 1
	266	end
	end

      	playlist	829, 3, 'Scorpion: Get over here!'
	0	setvol	3, 100
	0	play	3, 'scorget', 1
	266	end
	end

      	playlist	830, 1, 'Trees: roar'
	0	setvol	1, 105
	0	play	1, 'treeroar', 1
	338	end
	end

      	playlist	831, 2, 'Trees: roar'
	0	setvol	2, 105
	0	play	2, 'treeroar', 1
	338	end
	end

      	playlist	832, 3, 'Trees: roar'
	0	setvol	3, 105
	0	play	3, 'treeroar', 1
	338	end
	end

      	playlist	836, 1, 'EB: fall down pit'
	0	setvol	1, 103
	0	play	1, 'ebpit', 1
	502	end
	end

      	playlist	837, 2, 'EB: fall down pit'
	0	setvol	2, 103
	0	play	2, 'ebpit', 1
	502	end
	end

      	playlist	838, 3, 'EB: fall down pit'
	0	setvol	3, 103
	0	play	3, 'ebpit', 1
	502	end
	end

      	playlist	839, 1, 'EB: hit bottom of pit'
	0	setvol	1, 103
	0	play	1, 'ebpithit', 1
	90	end
	end

      	playlist	840, 2, 'EB: hit bottom of pit'
	0	setvol	2, 103
	0	play	2, 'ebpithit', 1
	90	end
	end

      	playlist	841, 3, 'EB: hit bottom of pit'
	0	setvol	3, 103
	0	play	3, 'ebpithit', 1
	90	end
	end

      	playlist	842, 1, 'Kung Lao: flip throw'
	0	setvol	1, 110
	0	play	1, 'klflip', 1
	207	end
	end

      	playlist	843, 2, 'Kung Lao: flip throw'
	0	setvol	2, 110
	0	play	2, 'klflip', 1
	207	end
	end

      	playlist	844, 3, 'Kung Lao: flip throw'
	0	setvol	3, 110
	0	play	3, 'klflip', 1
	207	end
	end

      	playlist	850, 1, 'Vince: attack #1'
	0	setvol	1, 100
	0	play	1, 'vpattak1', 1
	63	end
	end

      	playlist	851, 2, 'Vince: attack #1'
	0	setvol	2, 100
	0	play	2, 'vpattak1', 1
	63	end
	end

      	playlist	852, 3, 'Vince: attack #1'
	0	setvol	3, 100
	0	play	3, 'vpattak1', 1
	63	end
	end

      	playlist	853, 1, 'Vince: attack #2'
	0	setvol	1, 100
	0	play	1, 'vpattak2', 1
	61	end
	end

      	playlist	854, 2, 'Vince: attack #2'
	0	setvol	2, 100
	0	play	2, 'vpattak2', 1
	61	end
	end

      	playlist	855, 3, 'Vince: attack #2'
	0	setvol	3, 100
	0	play	3, 'vpattak2', 1
	61	end
	end

      	playlist	856, 1, 'Vince: jump'
	0	setvol	1, 100
	0	play	1, 'vpjump', 1
	39	end
	end

      	playlist	857, 2, 'Vince: jump'
	0	setvol	2, 100
	0	play	2, 'vpjump', 1
	39	end
	end

      	playlist	858, 3, 'Vince: jump'
	0	setvol	3, 100
	0	play	3, 'vpjump', 1
	39	end
	end

      	playlist	859, 1, 'Vince: trip'
	0	setvol	1, 100
	0	play	1, 'vptrip', 1
	72	end
	end

      	playlist	860, 2, 'Vince: trip'
	0	setvol	2, 100
	0	play	2, 'vptrip', 1
	72	end
	end

      	playlist	861, 3, 'Vince: trip'
	0	setvol	3, 100
	0	play	3, 'vptrip', 1
	72	end
	end

      	playlist	862, 1, 'Vince: grab'
	0	setvol	1, 100
	0	play	1, 'vpgrab', 1
	64	end
	end

      	playlist	863, 2, 'Vince: grab'
	0	setvol	2, 100
	0	play	2, 'vpgrab', 1
	64	end
	end

      	playlist	864, 3, 'Vince: grab'
	0	setvol	3, 100
	0	play	3, 'vpgrab', 1
	64	end
	end

      	playlist	865, 1, 'Vince: throw'
	0	setvol	1, 100
	0	play	1, 'vpthrow', 1
	99	end
	end

      	playlist	866, 2, 'Vince: throw'
	0	setvol	2, 100
	0	play	2, 'vpthrow', 1
	99	end
	end

      	playlist	867, 3, 'Vince: throw'
	0	setvol	3, 100
	0	play	3, 'vpthrow', 1
	99	end
	end

      	playlist	868, 1, 'Vince: react #1'
	0	setvol	1, 100
	0	play	1, 'vpreact1', 1
	57	end
	end

      	playlist	869, 2, 'Vince: react #1'
	0	setvol	2, 100
	0	play	2, 'vpreact1', 1
	57	end
	end

      	playlist	870, 3, 'Vince: react #1'
	0	setvol	3, 100
	0	play	3, 'vpreact1', 1
	57	end
	end

      	playlist	871, 1, 'Vince: react #2'
	0	setvol	1, 100
	0	play	1, 'vpreact2', 1
	60	end
	end

      	playlist	872, 2, 'Vince: react #2'
	0	setvol	2, 100
	0	play	2, 'vpreact2', 1
	60	end
	end

      	playlist	873, 3, 'Vince: react #2'
	0	setvol	3, 100
	0	play	3, 'vpreact2', 1
	60	end
	end

      	playlist	874, 1, 'Vince: react #3'
	0	setvol	1, 100
	0	play	1, 'vpreact3', 1
	71	end
	end

      	playlist	875, 2, 'Vince: react #3'
	0	setvol	2, 100
	0	play	2, 'vpreact3', 1
	71	end
	end

      	playlist	876, 3, 'Vince: react #3'
	0	setvol	3, 100
	0	play	3, 'vpreact3', 1
	71	end
	end

      	playlist	877, 1, 'Vince: wast #1'
	0	setvol	1, 100
	0	play	1, 'vpwast1', 1
	105	end
	end

      	playlist	878, 2, 'Vince: wast #1'
	0	setvol	2, 100
	0	play	2, 'vpwast1', 1
	105	end
	end

      	playlist	879, 3, 'Vince: wast #1'
	0	setvol	3, 100
	0	play	3, 'vpwast1', 1
	105	end
	end

      	playlist	880, 1, 'Vince: wast #2'
	0	setvol	1, 100
	0	play	1, 'vpwast2', 1
	144	end
	end

      	playlist	881, 2, 'Vince: wast #2'
	0	setvol	2, 100
	0	play	2, 'vpwast2', 1
	144	end
	end

      	playlist	882, 3, 'Vince: wast #2'
	0	setvol	3, 100
	0	play	3, 'vpwast2', 1
	144	end
	end

      	playlist	883, 1, 'Vince: death'
	0	setvol	1, 100
	0	play	1, 'vpdeath', 1
	298	end
	end

      	playlist	884, 2, 'Vince: death'
	0	setvol	2, 100
	0	play	2, 'vpdeath', 1
	298	end
	end

      	playlist	885, 3, 'Vince: death'
	0	setvol	3, 100
	0	play	3, 'vpdeath', 1
	298	end
	end

      	playlist	886, 1, 'Shang Tsung: inside body noise'
	0	setvol	1, 110
	0	play	1, 'stgross1', 1
	196	end
	end

      	playlist	887, 2, 'Shang Tsung: inside body noise'
	0	setvol	2, 110
	0	play	2, 'stgross1', 1
	196	end
	end

      	playlist	888, 3, 'Shang Tsung: inside body noise'
	0	setvol	3, 110
	0	play	3, 'stgross1', 1
	196	end
	end

      	playlist	889, 1, 'Shang Tsung: green goo cloud'
	0	setvol	1, 110
	0	play	1, 'stcloud', 1
	205	end
	end

      	playlist	890, 2, 'Shang Tsung: green goo cloud'
	0	setvol	2, 110
	0	play	2, 'stcloud', 1
	205	end
	end

      	playlist	891, 3, 'Shang Tsung: green goo cloud'
	0	setvol	3, 110
	0	play	3, 'stcloud', 1
	205	end
	end

      	playlist	892, 1, 'Shang Tsung: cloud goes into hand'
	0	setvol	1, 80
	0	rampupvol	1, 80, 10
	0	play	1, 'stcldwn', 1
	135	end
	end

      	playlist	893, 2, 'Shang Tsung: cloud goes into hand'
	0	setvol	2, 80
	0	rampupvol	2, 80, 10
	0	play	2, 'stcldwn', 1
	135	end
	end

      	playlist	894, 3, 'Shang Tsung: cloud goes into hand'
	0	setvol	3, 80
	0	rampupvol	3, 80, 10
	0	play	3, 'stcldwn', 1
	135	end
	end

; **************************************************************************
; *                                                                        *
; *                         Narrator Boss                                  *
; *                                                                        *
; **************************************************************************

      	playlist	900, 1, 'Shao Kahn: Liu Kang wins'
	0	setvol	1, 117
	0	downvol	0, 15
	0	play	1, 'liukang', 1
	135	setvol	1, 112
	0	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	901, 2, 'Shao Kahn: Liu Kang wins'
	0	setvol	2, 117
	0	downvol	0, 15
	0	play	2, 'liukang', 1
	135	setvol	2, 112
	0	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	902, 3, 'Shao Kahn: Liu Kang wins'
	0	setvol	3, 117
	0	downvol	0, 15
	0	play	3, 'liukang', 1
	135	setvol	3, 112
	0	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	903, 1, 'Shao Kahn: Kung Lao wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'kunglao', 1
	145	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	904, 2, 'Shao Kahn: Kung Lao wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'kunglao', 1
	145	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	905, 3, 'Shao Kahn: Kung Lao wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'kunglao', 1
	145	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	906, 1, 'Shao Kahn: Johnny Cage wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'joncage', 1
	173	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	907, 2, 'Shao Kahn: Johnny Cage wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'joncage', 1
	173	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	908, 3, 'Shao Kahn: Johnny Cage wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'joncage', 1
	173	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	909, 1, 'Shao Kahn: Reptile wins'
	0	setvol	1, 117
	0	downvol	0, 15
	0	play	1, 'reptile', 1
	128	setvol	1, 112
	0	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	910, 2, 'Shao Kahn: Reptile wins'
	0	setvol	2, 117
	0	downvol	0, 15
	0	play	2, 'reptile', 1
	128	setvol	2, 112
	0	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	911, 3, 'Shao Kahn: Reptile wins'
	0	setvol	3, 117
	0	downvol	0, 15
	0	play	3, 'reptile', 1
	128	setvol	3, 112
	0	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	912, 1, 'Shao Kahn: Sub-Zero wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'subzero', 1
	151	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	913, 2, 'Shao Kahn: Sub-Zero wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'subzero', 1
	151	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	914, 3, 'Shao Kahn: Sub-Zero wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'subzero', 1
	151	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	915, 1, 'Shao Kahn: Shang Tsung wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'shangtsg', 1
	172	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	916, 2, 'Shao Kahn: Shang Tsung wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'shangtsg', 1
	172	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	917, 3, 'Shao Kahn: Shang Tsung wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'shangtsg', 1
	172	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	918, 1, 'Shao Kahn: Kitana wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'kitana', 1
	117	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	919, 2, 'Shao Kahn: Kitana wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'kitana', 1
	117	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	920, 3, 'Shao Kahn: Kitana wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'kitana', 1
	117	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	921, 1, 'Shao Kahn: Jax wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'jax', 1
	127	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	922, 2, 'Shao Kahn: Jax wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'jax', 1
	127	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	923, 3, 'Shao Kahn: Jax wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'jax', 1
	127	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	924, 1, 'Shao Kahn: Malena wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'malena', 1
	129	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	925, 2, 'Shao Kahn: Malena wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'malena', 1
	129	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	926, 3, 'Shao Kahn: Malena wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'malena', 1
	129	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	927, 1, 'Shao Kahn: Baraka wins'
	0	setvol	1, 117
	0	downvol	0, 15
	0	play	1, 'baraka', 1
	140	setvol	1, 112
	0	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	928, 2, 'Shao Kahn: Baraka wins'
	0	setvol	2, 117
	0	downvol	0, 15
	0	play	2, 'baraka', 1
	140	setvol	2, 112
	0	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	929, 3, 'Shao Kahn: Baraka wins'
	0	setvol	3, 117
	0	downvol	0, 15
	0	play	3, 'baraka', 1
	140	setvol	3, 112
	0	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	930, 1, 'Shao Kahn: Scorpion wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'scorpion', 1
	155	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	931, 2, 'Shao Kahn: Scorpion wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'scorpion', 1
	155	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	932, 3, 'Shao Kahn: Scorpion wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'scorpion', 1
	155	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	933, 1, 'Shao Kahn: Raiden wins'
	0	setvol	1, 117
	0	downvol	0, 15
	0	play	1, 'raiden', 1
	116	setvol	1, 112
	0	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	934, 2, 'Shao Kahn: Raiden wins'
	0	setvol	2, 117
	0	downvol	0, 15
	0	play	2, 'raiden', 1
	116	setvol	2, 112
	0	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	935, 3, 'Shao Kahn: Raiden wins'
	0	setvol	3, 117
	0	downvol	0, 15
	0	play	3, 'raiden', 1
	116	setvol	3, 112
	0	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	936, 1, 'Shao Kahn: Smoke wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'smoke', 1
	119	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	937, 2, 'Shao Kahn: Smoke wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'smoke', 1
	119	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	938, 3, 'Shao Kahn: Smoke wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'smoke', 1
	119	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	939, 1, 'Shao Kahn: Jade wins'
	0	setvol	1, 112
	0	downvol	0, 15
	0	play	1, 'jade', 1
	119	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	940, 2, 'Shao Kahn: Jade wins'
	0	setvol	2, 112
	0	downvol	0, 15
	0	play	2, 'jade', 1
	119	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	941, 3, 'Shao Kahn: Jade wins'
	0	setvol	3, 112
	0	downvol	0, 15
	0	play	3, 'jade', 1
	119	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	942, 1, 'Shao Kahn: Finish Him!'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'finishim', 1
	150	rampupvol	0, 15, 20
	48	end
	end

      	playlist	943, 2, 'Shao Kahn: Finish Him!'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'finishim', 1
	150	rampupvol	0, 15, 20
	48	end
	end

      	playlist	944, 3, 'Shao Kahn: Finish Him!'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'finishim', 1
	150	rampupvol	0, 15, 20
	48	end
	end

      	playlist	945, 1, 'Shao Kahn: Finish Her!'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'finisher', 1
	120	rampupvol	0, 15, 20
	43	end
	end

      	playlist	946, 2, 'Shao Kahn: Finish Her!'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'finisher', 1
	120	rampupvol	0, 15, 20
	43	end
	end

      	playlist	947, 3, 'Shao Kahn: Finish Her!'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'finisher', 1
	120	rampupvol	0, 15, 20
	43	end
	end

      	playlist	948, 1, 'Shao Kahn: Fatality'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'fatality', 1
	140	rampupvol	0, 15, 20
	44	end
	end

      	playlist	949, 2, 'Shao Kahn: Fatality'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'fatality', 1
	140	rampupvol	0, 15, 20
	44	end
	end

      	playlist	950, 3, 'Shao Kahn: Fatality'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'fatality', 1
	140	rampupvol	0, 15, 20
	44	end
	end

      	playlist	951, 1, 'Shao Kahn: Flawless Victory'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'flawless', 1
	190	rampupvol	0, 15, 20
	46	end
	end

      	playlist	952, 2, 'Shao Kahn: Flawless Victory'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'flawless', 1
	190	rampupvol	0, 15, 20
	46	end
	end

      	playlist	953, 3, 'Shao Kahn: Flawless Victory'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'flawless', 1
	190	rampupvol	0, 15, 20
	46	end
	end

      	playlist	954, 1, 'Shao Kahn: Excellent!'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'excelent', 1
	50	rampupvol	0, 20, 40
	68	end
	end

      	playlist	955, 2, 'Shao Kahn: Excellent!'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'excelent', 1
	50	rampupvol	0, 20, 40
	68	end
	end

      	playlist	956, 3, 'Shao Kahn: Excellent!'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'excelent', 1
	50	rampupvol	0, 20, 40
	68	end
	end

      	playlist	957, 1, 'Shao Kahn: Kintaro wins'
	0	setvol	1, 110
	0	downvol	0, 15
	0	play	1, 'kintaro', 1
	135	play	1, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	958, 2, 'Shao Kahn: Kintaro wins'
	0	setvol	2, 110
	0	downvol	0, 15
	0	play	2, 'kintaro', 1
	135	play	2, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	959, 3, 'Shao Kahn: Kintaro wins'
	0	setvol	3, 110
	0	downvol	0, 15
	0	play	3, 'kintaro', 1
	135	play	3, 'wins1', 1
	100	rampupvol	0, 15, 20
	44	end
	end

      	playlist	960, 1, 'Shao Kahn: Outstanding!'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'outstand', 1
	130	rampupvol	0, 15, 20
	43	end
	end

      	playlist	961, 2, 'Shao Kahn: Outstanding!'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'outstand', 1
	130	rampupvol	0, 15, 20
	43	end
	end

      	playlist	962, 3, 'Shao Kahn: Outstanding!'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'outstand', 1
	130	rampupvol	0, 15, 20
	43	end
	end

      	playlist	963, 1, 'Shao Kahn: Well done'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'welldone', 1
	110	rampupvol	0, 15, 20
	45	end
	end

      	playlist	964, 2, 'Shao Kahn: Well done'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'welldone', 1
	110	rampupvol	0, 15, 20
	45	end
	end

      	playlist	965, 3, 'Shao Kahn: Well done'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'welldone', 1
	110	rampupvol	0, 15, 20
	45	end
	end

      	playlist	966, 1, 'Shao Kahn: Superb'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'superb', 1
	130	rampupvol	0, 15, 20
	44	end
	end

      	playlist	967, 2, 'Shao Kahn: Superb'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'superb', 1
	130	rampupvol	0, 15, 20
	44	end
	end

      	playlist	968, 3, 'Shao Kahn: Superb'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'superb', 1
	130	rampupvol	0, 15, 20
	44	end
	end

      	playlist	969, 1, 'Shao Kahn: Babality'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'babality', 1
	130	rampupvol	0, 15, 20
	41	end
	end

      	playlist	970, 2, 'Shao Kahn: Babality'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'babality', 1
	130	rampupvol	0, 15, 20
	41	end
	end

      	playlist	971, 3, 'Shao Kahn: Babality'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'babality', 1
	130	rampupvol	0, 15, 20
	41	end
	end

      	playlist	972, 1, 'Shao Kahn: Fight! (#1)'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'fight1', 1
	100	rampupvol	0, 15, 20
	46	end
	end

      	playlist	973, 2, 'Shao Kahn: Fight! (#1)'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'fight1', 1
	100	rampupvol	0, 15, 20
	46	end
	end

      	playlist	974, 3, 'Shao Kahn: Fight! (#1)'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'fight1', 1
	100	rampupvol	0, 15, 20
	46	end
	end

      	playlist	975, 1, 'Shao Kahn: Friendship (#1)'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'friend1', 1
	120	rampupvol	0, 15, 20
	46	end
	end

      	playlist	976, 2, 'Shao Kahn: Friendship (#1)'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'friend1', 1
	120	rampupvol	0, 15, 20
	46	end
	end

      	playlist	977, 3, 'Shao Kahn: Friendship (#1)'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'friend1', 1
	120	rampupvol	0, 15, 20
	46	end
	end

      	playlist	980, 1, 'Male Slippery when frozen #1'
	0	setvol	1, 95
	0	play	1, 'sliped1', 1
	56	play	1, 'sliped2', 1
	57	play	1, 'sliped3', 1
	67	play	1, 'sliped4', 1
	83	play	1, 'sliped5', 1
	96	play	1, 'sliped6', 1
	70	end
	end

      	playlist	981, 2, 'Male Slippery when frozen #1'
	0	setvol	2, 95
	0	play	2, 'sliped1', 1
	56	play	2, 'sliped2', 1
	57	play	2, 'sliped3', 1
	67	play	2, 'sliped4', 1
	83	play	2, 'sliped5', 1
	96	play	2, 'sliped6', 1
	70	end
	end

      	playlist	982, 3, 'Male Slippery when frozen #1'
	0	setvol	3, 95
	0	play	3, 'sliped1', 1
	56	play	3, 'sliped2', 1
	57	play	3, 'sliped3', 1
	67	play	3, 'sliped4', 1
	83	play	3, 'sliped5', 1
	96	play	3, 'sliped6', 1
	70	end
	end

      	playlist	983, 1, 'Male Slippery when frozen #2'
	0	setvol	1, 95
	0	play	1, 'sliped4', 1
	83	play	1, 'sliped5', 1
	96	play	1, 'sliped6', 1
	70	play	1, 'slipbig', 1
	236	end
	end

      	playlist	984, 2, 'Male Slippery when frozen #2'
	0	setvol	2, 95
	0	play	2, 'sliped4', 1
	83	play	2, 'sliped5', 1
	96	play	2, 'sliped6', 1
	70	play	2, 'slipbig', 1
	236	end
	end

      	playlist	985, 3, 'Male Slippery when frozen #2'
	0	setvol	3, 95
	0	play	3, 'sliped4', 1
	83	play	3, 'sliped5', 1
	96	play	3, 'sliped6', 1
	70	play	3, 'slipbig', 1
	236	end
	end

      	playlist	986, 1, 'Male Slippery when frozen #3'
	0	setvol	1, 95
	0	play	1, 'slipdan1', 1
	46	play	1, 'slipdan2', 1
	48	play	1, 'slipdan3', 1
	49	play	1, 'slipdan4', 1
	42	end
	end

      	playlist	987, 2, 'Male Slippery when frozen #3'
	0	setvol	2, 95
	0	play	2, 'slipdan1', 1
	46	play	2, 'slipdan2', 1
	48	play	2, 'slipdan3', 1
	49	play	2, 'slipdan4', 1
	42	end
	end

      	playlist	988, 3, 'Male Slippery when frozen #3'
	0	setvol	3, 95
	0	play	3, 'slipdan1', 1
	46	play	3, 'slipdan2', 1
	48	play	3, 'slipdan3', 1
	49	play	3, 'slipdan4', 1
	42	end
	end

; **************************************************************************
; *                                                                        *
; * Diagnostics live in the same place as in the 6809/Yamaha system.       *
; *                                                                        *
; **************************************************************************

; **************************************************************************
; *                                                                        *
; *                         Utilities                                      *
; *                                                                        *
; **************************************************************************

	playlist	995, 0, 'SYSTEM          Kill sound on track 0'
	0	end
	end

	playlist	996, 1, 'SYSTEM          Kill sound on track 1'
	0	end
	end
	
	playlist	997, 2, 'SYSTEM          Kill sound on track 2'
	0	end
	end

	playlist	998, 3, 'SYSTEM          Kill sound on track 3'
	0	end
	end


	playlist	999, 0, 'SYSTEM      send version # as a signal'
;	sound level 1 set up 11-12-93 dwf
	0	signal	0x01	
	5	end
	end

; **************************************************************************
; *                                                                        *
; *                         Death Blow Stuff                               *
; *                                                                        *
; **************************************************************************

      	playlist	1000, 1, 'Death: Cage - Rip in half [1 2]'
	0	setvol	1, 110
	0	setvol	2, 110
	0	play	1, 'crunch1', 1
	0	play	2, 'crunch2', 1
	84	end
	end

      	playlist	1001, 1, 'Death: Jax - Clap yer head off [1 2]'
	0	downvol	0, 40
	0	setvol	1, 110
	0	setvol	2, 110
	0	play	1, 'bodyxpld', 1
	0	play	2, 'bigstab2', 1
	50	rampdownvol	1, 110, 50
	0	rampupvol	0, 40, 50
	90	rampdownvol	2, 110, 10
	10	end
	end

      	playlist	1020, 1, 'Death: Kitana - Kiss #1'
	0	setvol	1, 105
	0	play	1, 'kiss', 1
	57	end
	end

      	playlist	1021, 2, 'Death: Kitana - Kiss #1'
	0	setvol	2, 105
	0	play	2, 'kiss', 1
	57	end
	end

      	playlist	1022, 3, 'Death: Kitana - Kiss #1'
	0	setvol	3, 105
	0	play	3, 'kiss', 1
	57	end
	end

      	playlist	1023, 1, 'Death: Kitana - Kiss #2'
	0	setvol	1, 70
	0	play	1, 'kiss2', 1
	111	end
	end

      	playlist	1024, 2, 'Death: Kitana - Kiss #2'
	0	setvol	2, 70
	0	play	2, 'kiss2', 1
	111	end
	end

      	playlist	1025, 3, 'Death: Kitana - Kiss #2'
	0	setvol	3, 70
	0	play	3, 'kiss2', 1
	111	end
	end

      	playlist	1026, 1, 'Death: Kitana - Body inflates'
	0	setvol	1, 110
	0	play	1, 'bodinflt', 1
	110	end
	end

      	playlist	1027, 2, 'Death: Kitana - Body inflates'
	0	setvol	2, 110
	0	play	2, 'bodinflt', 1
	110	end
	end

      	playlist	1028, 3, 'Death: Kitana - Body inflates'
	0	setvol	3, 110
	0	play	3, 'bodinflt', 1
	110	end
	end

      	playlist	1029, 1, 'Death: Kitana - Body rumbles/shakes'
	0	setvol	1, 95
	0	play	1, 'bodrumbl', 1
	0	rampupvol	1, 15, 160
	321	end
	end

      	playlist	1030, 2, 'Death: Kitana - Body rumbles/shakes'
	0	setvol	2, 95
	0	play	2, 'bodrumbl', 1
	0	rampupvol	2, 15, 160
	321	end
	end

      	playlist	1031, 3, 'Death: Kitana - Body rumbles/shakes'
	0	setvol	3, 95
	0	play	3, 'bodrumbl', 1
	0	rampupvol	3, 15, 160
	321	end
	end

      	playlist	1032, 1, 'Death: Kitana - male about to explode'
	0	setvol	1, 100
	0	play	1, 'boutxpld', 1
	165	end
	end

      	playlist	1033, 2, 'Death: Kitana - male about to explode'
	0	setvol	2, 100
	0	play	2, 'boutxpld', 1
	165	end
	end

      	playlist	1034, 3, 'Death: Kitana - male about to explode'
	0	setvol	3, 100
	0	play	3, 'boutxpld', 1
	165	end
	end

      	playlist	1035, 1, 'Death: Kitana - victum explodes'
	0	downvol	0, 50
	0	setvol	1, 115
	0	play	1, 'bodyxpld', 1
	200	rampupvol	0, 50, 134
	134	end
	end

      	playlist	1036, 2, 'Death: Kitana - victum explodes'
	0	downvol	0, 50
	0	setvol	2, 115
	0	play	2, 'bodyxpld', 1
	200	rampupvol	0, 50, 134
	134	end
	end

      	playlist	1037, 3, 'Death: Kitana - victum explodes'
	0	downvol	0, 50
	0	setvol	3, 115
	0	play	3, 'bodyxpld', 1
	200	rampupvol	0, 50, 134
	134	end
	end

      	playlist	1038, 1, 'Death: Reptile - ''Yum!'''
	0	setvol	1, 100
	0	play	1, 'jhyum', 1
	83	end
	end

      	playlist	1039, 2, 'Death: Reptile - ''Yum!'''
	0	setvol	2, 100
	0	play	2, 'jhyum', 1
	83	end
	end

      	playlist	1040, 3, 'Death: Reptile - ''Yum!'''
	0	setvol	3, 100
	0	play	3, 'jhyum', 1
	83	end
	end

      	playlist	1041, 1, 'Death: Reptile - tongue sticks'
	0	setvol	1, 110
	0	play	1, 'tnguestk', 1
	32	end
	end

      	playlist	1042, 2, 'Death: Reptile - tongue sticks'
	0	setvol	2, 110
	0	play	2, 'tnguestk', 1
	32	end
	end

      	playlist	1043, 3, 'Death: Reptile - tongue sticks'
	0	setvol	3, 110
	0	play	3, 'tnguestk', 1
	32	end
	end

      	playlist	1044, 1, 'Death: Reptile - tongue whip'
	0	setvol	1, 110
	0	play	1, 'rtongue', 1
	76	end
	end

      	playlist	1045, 2, 'Death: Reptile - tongue whip'
	0	setvol	2, 110
	0	play	2, 'rtongue', 1
	76	end
	end

      	playlist	1046, 3, 'Death: Reptile - tongue whip'
	0	setvol	3, 110
	0	play	3, 'rtongue', 1
	76	end
	end

      	playlist	1047, 1, 'Death: hat cuts in two'
	0	setvol	1, 110
	0	play	1, 'hhsawcut', 1
	120	end
	end

      	playlist	1048, 2, 'Death: hat cuts in two'
	0	setvol	2, 110
	0	play	2, 'hhsawcut', 1
	120	end
	end

      	playlist	1049, 3, 'Death: hat cuts in two'
	0	setvol	3, 110
	0	play	3, 'hhsawcut', 1
	120	end
	end

      	playlist	1050, 1, 'Slipping on ice #1'
	0	setvol	1, 105
	0	play	1, 'slip1', 1
	39	end
	end

      	playlist	1051, 2, 'Slipping on ice #1'
	0	setvol	2, 105
	0	play	2, 'slip1', 1
	39	end
	end

      	playlist	1052, 3, 'Slipping on ice #1'
	0	setvol	3, 105
	0	play	3, 'slip1', 1
	39	end
	end

      	playlist	1053, 1, 'Slipping on ice #2'
	0	setvol	1, 105
	0	play	1, 'slip2', 1
	40	end
	end

      	playlist	1054, 2, 'Slipping on ice #2'
	0	setvol	2, 105
	0	play	2, 'slip2', 1
	40	end
	end

      	playlist	1055, 3, 'Slipping on ice #2'
	0	setvol	3, 105
	0	play	3, 'slip2', 1
	40	end
	end

      	playlist	1056, 1, 'Slipping on ice #3'
	0	setvol	1, 105
	0	play	1, 'slip3', 1
	47	end
	end

      	playlist	1057, 2, 'Slipping on ice #3'
	0	setvol	2, 105
	0	play	2, 'slip3', 1
	47	end
	end

      	playlist	1058, 3, 'Slipping on ice #3'
	0	setvol	3, 105
	0	play	3, 'slip3', 1
	47	end
	end

      	playlist	1059, 1, 'Slipping on ice #4'
	0	setvol	1, 105
	0	play	1, 'slip4', 1
	58	end
	end

      	playlist	1060, 2, 'Slipping on ice #4'
	0	setvol	2, 105
	0	play	2, 'slip4', 1
	58	end
	end

      	playlist	1061, 3, 'Slipping on ice #4'
	0	setvol	3, 105
	0	play	3, 'slip4', 1
	58	end
	end

      	playlist	1062, 1, 'Jax projectile'
	0	setvol	1, 105
	0	play	1, 'jaxproj', 1
	191	end
	end

      	playlist	1063, 2, 'Jax projectile'
	0	setvol	2, 105
	0	play	2, 'jaxproj', 1
	191	end
	end

      	playlist	1064, 3, 'Jax projectile'
	0	setvol	3, 105
	0	play	3, 'jaxproj', 1
	191	end
	end

      	playlist	1065, 1, 'Mileena spinning ball'
	0	setvol	1, 105
	0	play	1, 'mileball', 1
	159	end
	end

      	playlist	1066, 2, 'Mileena spinning ball'
	0	setvol	2, 105
	0	play	2, 'mileball', 1
	159	end
	end

      	playlist	1067, 3, 'Mileena spinning ball'
	0	setvol	3, 105
	0	play	3, 'mileball', 1
	159	end
	end

      	playlist	1068, 1, 'Reptile flying move'
	0	setvol	1, 85
	0	play	1, 'repfly', 1
	106	end
	end

      	playlist	1069, 2, 'Reptile flying move'
	0	setvol	2, 85
	0	play	2, 'repfly', 1
	106	end
	end

      	playlist	1070, 3, 'Reptile flying move'
	0	setvol	3, 85
	0	play	3, 'repfly', 1
	106	end
	end

; **************************************************************************
; *                                                                        *
; *                         More Narrator Stuff                            *
; *                                                                        *
; **************************************************************************

      	playlist	1100, 1, 'Shao Kahn: Friendship (#2)'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'friend2', 1
	120	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1101, 2, 'Shao Kahn: Friendship (#2)'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'friend2', 1
	120	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1102, 3, 'Shao Kahn: Friendship (#2)'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'friend2', 1
	120	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1103, 1, 'Shao Kahn: Round One'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'round', 1
	90	play	1, 'rone', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1104, 2, 'Shao Kahn: Round One'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'round', 1
	90	play	2, 'rone', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1105, 3, 'Shao Kahn: Round One'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'round', 1
	90	play	3, 'rone', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1106, 1, 'Shao Kahn: Round Two'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'round', 1
	100	play	1, 'rtwo', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1107, 2, 'Shao Kahn: Round Two'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'round', 1
	100	play	2, 'rtwo', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1108, 3, 'Shao Kahn: Round Two'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'round', 1
	100	play	3, 'rtwo', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1109, 1, 'Shao Kahn: Round Three'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'round', 1
	90	play	1, 'rthree', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1110, 2, 'Shao Kahn: Round Three'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'round', 1
	90	play	2, 'rthree', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1111, 3, 'Shao Kahn: Round Three'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'round', 1
	90	play	3, 'rthree', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1112, 1, 'Shao Kahn: Round Four'
	0	setvol	1, 105
	0	downvol	0, 15
	0	play	1, 'round', 1
	90	play	1, 'rfour', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1113, 2, 'Shao Kahn: Round Four'
	0	setvol	2, 105
	0	downvol	0, 15
	0	play	2, 'round', 1
	90	play	2, 'rfour', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1114, 3, 'Shao Kahn: Round Four'
	0	setvol	3, 105
	0	downvol	0, 15
	0	play	3, 'round', 1
	90	play	3, 'rfour', 1
	70	rampupvol	0, 15, 20
	46	end
	end

      	playlist	1115, 1, 'Shao Kahn: Liu Kang'
	0	setvol	1, 115
	0	downvol	0, 15
	0	play	1, 'liukang', 1
	100	rampupvol	0, 15, 20
	36	end
	end

      	playlist	1116, 2, 'Shao Kahn: Liu Kang'
	0	setvol	2, 115
	0	downvol	0, 15
	0	play	2, 'liukang', 1
	100	rampupvol	0, 15, 20
	36	end
	end

      	playlist	1117, 3, 'Shao Kahn: Liu Kang'
	0	setvol	3, 115
	0	downvol	0, 15
	0	play	3, 'liukang', 1
	100	rampupvol	0, 15, 20
	36	end
	end

      	playlist	1118, 1, 'Shao Kahn: Kung Lao'
	0	setvol	1, 110
	0	downvol	0, 15
	0	play	1, 'kunglao', 1
	110	rampupvol	0, 15, 20
	35	end
	end

      	playlist	1119, 2, 'Shao Kahn: Kung Lao'
	0	setvol	2, 110
	0	downvol	0, 15
	0	play	2, 'kunglao', 1
	110	rampupvol	0, 15, 20
	35	end
	end

      	playlist	1120, 3, 'Shao Kahn: Kung Lao'
	0	setvol	3, 110
	0	downvol	0, 15
	0	play	3, 'kunglao', 1
	110	rampupvol	0, 15, 20
	35	end
	end

      	playlist	1121, 1, 'Shao Kahn: Johnny Cage'
	0	setvol	1, 110
	0	downvol	0, 15
	0	play	1, 'joncage', 1
	140	rampupvol	0, 15, 20
	33	end
	end

      	playlist	1122, 2, 'Shao Kahn: Johnny Cage'
	0	setvol	2, 110
	0	downvol	0, 15
	0	play	2, 'joncage', 1
	140	rampupvol	0, 15, 20
	33	end
	end

      	playlist	1123, 3, 'Shao Kahn: Johnny Cage'
	0	setvol	3, 110
	0	downvol	0, 15
	0	play	3, 'joncage', 1
	140	rampupvol	0, 15, 20
	33	end
	end

      	playlist	1124, 1, 'Shao Kahn: Reptile'
	0	setvol	1, 115
	0	downvol	0, 15
	0	play	1, 'reptile', 1
	90	rampupvol	0, 15, 20
	38	end
	end

      	playlist	1125, 2, 'Shao Kahn: Reptile'
	0	setvol	2, 115
	0	downvol	0, 15
	0	play	2, 'reptile', 1
	90	rampupvol	0, 15, 20
	38	end
	end

      	playlist	1126, 3, 'Shao Kahn: Reptile'
	0	setvol	3, 115
	0	downvol	0, 15
	0	play	3, 'reptile', 1
	90	rampupvol	0, 15, 20
	38	end
	end

      	playlist	1127, 1, 'Shao Kahn: Sub-Zero'
	0	setvol	1, 110
	0	downvol	0, 15
	0	play	1, 'subzero', 1
	120	rampupvol	0, 15, 20
	31	end
	end

      	playlist	1128, 2, 'Shao Kahn: Sub-Zero'
	0	setvol	2, 110
	0	downvol	0, 15
	0	play	2, 'subzero', 1
	120	rampupvol	0, 15, 20
	31	end
	end

      	playlist	1129, 3, 'Shao Kahn: Sub-Zero'
	0	setvol	3, 110
	0	downvol	0, 15
	0	play	3, 'subzero', 1
	120	rampupvol	0, 15, 20
	31	end
	end

      	playlist	1130, 1, 'Shao Kahn: Shang-Tsung'
	0	setvol	1, 110
	0	downvol	0, 15
	0	play	1, 'shangtsg', 1
	140	rampupvol	0, 15, 20
	32	end
	end

      	playlist	1131, 2, 'Shao Kahn: Shang-Tsung'
	0	setvol	2, 110
	0	downvol	0, 15
	0	play	2, 'shangtsg', 1
	140	rampupvol	0, 15, 20
	32	end
	end

      	playlist	1132, 3, 'Shao Kahn: Shang-Tsung'
	0	setvol	3, 110
	0	downvol	0, 15
	0	play	3, 'shangtsg', 1
	140	rampupvol	0, 15, 20
	32	end
	end

      	playlist	1133, 1, 'Shao Kahn: Kitana'
	0	setvol	1, 110
	0	downvol	0, 15
	0	play	1, 'kitana', 1
	80	rampupvol	0, 15, 20
	37	end
	end

      	playlist	1134, 2, 'Shao Kahn: Kitana'
	0	setvol	2, 110
	0	downvol	0, 15
	0	play	2, 'kitana', 1
	80	rampupvol	0, 15, 20
	37	end
	end

      	playlist	1135, 3, 'Shao Kahn: Kitana'
	0	setvol	3, 110
	0	downvol	0, 15
	0	play	3, 'kitana', 1
	80	rampupvol	0, 15, 20
	37	end
	end

      	playlist	1136, 1, 'Shao Kahn: Jax'
	0	setvol	1, 110
	0	downvol	0, 15
	0	play	1, 'jax', 1
	90	rampupvol	0, 15, 20
	37	end
	end

      	playlist	1137, 2, 'Shao Kahn: Jax'
	0	setvol	2, 110
	0	downvol	0, 15
	0	play	2, 'jax', 1
	90	rampupvol	0, 15, 20
	37	end
	end

      	playlist	1138, 3, 'Shao Kahn: Jax'
	0	setvol	3, 110
	0	downvol	0, 15
	0	play	3, 'jax', 1
	90	rampupvol	0, 15, 20
	37	end
	end

      	playlist	1139, 1, 'Shao Kahn: Malena'
	0	setvol	1, 110
	0	downvol	0, 15
	0	play	1, 'malena', 1
	90	rampupvol	0, 15, 20
	39	end
	end

      	playlist	1140, 2, 'Shao Kahn: Malena'
	0	setvol	2, 110
	0	downvol	0, 15
	0	play	2, 'malena', 1
	90	rampupvol	0, 15, 20
	39	end
	end

      	playlist	1141, 3, 'Shao Kahn: Malena'
	0	setvol	3, 110
	0	downvol	0, 15
	0	play	3, 'malena', 1
	90	rampupvol	0, 15, 20
	39	end
	end

      	playlist	1142, 1, 'Shao Kahn: Baraka'
	0	setvol	1, 115
	0	downvol	0, 15
	0	play	1, 'baraka', 1
	110	rampupvol	0, 15, 20
	30	end
	end

      	playlist	1143, 2, 'Shao Kahn: Baraka'
	0	setvol	2, 115
	0	downvol	0, 15
	0	play	2, 'baraka', 1
	110	rampupvol	0, 15, 20
	30	end
	end

      	playlist	1144, 3, 'Shao Kahn: Baraka'
	0	setvol	3, 115
	0	downvol	0, 15
	0	play	3, 'baraka', 1
	110	rampupvol	0, 15, 20
	30	end
	end

      	playlist	1145, 1, 'Shao Kahn: Scorpion'
	0	setvol	1, 110
	0	downvol	0, 15
	0	play	1, 'scorpion', 1
	110	rampupvol	0, 15, 20
	30	end
	end

      	playlist	1146, 2, 'Shao Kahn: Scorpion'
	0	setvol	2, 110
	0	downvol	0, 15
	0	play	2, 'scorpion', 1
	110	rampupvol	0, 15, 20
	30	end
	end

      	playlist	1147, 3, 'Shao Kahn: Scorpion'
	0	setvol	3, 110
	0	downvol	0, 15
	0	play	3, 'scorpion', 1
	110	rampupvol	0, 15, 20
	30	end
	end

      	playlist	1148, 1, 'Shao Kahn: Raiden'
	0	setvol	1, 115
	0	downvol	0, 15
	0	play	1, 'raiden', 1
	80	rampupvol	0, 15, 20
	36	end
	end

      	playlist	1149, 2, 'Shao Kahn: Raiden'
	0	setvol	2, 115
	0	downvol	0, 15
	0	play	2, 'raiden', 1
	80	rampupvol	0, 15, 20
	36	end
	end

      	playlist	1150, 3, 'Shao Kahn: Raiden'
	0	setvol	3, 115
	0	downvol	0, 15
	0	play	3, 'raiden', 1
	80	rampupvol	0, 15, 20
	36	end
	end

      	playlist	1151, 1, 'Shao Kahn: I''m SK, bow to me'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'skimsk', 1
	245	play	1, 'skbow2me', 1
	179	upvol	0, 20
	25	end
	end

      	playlist	1152, 2, 'Shao Kahn: I''m SK, bow to me'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'skimsk', 1
	245	play	2, 'skbow2me', 1
	179	upvol	0, 20
	25	end
	end

      	playlist	1153, 3, 'Shao Kahn: I''m SK, bow to me'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'skimsk', 1
	245	play	3, 'skbow2me', 1
	179	upvol	0, 20
	25	end
	end

      	playlist	1154, 1, 'Shao Kahn: Feel the wrath ...'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'skfeelwr', 1
	317	upvol	0, 20
	30	end
	end

      	playlist	1155, 2, 'Shao Kahn: Feel the wrath ...'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'skfeelwr', 1
	317	upvol	0, 20
	30	end
	end

      	playlist	1156, 3, 'Shao Kahn: Feel the wrath ...'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'skfeelwr', 1
	317	upvol	0, 20
	30	end
	end

      	playlist	1157, 1, 'Shao Kahn: Feel the power ...'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'skfeelpr', 1
	298	upvol	0, 20
	30	end
	end

      	playlist	1158, 2, 'Shao Kahn: Feel the power ...'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'skfeelpr', 1
	298	upvol	0, 20
	30	end
	end

      	playlist	1159, 3, 'Shao Kahn: Feel the power ...'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'skfeelpr', 1
	298	upvol	0, 20
	30	end
	end

      	playlist	1160, 1, 'Shao Kahn: I rule ...'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'skirule', 1
	250	upvol	0, 20
	36	end
	end

      	playlist	1161, 2, 'Shao Kahn: I rule ...'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'skirule', 1
	250	upvol	0, 20
	36	end
	end

      	playlist	1162, 3, 'Shao Kahn: I rule ...'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'skirule', 1
	250	upvol	0, 20
	36	end
	end

      	playlist	1166, 1, 'Shao Kahn: Prepare to die'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'skprepdi', 1
	200	upvol	0, 20
	53	end
	end

      	playlist	1167, 2, 'Shao Kahn: Prepare to die'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'skprepdi', 1
	200	upvol	0, 20
	53	end
	end

      	playlist	1168, 3, 'Shao Kahn: Prepare to die'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'skprepdi', 1
	200	upvol	0, 20
	53	end
	end

      	playlist	1172, 1, 'Shao Kahn: You will die'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'skwilldi', 1
	270	upvol	0, 20
	36	end
	end

      	playlist	1173, 2, 'Shao Kahn: You will die'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'skwilldi', 1
	270	upvol	0, 20
	36	end
	end

      	playlist	1174, 3, 'Shao Kahn: You will die'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'skwilldi', 1
	270	upvol	0, 20
	36	end
	end

      	playlist	1175, 1, 'Shao Kahn: You are nothing'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'sknuthin', 1
	200	upvol	0, 20
	27	end
	end

      	playlist	1176, 2, 'Shao Kahn: You are nothing'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'sknuthin', 1
	200	upvol	0, 20
	27	end
	end

      	playlist	1177, 3, 'Shao Kahn: You are nothing'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'sknuthin', 1
	200	upvol	0, 20
	27	end
	end

      	playlist	1178, 1, 'Shao Kahn: laugh #1'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'sklaugh1', 1
	250	upvol	0, 20
	15	end
	end

      	playlist	1179, 2, 'Shao Kahn: laugh #1'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'sklaugh1', 1
	250	upvol	0, 20
	30	end
	end

      	playlist	1180, 3, 'Shao Kahn: laugh #1'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'sklaugh1', 1
	250	upvol	0, 20
	30	end
	end

      	playlist	1181, 1, 'Shao Kahn: laugh #2'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'sklaugh2', 1
	250	upvol	0, 20
	36	end
	end

      	playlist	1182, 2, 'Shao Kahn: laugh #2'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'sklaugh2', 1
	250	upvol	0, 20
	36	end
	end

      	playlist	1183, 3, 'Shao Kahn: laugh #2'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'sklaugh2', 1
	250	upvol	0, 20
	36	end
	end

      	playlist	1184, 1, 'Shao Kahn: laugh #3'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'sklaugh3', 1
	100	upvol	0, 20
	30	end
	end

      	playlist	1185, 2, 'Shao Kahn: laugh #3'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'sklaugh3', 1
	100	upvol	0, 20
	30	end
	end

      	playlist	1186, 3, 'Shao Kahn: laugh #3'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'sklaugh3', 1
	100	upvol	0, 20
	30	end
	end

      	playlist	1187, 1, 'Shao Kahn: <laugh> ... yer best?'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'sklaugh3', 1
	169	play	1, 'skbest', 1
	175	upvol	0, 20
	50	end
	end

      	playlist	1188, 2, 'Shao Kahn: <laugh> ... yer best?'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'sklaugh3', 1
	169	play	2, 'skbest', 1
	175	upvol	0, 20
	50	end
	end

      	playlist	1189, 3, 'Shao Kahn: <laugh> ... yer best?'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'sklaugh3', 1
	169	play	3, 'skbest', 1
	175	upvol	0, 20
	50	end
	end

      	playlist	1190, 1, 'Shao Kahn: Is that yer best?'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'skbest', 1
	175	upvol	0, 20
	50	end
	end

      	playlist	1191, 2, 'Shao Kahn: Is that yer best?'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'skbest', 1
	175	upvol	0, 20
	50	end
	end

      	playlist	1192, 3, 'Shao Kahn: Is that yer best?'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'skbest', 1
	175	upvol	0, 20
	50	end
	end

      	playlist	1193, 1, 'Shao Kahn: All too easy'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'skeasy', 1
	200	upvol	0, 20
	33	end
	end

      	playlist	1194, 2, 'Shao Kahn: All too easy'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'skeasy', 1
	200	upvol	0, 20
	33	end
	end

      	playlist	1195, 3, 'Shao Kahn: All too easy'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'skeasy', 1
	200	upvol	0, 20
	33	end
	end

      	playlist	1196, 1, 'Shao Kahn: You weak pathetic ...'
	0	setvol	1, 110
	0	downvol	0, 20
	0	play	1, 'skfool', 1
	350	upvol	0, 20
	29	end
	end

      	playlist	1197, 2, 'Shao Kahn: You weak pathetic ...'
	0	setvol	2, 110
	0	downvol	0, 20
	0	play	2, 'skfool', 1
	350	upvol	0, 20
	29	end
	end

      	playlist	1198, 3, 'Shao Kahn: You weak pathetic ...'
	0	setvol	3, 110
	0	downvol	0, 20
	0	play	3, 'skfool', 1
	350	upvol	0, 20
	29	end
	end

; **************************************************************************
; *                                                                        *
; *                         Boss Monster Speech                            *
; *                                                                        *
; **************************************************************************

      	playlist	1200, 1, 'Goro: Growl #1'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'gorgrwl1', 1
	180	upvol	0, 10
	33	end
	end

      	playlist	1201, 2, 'Goro: Growl #1'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'gorgrwl1', 1
	180	upvol	0, 10
	33	end
	end

      	playlist	1202, 3, 'Goro: Growl #1'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'gorgrwl1', 1
	180	upvol	0, 10
	33	end
	end

      	playlist	1203, 1, 'Goro: Growl #2'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'gorgrwl2', 1
	280	upvol	0, 10
	31	end
	end

      	playlist	1204, 2, 'Goro: Growl #2'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'gorgrwl2', 1
	280	upvol	0, 10
	31	end
	end

      	playlist	1205, 3, 'Goro: Growl #2'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'gorgrwl2', 1
	280	upvol	0, 10
	31	end
	end

      	playlist	1206, 1, 'Goro: Roar'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'gororoar', 1
	250	upvol	0, 10
	25	end
	end

      	playlist	1207, 2, 'Goro: Roar'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'gororoar', 1
	250	upvol	0, 10
	25	end
	end

      	playlist	1208, 3, 'Goro: Roar'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'gororoar', 1
	250	upvol	0, 10
	25	end
	end

      	playlist	1209, 1, 'Goro: Stomp roar'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'gorattk', 1
	130	upvol	0, 10
	38	end
	end

      	playlist	1210, 2, 'Goro: Stomp roar'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'gorattk', 1
	130	upvol	0, 10
	38	end
	end

      	playlist	1211, 3, 'Goro: Stomp roar'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'gorattk', 1
	130	upvol	0, 10
	38	end
	end

      	playlist	1212, 1, 'Goro: react #1'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'goroung1', 1
	60	upvol	0, 10
	34	end
	end

      	playlist	1213, 2, 'Goro: react #1'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'goroung1', 1
	60	upvol	0, 10
	34	end
	end

      	playlist	1214, 3, 'Goro: react #1'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'goroung1', 1
	60	upvol	0, 10
	34	end
	end

      	playlist	1215, 1, 'Goro: react #2'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'goroung2', 1
	50	upvol	0, 10
	32	end
	end

      	playlist	1216, 2, 'Goro: react #2'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'goroung2', 1
	50	upvol	0, 10
	32	end
	end

      	playlist	1217, 3, 'Goro: react #2'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'goroung2', 1
	50	upvol	0, 10
	32	end
	end

      	playlist	1218, 1, 'Goro: crazy scary roar'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'czgoroar', 1
	250	upvol	0, 10
	26	end
	end

      	playlist	1219, 2, 'Goro: crazy scary roar'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'czgoroar', 1
	250	upvol	0, 10
	26	end
	end

      	playlist	1220, 3, 'Goro: crazy scary roar'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'czgoroar', 1
	250	upvol	0, 10
	26	end
	end

      	playlist	1250, 1, 'Shao Kahn: attack #1'
	0	setvol	1, 103
	0	play	1, 'skatt1', 1
	83	end
	end

      	playlist	1251, 2, 'Shao Kahn: attack #1'
	0	setvol	2, 103
	0	play	2, 'skatt1', 1
	83	end
	end

      	playlist	1252, 3, 'Shao Kahn: attack #1'
	0	setvol	3, 103
	0	play	3, 'skatt1', 1
	83	end
	end

      	playlist	1253, 1, 'Shao Kahn: attack #2'
	0	setvol	1, 103
	0	play	1, 'skatt2', 1
	89	end
	end

      	playlist	1254, 2, 'Shao Kahn: attack #2'
	0	setvol	2, 103
	0	play	2, 'skatt2', 1
	89	end
	end

      	playlist	1255, 3, 'Shao Kahn: attack #2'
	0	setvol	3, 103
	0	play	3, 'skatt2', 1
	89	end
	end

      	playlist	1256, 1, 'Shao Kahn: react #1'
	0	setvol	1, 103
	0	play	1, 'skreact1', 1
	63	end
	end

      	playlist	1257, 2, 'Shao Kahn: react #1'
	0	setvol	2, 103
	0	play	2, 'skreact1', 1
	63	end
	end

      	playlist	1258, 3, 'Shao Kahn: react #1'
	0	setvol	3, 103
	0	play	3, 'skreact1', 1
	63	end
	end

      	playlist	1259, 1, 'Shao Kahn: react #2'
	0	setvol	1, 110
	0	play	1, 'skreact2', 1
	74	end
	end

      	playlist	1260, 2, 'Shao Kahn: react #2'
	0	setvol	2, 110
	0	play	2, 'skreact2', 1
	74	end
	end

      	playlist	1261, 3, 'Shao Kahn: react #2'
	0	setvol	3, 110
	0	play	3, 'skreact2', 1
	74	end
	end

      	playlist	1262, 1, 'Shao Kahn: react #3'
	0	setvol	1, 103
	0	play	1, 'skreact3', 1
	92	end
	end

      	playlist	1263, 2, 'Shao Kahn: react #3'
	0	setvol	2, 103
	0	play	2, 'skreact3', 1
	92	end
	end

      	playlist	1264, 3, 'Shao Kahn: react #3'
	0	setvol	3, 103
	0	play	3, 'skreact3', 1
	92	end
	end

      	playlist	1265, 1, 'Shao Kahn: react #4'
	0	setvol	1, 103
	0	play	1, 'skreact4', 1
	118	end
	end

      	playlist	1266, 2, 'Shao Kahn: react #4'
	0	setvol	2, 103
	0	play	2, 'skreact4', 1
	118	end
	end

      	playlist	1267, 3, 'Shao Kahn: react #4'
	0	setvol	3, 103
	0	play	3, 'skreact4', 1
	118	end
	end

      	playlist	1268, 1, 'Shao Kahn: wast #1'
	0	setvol	1, 103
	0	play	1, 'skwast1', 1
	131	end
	end

      	playlist	1269, 2, 'Shao Kahn: wast #1'
	0	setvol	2, 103
	0	play	2, 'skwast1', 1
	131	end
	end

      	playlist	1270, 3, 'Shao Kahn: wast #1'
	0	setvol	3, 103
	0	play	3, 'skwast1', 1
	131	end
	end

      	playlist	1271, 1, 'Shao Kahn: wast #2'
	0	setvol	1, 103
	0	play	1, 'skwast2', 1
	147	end
	end

      	playlist	1272, 2, 'Shao Kahn: wast #2'
	0	setvol	2, 103
	0	play	2, 'skwast2', 1
	147	end
	end

      	playlist	1273, 3, 'Shao Kahn: wast #2'
	0	setvol	3, 103
	0	play	3, 'skwast2', 1
	147	end
	end

      	playlist	1288, 1, 'bones fall #1'
	0	setvol	1, 103
	0	play	1, 'bones1', 1
	53	end
	end

      	playlist	1289, 2, 'bones fall #1'
	0	setvol	2, 103
	0	play	2, 'bones1', 1
	53	end
	end

      	playlist	1290, 3, 'bones fall #1'
	0	setvol	3, 103
	0	play	3, 'bones1', 1
	53	end
	end

      	playlist	1291, 1, 'bones fall #2'
	0	setvol	1, 103
	0	play	1, 'bones2', 1
	69	end
	end

      	playlist	1292, 2, 'bones fall #2'
	0	setvol	2, 103
	0	play	2, 'bones2', 1
	69	end
	end

      	playlist	1293, 3, 'bones fall #2'
	0	setvol	3, 103
	0	play	3, 'bones2', 1
	69	end
	end

      	playlist	1294, 1, 'bones fall #3'
	0	setvol	1, 103
	0	play	1, 'bones3', 1
	61	end
	end

      	playlist	1295, 2, 'bones fall #3'
	0	setvol	2, 103
	0	play	2, 'bones3', 1
	61	end
	end

      	playlist	1296, 3, 'bones fall #3'
	0	setvol	3, 103
	0	play	3, 'bones3', 1
	61	end
	end

      	playlist	1297, 1, 'bones fall #4'
	0	setvol	1, 103
	0	play	1, 'bones4', 1
	57	end
	end

      	playlist	1298, 2, 'bones fall #4'
	0	setvol	2, 103
	0	play	2, 'bones4', 1
	57	end
	end

      	playlist	1299, 3, 'bones fall #4'
	0	setvol	3, 103
	0	play	3, 'bones4', 1
	57	end
	end

; **************************************************************************
; *                                                                        *
; *                         More Stuff                                     *
; *                                                                        *
; **************************************************************************

      	playlist	1300, 1, 'Ed: Slippery #1'
	0	setvol	1, 95
	0	play	1, 'sliped1', 1
	56	end
	end

      	playlist	1301, 2, 'Ed: Slippery #1'
	0	setvol	2, 95
	0	play	2, 'sliped1', 1
	56	end
	end

      	playlist	1302, 3, 'Ed: Slippery #1'
	0	setvol	3, 95
	0	play	3, 'sliped1', 1
	56	end
	end

      	playlist	1303, 1, 'Ed: Slippery #2'
	0	setvol	1, 95
	0	play	1, 'sliped2', 1
	57	end
	end

      	playlist	1304, 2, 'Ed: Slippery #2'
	0	setvol	2, 95
	0	play	2, 'sliped2', 1
	57	end
	end

      	playlist	1305, 3, 'Ed: Slippery #2'
	0	setvol	3, 95
	0	play	3, 'sliped2', 1
	57	end
	end

      	playlist	1306, 1, 'Ed: Slippery #3'
	0	setvol	1, 95
	0	play	1, 'sliped3', 1
	67	end
	end

      	playlist	1307, 2, 'Ed: Slippery #3'
	0	setvol	2, 95
	0	play	2, 'sliped3', 1
	67	end
	end

      	playlist	1308, 3, 'Ed: Slippery #3'
	0	setvol	3, 95
	0	play	3, 'sliped3', 1
	67	end
	end

      	playlist	1309, 1, 'Ed: Slippery #4'
	0	setvol	1, 95
	0	play	1, 'sliped4', 1
	83	end
	end

      	playlist	1310, 2, 'Ed: Slippery #4'
	0	setvol	2, 95
	0	play	2, 'sliped4', 1
	83	end
	end

      	playlist	1311, 3, 'Ed: Slippery #4'
	0	setvol	3, 95
	0	play	3, 'sliped4', 1
	83	end
	end

      	playlist	1312, 1, 'Ed: Slippery #5'
	0	setvol	1, 95
	0	play	1, 'sliped5', 1
	96	end
	end

      	playlist	1313, 2, 'Ed: Slippery #5'
	0	setvol	2, 95
	0	play	2, 'sliped5', 1
	96	end
	end

      	playlist	1314, 3, 'Ed: Slippery #5'
	0	setvol	3, 95
	0	play	3, 'sliped5', 1
	96	end
	end

      	playlist	1315, 1, 'Ed: Slippery #6'
	0	setvol	1, 95
	0	play	1, 'sliped6', 1
	70	end
	end

      	playlist	1316, 2, 'Ed: Slippery #6'
	0	setvol	2, 95
	0	play	2, 'sliped6', 1
	70	end
	end

      	playlist	1317, 3, 'Ed: Slippery #6'
	0	setvol	3, 95
	0	play	3, 'sliped6', 1
	70	end
	end

      	playlist	1318, 1, 'Ed: Big Slippery Whoa'
	0	setvol	1, 95
	0	play	1, 'slipbig', 1
	236	end
	end

      	playlist	1319, 2, 'Ed: Big Slippery Whoa'
	0	setvol	2, 95
	0	play	2, 'slipbig', 1
	236	end
	end

      	playlist	1320, 3, 'Ed: Big Slippery Whoa'
	0	setvol	3, 95
	0	play	3, 'slipbig', 1
	236	end
	end

      	playlist	1321, 1, 'Dan: Slippery #1'
	0	setvol	1, 95
	0	play	1, 'slipdan1', 1
	46	end
	end

      	playlist	1322, 2, 'Dan: Slippery #1'
	0	setvol	2, 95
	0	play	2, 'slipdan1', 1
	46	end
	end

      	playlist	1323, 3, 'Dan: Slippery #1'
	0	setvol	3, 95
	0	play	3, 'slipdan1', 1
	46	end
	end

      	playlist	1324, 1, 'Dan: Slippery #2'
	0	setvol	1, 95
	0	play	1, 'slipdan2', 1
	48	end
	end

      	playlist	1325, 2, 'Dan: Slippery #2'
	0	setvol	2, 95
	0	play	2, 'slipdan2', 1
	48	end
	end

      	playlist	1326, 3, 'Dan: Slippery #2'
	0	setvol	3, 95
	0	play	3, 'slipdan2', 1
	48	end
	end

      	playlist	1327, 1, 'Dan: Slippery #3'
	0	setvol	1, 95
	0	play	1, 'slipdan3', 1
	49	end
	end

      	playlist	1328, 2, 'Dan: Slippery #3'
	0	setvol	2, 95
	0	play	2, 'slipdan3', 1
	49	end
	end

      	playlist	1329, 3, 'Dan: Slippery #3'
	0	setvol	3, 95
	0	play	3, 'slipdan3', 1
	49	end
	end

      	playlist	1330, 1, 'Dan: Slippery #4'
	0	setvol	1, 95
	0	play	1, 'slipdan4', 1
	49	end
	end

      	playlist	1331, 2, 'Dan: Slippery #4'
	0	setvol	2, 95
	0	play	2, 'slipdan4', 1
	49	end
	end

      	playlist	1332, 3, 'Dan: Slippery #4'
	0	setvol	3, 95
	0	play	3, 'slipdan4', 1
	49	end
	end

      	playlist	1333, 1, 'Dan: Slippery #5'
	0	setvol	1, 99
	0	play	1, 'slipdan5', 1
	70	end
	end

      	playlist	1334, 2, 'Dan: Slippery #5'
	0	setvol	2, 99
	0	play	2, 'slipdan5', 1
	70	end
	end

      	playlist	1335, 3, 'Dan: Slippery #5'
	0	setvol	3, 99
	0	play	3, 'slipdan5', 1
	70	end
	end

      	playlist	1336, 1, 'Dan: Slippery #6'
	0	setvol	1, 99
	0	play	1, 'slipdan6', 1
	105	end
	end

      	playlist	1337, 2, 'Dan: Slippery #6'
	0	setvol	2, 99
	0	play	2, 'slipdan6', 1
	105	end
	end

      	playlist	1338, 3, 'Dan: Slippery #6'
	0	setvol	3, 99
	0	play	3, 'slipdan6', 1
	105	end
	end

      	playlist	1350, 1, 'Girl: Slippery #1'
	0	setvol	1, 100
	0	play	1, 'gslip1', 1
	79	end
	end

      	playlist	1351, 2, 'Girl: Slippery #1'
	0	setvol	2, 100
	0	play	2, 'gslip1', 1
	79	end
	end

      	playlist	1352, 3, 'Girl: Slippery #1'
	0	setvol	3, 100
	0	play	3, 'gslip1', 1
	79	end
	end

      	playlist	1353, 1, 'Girl: Slippery #2'
	0	setvol	1, 100
	0	play	1, 'gslip2', 1
	44	end
	end

      	playlist	1354, 2, 'Girl: Slippery #2'
	0	setvol	2, 100
	0	play	2, 'gslip2', 1
	44	end
	end

      	playlist	1355, 3, 'Girl: Slippery #2'
	0	setvol	3, 100
	0	play	3, 'gslip2', 1
	44	end
	end

      	playlist	1356, 1, 'Girl: Slippery #3'
	0	setvol	1, 100
	0	play	1, 'gslip3', 1
	89	end
	end

      	playlist	1357, 2, 'Girl: Slippery #3'
	0	setvol	2, 100
	0	play	2, 'gslip3', 1
	89	end
	end

      	playlist	1358, 3, 'Girl: Slippery #3'
	0	setvol	3, 100
	0	play	3, 'gslip3', 1
	89	end
	end

      	playlist	1359, 1, 'Girl: Slippery #4'
	0	setvol	1, 100
	0	play	1, 'gslip4', 1
	45	end
	end

      	playlist	1360, 2, 'Girl: Slippery #4'
	0	setvol	2, 100
	0	play	2, 'gslip4', 1
	45	end
	end

      	playlist	1361, 3, 'Girl: Slippery #4'
	0	setvol	3, 100
	0	play	3, 'gslip4', 1
	45	end
	end

      	playlist	1362, 1, 'Girl: Slippery #5'
	0	setvol	1, 100
	0	play	1, 'gslip5', 1
	72	end
	end

      	playlist	1363, 2, 'Girl: Slippery #5'
	0	setvol	2, 100
	0	play	2, 'gslip5', 1
	72	end
	end

      	playlist	1364, 3, 'Girl: Slippery #5'
	0	setvol	3, 100
	0	play	3, 'gslip5', 1
	72	end
	end

      	playlist	1365, 1, 'Girl: Big slip'
	0	setvol	1, 100
	0	play	1, 'gbigslip', 1
	133	end
	end

      	playlist	1366, 2, 'Girl: Big slip'
	0	setvol	2, 100
	0	play	2, 'gbigslip', 1
	133	end
	end

      	playlist	1367, 3, 'Girl: Big slip'
	0	setvol	3, 100
	0	play	3, 'gbigslip', 1
	133	end
	end

      	playlist	1377, 1, 'Shao Kahn: destruction rumble #1'
	0	setvol	1, 50
	0	rampupvol	1, 60, 500
	0	play	1, 'skb2l', 1
	97	play	1, 'skb2l', 1
	90	play	1, 'skb2l', 1
	85	play	1, 'skb2l', 1
	80	play	1, 'skb2l', 1
	72	play	1, 'skb2l', 1
	62	play	1, 'skb2l', 1
	97	end
	end

      	playlist	1378, 2, 'Shao Kahn: destruction rumble #1'
	0	setvol	2, 50
	0	rampupvol	2, 60, 500
	0	play	2, 'skb2l', 1
	97	play	2, 'skb2l', 1
	90	play	2, 'skb2l', 1
	85	play	2, 'skb2l', 1
	80	play	2, 'skb2l', 1
	72	play	2, 'skb2l', 1
	62	play	2, 'skb2l', 1
	97	end
	end

      	playlist	1379, 3, 'Shao Kahn: destruction rumble #1'
	0	setvol	3, 50
	0	rampupvol	3, 60, 500
	0	play	3, 'skb2l', 1
	97	play	3, 'skb2l', 1
	90	play	3, 'skb2l', 1
	85	play	3, 'skb2l', 1
	80	play	3, 'skb2l', 1
	72	play	3, 'skb2l', 1
	62	play	3, 'skb2l', 1
	97	end
	end

      	playlist	1380, 1, 'Shao Kahn: destruction rumble #2'
	0	setvol	1, 30
	0	rampupvol	1, 80, 500
	0	play	1, 'skb1l', 1
	81	play	1, 'skb1l', 1
	78	play	1, 'skb1l', 1
	74	play	1, 'skb1l', 1
	69	play	1, 'skb1l', 1
	63	play	1, 'skb1l', 1
	56	play	1, 'skb1l', 1
	54	play	1, 'skb1l', 1
	50	play	1, 'skb1l', 1
	50	play	1, 'skb1l', 1
	81	loopend
	0	end
	end

      	playlist	1381, 2, 'Shao Kahn: destruction rumble #2'
	0	setvol	2, 30
	0	rampupvol	2, 80, 500
	0	play	2, 'skb1l', 1
	81	play	2, 'skb1l', 1
	78	play	2, 'skb1l', 1
	74	play	2, 'skb1l', 1
	69	play	2, 'skb1l', 1
	63	play	2, 'skb1l', 1
	56	play	2, 'skb1l', 1
	54	play	2, 'skb1l', 1
	50	play	2, 'skb1l', 1
	50	play	2, 'skb1l', 1
	81	loopend
	0	end
	end

      	playlist	1382, 3, 'Shao Kahn: destruction rumble #2'
	0	setvol	3, 30
	0	rampupvol	3, 80, 500
	0	play	3, 'skb1l', 1
	81	play	3, 'skb1l', 1
	78	play	3, 'skb1l', 1
	74	play	3, 'skb1l', 1
	69	play	3, 'skb1l', 1
	63	play	3, 'skb1l', 1
	56	play	3, 'skb1l', 1
	54	play	3, 'skb1l', 1
	50	play	3, 'skb1l', 1
	50	play	3, 'skb1l', 1
	81	loopend
	0	end
	end

      	playlist	1383, 1, 'Shao Kahn: No! #1'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'skno1', 1
	96	upvol	0, 10
	0	end
	end

      	playlist	1384, 2, 'Shao Kahn: No! #1'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'skno1', 1
	96	upvol	0, 10
	0	end
	end

      	playlist	1385, 3, 'Shao Kahn: No! #1'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'skno1', 1
	96	upvol	0, 10
	0	end
	end

      	playlist	1386, 1, 'Shao Kahn: No! #2'
	0	downvol	0, 10
	0	setvol	1, 110
	0	play	1, 'skno2', 1
	101	upvol	0, 10
	0	end
	end

      	playlist	1387, 2, 'Shao Kahn: No! #2'
	0	downvol	0, 10
	0	setvol	2, 110
	0	play	2, 'skno2', 1
	101	upvol	0, 10
	0	end
	end

      	playlist	1388, 3, 'Shao Kahn: No! #2'
	0	downvol	0, 10
	0	setvol	3, 110
	0	play	3, 'skno2', 1
	101	upvol	0, 10
	0	end
	end

      	playlist	1389, 1, 'Shao Kahn: Nooooo! with noise'
	0	downvol	0, 10
	0	setvol	1, 115
	0	play	1, 'skbyebye', 1
	572	upvol	0, 10
	0	end
	end

      	playlist	1390, 2, 'Shao Kahn: Nooooo! with noise'
	0	downvol	0, 10
	0	setvol	2, 115
	0	play	2, 'skbyebye', 1
	572	upvol	0, 10
	0	end
	end

      	playlist	1391, 3, 'Shao Kahn: Nooooo! with noise'
	0	downvol	0, 10
	0	setvol	3, 115
	0	play	3, 'skbyebye', 1
	572	upvol	0, 10
	0	end
	end

      	playlist	1392, 1, 'Shao Kahn: turn to stone'
	0	downvol	0, 10
	0	setvol	1, 100
	0	play	1, 'skcrackl', 1
	78	upvol	0, 10
	0	end
	end

      	playlist	1393, 2, 'Shao Kahn: turn to stone'
	0	downvol	0, 10
	0	setvol	2, 100
	0	play	2, 'skcrackl', 1
	78	upvol	0, 10
	0	end
	end

      	playlist	1394, 3, 'Shao Kahn: turn to stone'
	0	downvol	0, 10
	0	setvol	3, 100
	0	play	3, 'skcrackl', 1
	78	upvol	0, 10
	0	end
	end

      	playlist	1395, 1, 'Shao Kahn: destruction sequence example'
	0	setvol	2, 105
	0	play	2, 'bigcrnch', 1

	5	setvol	3, 105
	0	play	3, 'skwast2', 1
	
	5	setvol	1, 10
	0	rampupvol	1, 100, 600
	0	play	1, 'skb1l', 8

	180	setvol	2, 110
	0	play	2, 'skno1', 1
	140	play	2, 'skno2', 1
	150	setvol	2, 115
	0	play	2, 'skbyebye', 1
	560	setvol	2, 100
	0	play	2, 'skcrackl', 1
	100	setvol	2, 115
	0	play	2, 'bigcrnch', 1
	30	play	2, 'bigcrnch', 1
	30	play	2, 'bodyxpld', 1
	300	install	64
	34	end
	end

      	playlist	1400, 1, 'Feel the power of ????'
	0	downvol	0, 15
	0	setvol	1, 115
	0	play	1, 'skfeelpr', 1
	178	play	1, 'tosty', 1
	90	upvol	0, 15
	0	end
	end

      	playlist	1401, 2, 'Feel the power of ????'
	0	downvol	0, 15
	0	setvol	2, 115
	0	play	2, 'skfeelpr', 1
	178	play	2, 'tosty', 1
	90	upvol	0, 15
	0	end
	end

      	playlist	1402, 3, 'Feel the power of ????'
	0	downvol	0, 15
	0	setvol	3, 115
	0	play	3, 'skfeelpr', 1
	178	play	3, 'tosty', 1
	90	upvol	0, 15
	0	end
	end

; **************************************************************************
; * END of playlist and file                                               *
; **************************************************************************


