# First Pass

henry c -vt1 -v2 -vb79 -vr79 -vi15  bighit1
henry c -vt1 -v2 -vb79 -vr79 -vi15  bighit2
henry c -vt1 -v2 -vb79 -vr79 -vi15  block1
henry c -vt1 -v2 -vb79 -vr79 -vi15  bigblock
henry c -vt1 -v2 -vb79 -vr79 -vi15  body1
henry c -vt1 -v2 -vb79 -vr79 -vi15  body2
henry c -vt1 -v2 -vb79 -vr79 -vi15  bwhoosh1
henry c -vt1 -v2 -vb79 -vr79 -vi15  bwhoosh2
henry c -vt1 -v2 -vb79 -vr79 -vi15  face2
henry c -vt1 -v2 -vb79 -vr79 -vi15  whoosh1
henry c -vt1 -v2 -vb79 -vr79 -vi15  whoosh2
henry c -vt1 -v2 -vb79 -vr79 -vi15  whoosh3
henry c -vt1 -v4 -vb71 -vr55 -vi15  crunch1
henry c -vt1 -v4 -vb71 -vr55 -vi15  crunch2
henry c -vt1 -v4 -vb71 -vr55 -vi15  stab1

# Gud Pass

henry c -vt1 -v2 -vb79 -vr79 -vi15  gudhit1
henry c -vt1 -v4 -vb79 -vr79 -vi15  gudfall1
henry c -vt1 -v4 -vb79 -vr79 -vi15  gudfall2
henry c -vt1 -v2 -vb79 -vr79 -vi15  bighit3
henry c -vt1 -v2 -vb79 -vr79 -vi15  goodbod1
henry c -vt1 -v2 -vb79 -vr79 -vi15  gudblock
henry c -vt1 -v4 -vb79 -vr79 -vi15  splish1
henry c -vt1 -v4 -vb79 -vr79 -vi15  splish2
henry c -vt1 -v4 -vb79 -vr79 -vi15  splish3
henry c -vt1 -v3 -vb79 -vr79 -vi15  bigfall1
henry c -vt1 -v3 -vb95 -vr79 -vi15  bigstab1
henry c -vt1 -v3 -vb95 -vr79 -vi15  bigstab2
henry c -vt1 -v3 -vb95 -vr79 -vi15  bigstab3
henry c -vt1 -v5 -vb79 -vr79 -vi15  gudfall3
henry c -vt1 -v5 -vb79 -vr79 -vi15  gudfall4
henry c -vt1 -v5 -vb63 -vr63 -vi15  fallhrd1
henry c -vt1 -v5 -vb63 -vr63 -vi15  fallhrd2
henry c -vt1 -v5 -vb63 -vr63 -vi15  fallmet
henry c -vt1 -v2 -vb79 -vr79 -vi7  oldbig1
henry c -vt1 -v2 -vb79 -vr79 -vi7  oldbig2
henry c -vt0 -v1 -vb79 -vr79 -vi7  roldbig1
henry c -vt0 -v1 -vb79 -vr79 -vi7  roldbig2
henry c -vt1 -v2 -vb79 -vr63 -vi7  bwhoosh3
henry c -vt1 -v4 -vb79 -vr63 -vi7  lilstab1
henry c -vt1 -v4 -vb79 -vr63 -vi7  lilstab2
henry c -vt1 -v4 -vb79 -vr63 -vi7  lilstab3

