#	Dan speech

henry c -vt3 -v6 -vb47 -vr47 -vi15  dfdeath1
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfgrab
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfjump
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfreact1
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfreact2
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfreact3
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfthrow
henry c -vt3 -v6 -vb47 -vr47 -vi15  dftrip
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfwast1
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfwast2
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfatak1
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfatak2
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfskream
henry c -vt3 -v6 -vb47 -vr47 -vi15  klflip
henry c -vt3 -v6 -vb47 -vr47 -vi15  slipdan1
henry c -vt3 -v6 -vb47 -vr47 -vi15  slipdan2
henry c -vt3 -v6 -vb47 -vr47 -vi15  slipdan3
henry c -vt3 -v6 -vb47 -vr47 -vi15  slipdan4
henry c -vt3 -v6 -vb47 -vr47 -vi15  slipdan5
henry c -vt3 -v6 -vb47 -vr47 -vi15  slipdan6

#	Jon Hey speech

henry c -vt3 -v6 -vb47 -vr47 -vi15  jhattak1
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhattak2
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhdeath1
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhgrab
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhjump
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhreact1
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhreact2
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhreact3
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhthrow
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhtrip
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhwast1
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhwast2
henry c -vt3 -v6 -vb47 -vr47 -vi15  gib1
henry c -vt3 -v6 -vb47 -vr47 -vi15  gib3
henry c -vt3 -v6 -vb47 -vr47 -vi15  gib2
henry c -vt3 -v6 -vb47 -vr47 -vi15  gib4
henry c -vt3 -v6 -vb47 -vr47 -vi15  gib5
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhfelch
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhyum

#	Liu Kang speech

henry c -vt3 -v6 -vb47 -vr47 -vi15  lkattak1
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkattak2
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkcycle
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkfall
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkjump
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkthrow1
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkthrow2
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkreact1
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkreact2
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkspiked
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkwast1
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkwast2
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkdeath
henry c -vt3 -v5 -vb47 -vr47 -vi15  lkflyk1
henry c -vt3 -v5 -vb47 -vr47 -vi15  lkflyk2
henry c -vt3 -v5 -vb47 -vr47 -vi15  lkendf
henry c -vt3 -v5 -vb47 -vr47 -vi15  lkspink
henry c -vt3 -v5 -vb47 -vr47 -vi15  lkspkck1
henry c -vt3 -v5 -vb47 -vr47 -vi15  lkspkck2
henry c -vt3 -v5 -vb47 -vr47 -vi15  lkupper

#	Ninja Girl #1 speech

henry c -vt3 -v6 -vb47 -vr47 -vi15  n1attak1
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1attak2
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1death1
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1grab
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1jump
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1react1
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1react2
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1react3
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1throw
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1trip
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1wast1
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1wast2
henry c -vt3 -v6 -vb47 -vr47 -vi15  gbigslip
henry c -vt3 -v6 -vb47 -vr47 -vi15  gexplode
henry c -vt3 -v6 -vb47 -vr47 -vi15  gpit
henry c -vt3 -v6 -vb47 -vr47 -vi15  gpithit
henry c -vt3 -v6 -vb47 -vr47 -vi15  gslip1
henry c -vt3 -v6 -vb47 -vr47 -vi15  gslip2
henry c -vt3 -v6 -vb47 -vr47 -vi15  gslip3
henry c -vt3 -v6 -vb47 -vr47 -vi15  gslip4
henry c -vt3 -v6 -vb47 -vr47 -vi15  gslip5
henry c -vt3 -v6 -vb47 -vr47 -vi15  n1death2

# New Speech

henry c -vt3 -v6 -vb47 -vr47 -vi15  cagekiss
henry c -vt3 -v6 -vb47 -vr47 -vi15  dfyea
henry c -vt3 -v6 -vb47 -vr47 -vi15  jaxahh
henry c -vt3 -v6 -vb47 -vr47 -vi15  jaxgotch
henry c -vt2 -v6 -vb47 -vr47 -vi15  jaxyeah
henry c -vt3 -v6 -vb47 -vr47 -vi15  kidthund
henry c -vt3 -v6 -vb47 -vr47 -vi15  ohmaw
henry c -vt3 -v6 -vb47 -vr47 -vi15  scorcome
henry c -vt3 -v6 -vb47 -vr47 -vi15  scorget
henry c -vt3 -v6 -vb47 -vr47 -vi15  slipbig
henry c -vt3 -v6 -vb47 -vr47 -vi15  sliped1
henry c -vt3 -v6 -vb47 -vr47 -vi15  sliped2
henry c -vt3 -v6 -vb47 -vr47 -vi15  sliped3
henry c -vt3 -v6 -vb47 -vr47 -vi15  sliped4
henry c -vt3 -v6 -vb47 -vr47 -vi15  sliped5
henry c -vt3 -v6 -vb47 -vr47 -vi15  sliped6
henry c -vt3 -v6 -vb47 -vr47 -vi15  tosty
henry c -vt3 -v6 -vb47 -vr47 -vi15  treeroar
henry c -vt3 -v5 -vb47 -vr47 -vi15  gorattk
henry c -vt3 -v5 -vb47 -vr47 -vi15  gorgrwl1
henry c -vt3 -v5 -vb47 -vr47 -vi15  gorgrwl2
henry c -vt3 -v5 -vb47 -vr47 -vi15  gororoar
henry c -vt3 -v5 -vb47 -vr47 -vi15  goroung1
henry c -vt3 -v5 -vb47 -vr47 -vi15  goroung2
henry c -vt3 -v5 -vb47 -vr47 -vi15  czgoroar
henry c -vt3 -v5 -vb47 -vr47 -vi15  oooh

# Shao Kahn speech

henry c -vt3 -v5.75 -vb47 -vr47 -vi7  finishim
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  finisher
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  fatality
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  flawless
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  fantstic
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  outstand
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  welldone
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  superb
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  babality
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  excelent
#henry c -vt3 -v5.75 -vb47 -vr47 -vi7  fight2
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  fight1
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  friend1
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  friend2
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  malena
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  rfour
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  rone
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  round
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  rthree
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  rtwo
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  baraka
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  jade
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  jax
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  joncage
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  kitana
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  kunglao
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  liukang
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  otherchk
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  raiden
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  reptile
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  scorpion
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  shangtsg
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  smoke
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  subzero
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  kintaro
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  wins1
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skbow2me
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skeasy
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skfeelwr
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skfeelpr
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skfool
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skimsk
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skirule
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  sklaugh1
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  sklaugh2
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  sknuthin
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skwilldi
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skatt1
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skatt2
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skreact1
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skreact2
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skreact3
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skreact4
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skwast1
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skwast2
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skbest
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  sklaugh3
henry c -vt3 -v5.75 -vb47 -vr47 -vi7  skprepdi

# Vince speech

henry c -vt3 -v6 -vb47 -vr47 -vi15  vpattak1
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpattak2
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpdeath
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpgrab
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpjump
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpreact1
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpreact2
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpreact3
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpthrow
henry c -vt3 -v6 -vb47 -vr47 -vi15  vptrip
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpwast1
henry c -vt3 -v6 -vb47 -vr47 -vi15  vpwast2

# Pit Fall speech

henry c -vt3 -v6 -vb47 -vr47 -vi15  ebpit
henry c -vt3 -v6 -vb47 -vr47 -vi15  ebpithit
henry c -vt3 -v6 -vb47 -vr47 -vi15  jhpit
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkpit
henry c -vt3 -v6 -vb47 -vr47 -vi15  lkpithit
henry c -vt3 -v6 -vb47 -vr47 -vi15  vppit
henry c -vt3 -v6 -vb47 -vr47 -vi15  vppithit

