henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main4a
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main4b
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main4c
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main4d
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main4e
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  finish4
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  end4a
#henry c -vt0 -v4.5 -vb79 -vr63 -vi15  end4b
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  end4bl
