joey c -v5 -vb63 -vr63 -vi15  end6a
#joey c -v5 -vb63 -vr63 -vi15  end6b
joey c -v5 -vb63 -vr63 -vi15  end6bl
henry c -vt0 -v5 -vb63 -vr63 -vi15  finish6
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main6a
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main6b
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main6c
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main6d
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main6e
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main6f
henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main6g
