#	Miscellaneous Tunes

henry c -vt3 -v4 -vb79 -vr63 -vi15  introa
henry c -vt3 -v4.5 -vb79 -vr63 -vi15  introb
henry c -vt3 -v4 -vb79 -vr79 -vi7  mrtlsans
henry c -vt3 -v4 -vb79 -vr79 -vi7  mrtlsan2
henry c -vt3 -v4 -vb79 -vr63 -vi15  buyin
henry c -vt3 -v4.5 -vb79 -vr63 -vi15  oneguy
henry c -vt3 -v4 -vb79 -vr63 -vi7  endguy
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  attrct1a
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  attrct1b
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  attrct1c
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  attrct1d
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  attrct1e
henry c -vt3 -v4.5 -vb79 -vr63 -vi15  attrct1f
henry c -vt3 -v4 -vb79 -vr79 -vi7  fatal1
henry c -vt3 -v4 -vb79 -vr79 -vi7  fatal2
henry c -vt3 -v4 -vb79 -vr79 -vi15  fbone1
henry c -vt3 -v4 -vb79 -vr79 -vi15  message
henry c -vt3 -v4 -vb79 -vr79 -vi15  disco
henry c -vt3 -v3.5 -vb79 -vr63 -vi7  endsho1
henry c -vt3 -v3.5 -vb79 -vr63 -vi7  endsho2
henry c -vt3 -v3.5 -vb79 -vr63 -vi7  endsho3
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  thehits1
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  thehits2
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  thehits3
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  thehits4
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  thehits5
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  thehits6
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  theend1
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  theend2
henry c -vt3 -v4.5 -vb79 -vr63 -vi7  theend3
henry c -vt3 -v4.5 -vb79 -vr63 -vi15  dumbfrnd
henry c -vt3 -v4 -vb63 -vr63 -vi15  babytune
henry c -vt3 -v3.5 -vb79 -vr63 -vi7  attrct2a
henry c -vt3 -v3.5 -vb79 -vr63 -vi7  attrct2b

