henry c -vt0 -v4 -vb95 -vr79 -vi7  main7a
henry c -vt0 -v4 -vb95 -vr79 -vi7  main7b
henry c -vt0 -v4 -vb95 -vr79 -vi7  main7c
henry c -vt0 -v4 -vb95 -vr79 -vi7  main7d
henry c -vt0 -v4 -vb95 -vr79 -vi7  main7e
henry c -vt0 -v4 -vb95 -vr79 -vi7  main7f
henry c -vt0 -v4 -vb95 -vr79 -vi7  main7g
henry c -vt0 -v4 -vb95 -vr79 -vi7  finish7
henry c -vt0 -v4 -vb95 -vr79 -vi7  end7a
henry c -vt0 -v4 -vb95 -vr79 -vi7  end7b

