henry c -vt0 -v4.5 -vb79 -vr63 -vi15  main1a
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  main1b
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  main1c
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  main1d
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  main1e
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  main1f
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  end1a
#henry c -vt1 -v4 -vb79 -vr63 -vi15  end1b
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  end1bl
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  finish1a
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  finish1b


