#	Weapons

henry c -vt1 -v4 -vb79 -vr63 -vi15  fanhit
henry c -vt1 -v4 -vb79 -vr63 -vi15  nfanhit
henry c -vt1 -v4.5 -vb63 -vr47 -vi23  knifejec
henry c -vt1 -v4.5 -vb63 -vr47 -vi23  knifplng
henry c -vt1 -v4.5 -vb63 -vr47 -vi15  snotup
henry c -vt1 -v4.5 -vb63 -vr47 -vi15  snothit
#henry c -vt1 -v4 -vb79 -vr55 -vi15  tsaithr1
#henry c -vt1 -v4 -vb79 -vr55 -vi15  tsaithr2
#henry c -vt1 -v4 -vb79 -vr55 -vi15  tsaithr3
#henry c -vt1 -v4 -vb79 -vr55 -vi15  tsaithr4
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  repthock
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  reptspit
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  scorthr1
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  swrdscrp
henry c -vt1 -v5 -vb63 -vr63 -vi15  arcnast
henry c -vt1 -v5 -vb63 -vr63 -vi15  sprknst1
henry c -vt1 -v5 -vb63 -vr63 -vi15  sprknst2
henry c -vt1 -v5 -vb63 -vr63 -vi15  sprkthro

#	Pass 2

henry c -vt1 -v5 -vb63 -vr63 -vi23 arc1
henry c -vt1 -v5 -vb63 -vr63 -vi23 arc2
henry c -vt1 -v5 -vb63 -vr63 -vi23 arc3
henry c -vt1 -v4 -vb95 -vr63 -vi15  bwhoosh4
henry c -vt1 -v4 -vb63 -vr63 -vi15  cagekck1
henry c -vt1 -v4 -vb63 -vr63 -vi15  cagekck2
henry c -vt1 -v4 -vb63 -vr63 -vi15  girltrap
henry c -vt1 -v4 -vb63 -vr63 -vi15  hhsaw
henry c -vt1 -v2 -vb79 -vr79 -vi15  hhsawhit
henry c -vt1 -v4 -vb63 -vr63 -vi15  hhsawblk
henry c -vt1 -v4 -vb63 -vr63 -vi15  hhsawup
henry c -vt1 -v5 -vb63 -vr63 -vi15  kiss
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  stfball
henry c -vt1 -v5 -vb63 -vr63 -vi15  lkflykck
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  n1thrfan
henry c -vt1 -v4 -vb79 -vr63 -vi15  rgetup
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  rspark1
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  rsprkend
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  rsprkstr
henry c -vt1 -v4 -vb79 -vr63 -vi15  rtele
henry c -vt1 -v4 -vb63 -vr63 -vi15  rdive
henry c -vt1 -v4 -vb63 -vr63 -vi15  sizzle
henry c -vt1 -v4 -vb63 -vr63 -vi15  stskulls
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  szslide
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  tsaithro
henry c -vt1 -v4.5 -vb79 -vr63 -vi15  fballhit
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  szice1
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  szice2
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  szice3
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  reporb4l
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  repblow
henry c -vt1 -v4.5 -vb63 -vr63 -vi15  throtsai
henry c -vt1 -v5 -vb95 -vr63 -vi15  scortele
henry c -vt1 -v5 -vb95 -vr63 -vi15  kungtele
henry c -vt1 -v5 -vb95 -vr63 -vi15  mlenatel
henry c -vt1 -v5 -vb95 -vr63 -vi23  shngmrph
henry c -vt1 -v5 -vb95 -vr63 -vi23  barthrow
henry c -vt1 -v4 -vb79 -vr63 -vi7  bkwhoosh
henry c -vt1 -v5 -vb79 -vr63 -vi23  rtongue
henry c -vt1 -v4 -vb63 -vr63 -vi7  lkfball
henry c -vt1 -v4 -vb79 -vr63 -vi15  kungspin
henry c -vt1 -v4 -vb79 -vr63 -vi15  szfreeze
henry c -vt1 -v5 -vb79 -vr63 -vi15  rsmak
henry c -vt1 -v5 -vb79 -vr63 -vi15  jaxproj
henry c -vt1 -v5 -vb79 -vr63 -vi15  mileball
henry c -vt1 -v5 -vb79 -vr63 -vi15  repfly

